/* Streetview Journey v0.1.37 fixed playback clock */
(()=>{
  const VERSION='0.1.37';
  const BASE_FILTER='brightness(.9) contrast(1.08) saturate(.94)';
  const TILE_COLS=4,TILE_ROWS=5,ANALYSIS_W=80,ANALYSIS_H=120;
  const ROLL_LIMIT=3.0,ROLL_EMA=.13,ROLL_STEP_LIMIT=.22;
  const RAW_PRELOAD_AHEAD=12,HEAVY_PRELOAD_AHEAD=3,PAIR_PRELOAD_AHEAD=2;
  const VECTOR_SMOOTH=.62,VECTOR_PASSES=3;
  const MAX_NEIGHBOR_DX=1.65,MAX_NEIGHBOR_DY=1.25,TILE_OVERLAP_CSS_PX=12;
  const ACCUM_SCALE=.16,NORMALIZE_SCALE=.40,MIN_WEIGHT_BYTE=3;
  const BRIDGE_RADIAL_GAIN=.014,BRIDGE_MIN_STRENGTH=.18;
  const FAR_X0=10,FAR_X1=70,FAR_Y0=18,FAR_Y1=82,FAR_SEARCH_X=6,FAR_SEARCH_Y=5,FAR_MIN_CONFIDENCE=.018;
  const ANCHOR_WINDOW_RADIUS=2,CAMERA_WINDOW_RADIUS=3,CAMERA_MIN_TRACKS=8;
  const CAMERA_MAX_STEP_X=5.2,CAMERA_MAX_STEP_Y=4.0;
  const CAMERA_MAX_CORR_X=8.5,CAMERA_MAX_CORR_Y=6.2,CAMERA_MAX_CORR_ROLL=2.4,CAMERA_MIN_SCALE=.980,CAMERA_MAX_SCALE=1.020;
  const CAMERA_RANSAC_STRONG=.34,CAMERA_RANSAC_BLEND=.14,SAFETY_GUARD_STRONG=.58;
  const CANVAS_BOX_SCALE=1.12,CAMERA_ANALYSIS_OVERSCAN=1.045,CAMERA_FOREGROUND_OVERSCAN=1.16,CAMERA_EDGE_FILL_OVERSCAN=1.38;
  const WORKER_WAIT_MS=85,STREAM_WAIT_MS=120,CACHE_BEHIND=14,RENDER_TIMEOUT_MS=8000,CORS_TIMEOUT_MS=1800;
  const $=id=>document.getElementById(id),sleep=ms=>new Promise(r=>setTimeout(r,ms)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const rad=v=>v*Math.PI/180,deg=v=>v*180/Math.PI;
  const cosineRamp=t=>.5-.5*Math.cos(Math.PI*clamp(t,0,1));
  const idle=fn=>('requestIdleCallback'in window?requestIdleCallback(()=>fn(),{timeout:90}):setTimeout(fn,0));

  function installUI(){
    const viewer=$('viewer'),card=document.querySelector('.start-card');
    if(viewer&&!$('flowCanvas')){const c=document.createElement('canvas');c.id='flowCanvas';c.className='flow-canvas';viewer.querySelector('#layerB')?.insertAdjacentElement('afterend',c)}
    if(viewer&&!$('journeyBack')){const b=document.createElement('button');b.id='journeyBack';b.className='journey-back';b.type='button';b.hidden=true;b.innerHTML='<span aria-hidden="true">‹</span> 戻る';viewer.appendChild(b)}
    if(card){card.querySelector('.eyebrow').textContent='v0.1.37 FIXED CLOCK';card.querySelector('h1').textContent='0.08秒の再生を最優先。解析は完全に先読み。';card.querySelector('.lead').textContent='次画像が読めていれば時刻どおり切替。Optical Flowが間に合った区間だけ高品質補正を使う。'}
    let s=$('stabilizedTileStyles');if(!s){s=document.createElement('style');s.id='stabilizedTileStyles';document.head.appendChild(s)}
    s.textContent=`.flow-canvas{position:absolute;z-index:2;left:-6%;top:-6%;width:112%;height:112%;opacity:0;pointer-events:none;filter:${BASE_FILTER};will-change:contents}.scene-layer{z-index:1}.vignette,.motion-blur{z-index:3}.top-hud,.bottom-hud{z-index:4}.top-hud{padding-left:88px}.journey-back{position:absolute;z-index:6;left:14px;top:calc(var(--safe-top) + 12px);height:38px;padding:0 12px;border:1px solid rgba(255,255,255,.18);border-radius:999px;background:rgba(8,12,16,.55);color:#fff;font-size:11px;font-weight:750;backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px)}.journey-back[hidden]{display:none!important}#journeyDiag{left:auto!important;right:14px!important;top:calc(var(--safe-top) + 60px)!important;bottom:auto!important;padding:0!important;border:0!important;background:transparent!important;width:auto!important}#journeyDiag>.jd-head,#journeyDiag>#jdLine0,#journeyDiag>#jdLine1,#journeyDiag>#jdLine2,#journeyDiag>#jdLine3,#journeyDiag>#jdLine4,#journeyDiag>#jdApplied,#journeyDiag>#jdAxis,#journeyDiag .jd-log>span{display:none!important}#journeyDiag .jd-log{display:block!important;margin:0!important;padding:0!important;border:0!important}#journeyDiag #jdCopy{display:block!important;padding:8px 11px!important;font-size:10px!important;background:rgba(8,12,16,.55)!important}`;
  }
  installUI();
  const ui={viewer:$('viewer'),a:$('layerA'),b:$('layerB'),canvas:$('flowCanvas'),back:$('journeyBack'),edgeBlur:document.querySelector('.motion-blur'),start:$('startPanel'),error:$('errorPanel'),startBtn:$('startButton'),retry:$('retryButton'),err:$('errorMessage'),bar:$('progressBar'),num:$('frameLabel'),place:$('placeLabel'),heading:$('headingLabel'),coord:$('coordLabel'),net:$('networkLabel'),lat:$('latInput'),lng:$('lngInput'),coords:$('useCoordinates')};
  let route=[],token=0,wake=null,speedMs=80,ctx=null,canvasDpr=1,canvasSignature='',directStarting=false;
  let colorCanvas=null,colorCtx=null,weightCanvas=null,weightCtx=null,fallbackCanvas=null,fallbackCtx=null,outputImage=null;
  const renderCache=new Map(),renderReadyCache=new Map(),corsCache=new Map(),grayCache=new Map(),rollRawCache=new Map(),rollSmoothCache=new Map(),correctedGrayCache=new Map(),farPairCache=new Map(),workerPairCache=new Map(),motionPairCache=new Map(),rawTrajectoryCache=new Map(),cameraPoseCache=new Map(),stabilizedGrayCache=new Map(),tileCache=new Map(),anchorCache=new Map(),blendAssetCache=new Map();
  const stabilizedFrameCache=new Map(),stabilizedFrameReadyCache=new Map(),tileLayerCache=new Map(),preparedPairCache=new Map(),preparedPairReadyCache=new Map();
  const diag=window.__journeyDiagnostics={version:VERSION,worker:'starting',workerReady:false,lastWorkerPair:null,lastPairMs:0,frameCacheHits:0,tileCacheHits:0,pairCacheHits:0,deadlineFallbacks:0,opticalPairs:0,rawReady:0,targetMs:80,lastDeltaMs:0,latenessMs:0,maxLatenessMs:0,deadlineMisses:0,lastRenderPath:null,rawFallbacks:0,rawAheadReady:0,stabilizedAheadReady:0,pairAheadReady:0};

  let motionWorker=null,workerReady=false,workerSeq=0;const workerPending=new Map();
  function ensureMotionWorker(){if(motionWorker)return;try{motionWorker=new Worker('/motion-worker.js?v=0.1.25');diag.worker='loading';motionWorker.onmessage=e=>{const m=e.data||{};if(m.type==='ready'){workerReady=true;diag.worker='ready';diag.workerReady=true;return}const p=workerPending.get(m.id);if(!p)return;workerPending.delete(m.id);p.resolve(m.type==='result'?m.result:null)};motionWorker.onerror=()=>{diag.worker='fallback';workerReady=false;diag.workerReady=false;for(const p of workerPending.values())p.resolve(null);workerPending.clear()}}catch{diag.worker='fallback'}}
  function requestWorker(a,b,i){ensureMotionWorker();if(!motionWorker)return Promise.resolve(null);const aa=new Uint8Array(a.length),bb=new Uint8Array(b.length);for(let k=0;k<aa.length;k++){aa[k]=clamp(Math.round(a[k]),0,255);bb[k]=clamp(Math.round(b[k]),0,255)}const id=++workerSeq;return new Promise(resolve=>{workerPending.set(id,{resolve});try{motionWorker.postMessage({type:'analyze',id,width:ANALYSIS_W,height:ANALYSIS_H,grayA:aa.buffer,grayB:bb.buffer,seed:i*31+aa.length},[aa.buffer,bb.buffer])}catch{workerPending.delete(id);resolve(null)}})}
  ensureMotionWorker();

  function angle(a,b){return Number.isFinite(a)&&Number.isFinite(b)?((b-a+540)%360)-180:0}
  function hasCoords(f){return Number.isFinite(f?.lat)&&Number.isFinite(f?.lng)}
  function distanceMeters(a,b){if(!hasCoords(a)||!hasCoords(b))return Infinity;const p1=rad(a.lat),p2=rad(b.lat),dp=p2-p1,dl=rad(b.lng-a.lng),s=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 12742000*Math.atan2(Math.sqrt(s),Math.sqrt(Math.max(0,1-s)))}
  function bearing(a,b){if(!hasCoords(a)||!hasCoords(b))return null;const p1=rad(a.lat),p2=rad(b.lat),dl=rad(b.lng-a.lng),y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(deg(Math.atan2(y,x))+360)%360}
  function travelBearing(i){const c=route[i];if(!c)return null;let x=0,y=0,w=0;for(let s=1;s<=10&&i+s<route.length;s++){const n=route[i+s],d=distanceMeters(c,n);if(!Number.isFinite(d)||d<1)continue;const br=bearing(c,n),ww=Math.min(d,14)/Math.sqrt(s);x+=Math.cos(rad(br))*ww;y+=Math.sin(rad(br))*ww;w+=ww;if(d>=18)break}return w?(deg(Math.atan2(y,x))+360)%360:(Number.isFinite(c.heading)?c.heading:null)}
  function isSphere(f){return String(f?.projection||'').toUpperCase()==='SPHERE'||(Number.isFinite(f?.fieldOfView)&&f.fieldOfView>=180)}
  function rawAnchorX(i){const f=route[i];if(!f)return 50;const tr=travelBearing(i),ih=Number.isFinite(f.heading)?f.heading:f.projectionYaw;if(!Number.isFinite(tr)||!Number.isFinite(ih))return 50;const d=angle(ih,tr);return isSphere(f)?clamp(50+d/3.6,0,100):clamp(50+d/clamp(f.fieldOfView||100,45,170)*100,5,95)}
  function anchorX(i){if(anchorCache.has(i))return anchorCache.get(i);const base=rawAnchorX(i),sph=isSphere(route[i]);let sum=0,sw=0;for(let k=Math.max(0,i-ANCHOR_WINDOW_RADIUS);k<=Math.min(route.length-1,i+ANCHOR_WINDOW_RADIUS);k++){let v=rawAnchorX(k);if(sph||isSphere(route[k])){let d=v-base;if(d>50)d-=100;if(d<-50)d+=100;v=base+d}const d=Math.abs(k-i),w=d===0?4:d===1?2:1;sum+=v*w;sw+=w}let v=sw?sum/sw:base;if(sph)v=((v%100)+100)%100;else v=clamp(v,5,95);anchorCache.set(i,v);return v}
  function geoAlignment(i){let ad=anchorX(i)-anchorX(i+1);if(isSphere(route[i])||isSphere(route[i+1])){if(ad>50)ad-=100;if(ad<-50)ad+=100}const vw=window.innerWidth||390,turn=angle(travelBearing(i),travelBearing(i+1));return{x:clamp(ad/100*vw*.16-turn*.18,-15,15),y:0}}
  function perceptualBridgeStrength(i){const d=distanceMeters(route[i],route[i+1]),t=Math.abs(angle(travelBearing(i),travelBearing(i+1))),dp=Number.isFinite(d)?clamp((d-1.2)/7,0,1):.35,tp=clamp(t/32,0,1);return clamp(BRIDGE_MIN_STRENGTH+dp*.62+tp*.20,BRIDGE_MIN_STRENGTH,1)}

  function loadRender(url){if(!url)return Promise.reject(new Error('画像URLがありません'));if(!renderCache.has(url))renderCache.set(url,new Promise((res,rej)=>{const im=new Image(),tm=setTimeout(()=>{renderCache.delete(url);renderReadyCache.delete(url);rej(new Error('画像読み込みがタイムアウトしました'))},RENDER_TIMEOUT_MS);im.decoding='async';im.referrerPolicy='no-referrer';im.onload=()=>{clearTimeout(tm);renderReadyCache.set(url,im);diag.rawReady=renderReadyCache.size;res(im)};im.onerror=()=>{clearTimeout(tm);renderCache.delete(url);renderReadyCache.delete(url);rej(new Error('画像を読み込めませんでした'))};im.src=url}));return renderCache.get(url)}
  function loadCors(url){if(!url)return Promise.resolve(null);if(!corsCache.has(url))corsCache.set(url,new Promise(res=>{const im=new Image(),tm=setTimeout(()=>{corsCache.delete(url);res(null)},CORS_TIMEOUT_MS);im.crossOrigin='anonymous';im.referrerPolicy='no-referrer';im.onload=()=>{clearTimeout(tm);res(im)};im.onerror=()=>{clearTimeout(tm);corsCache.delete(url);res(null)};im.src=`${url}${url.includes('?')?'&':'?'}analysis=v0137`}));return corsCache.get(url)}
  function makeCanvas(w,h,alpha){const c=document.createElement('canvas');c.width=w;c.height=h;return{canvas:c,ctx:c.getContext('2d',{alpha,willReadFrequently:true})}}
  function canvasSize(){const dpr=Math.min(window.devicePixelRatio||1,1),w=Math.round((window.innerWidth||390)*CANVAS_BOX_SCALE*dpr),h=Math.round((window.innerHeight||844)*CANVAS_BOX_SCALE*dpr);if(ui.canvas.width!==w||ui.canvas.height!==h){ui.canvas.width=w;ui.canvas.height=h}ctx=ui.canvas.getContext('2d',{alpha:false});canvasDpr=dpr;const sig=`${w}x${h}@${dpr}`;if(sig!==canvasSignature){canvasSignature=sig;blendAssetCache.clear();tileLayerCache.clear();preparedPairCache.clear();preparedPairReadyCache.clear();const nw=Math.max(160,Math.round(w*NORMALIZE_SCALE)),nh=Math.max(260,Math.round(h*NORMALIZE_SCALE));({canvas:colorCanvas,ctx:colorCtx}=makeCanvas(nw,nh,false));({canvas:weightCanvas,ctx:weightCtx}=makeCanvas(nw,nh,false));({canvas:fallbackCanvas,ctx:fallbackCtx}=makeCanvas(nw,nh,false));outputImage=colorCtx.createImageData(nw,nh)}return{w,h}}
  function coverRect(c,im,a){const cw=c.width,ch=c.height,r=Math.max(cw/im.naturalWidth,ch/im.naturalHeight),dw=im.naturalWidth*r,dh=im.naturalHeight*r;return{x:(cw-dw)*a/100,y:(ch-dh)/2,w:dw,h:dh}}
  function drawTransformed(g,im,r,px,py,rot,scale,filter='none',alpha=1){const cx=g.canvas.width/2,cy=g.canvas.height/2;g.save();g.globalAlpha=alpha;g.filter=filter;g.translate(px,py);g.translate(cx,cy);g.rotate(rad(rot));g.scale(scale,scale);g.translate(-cx,-cy);g.drawImage(im,r.x,r.y,r.w,r.h);g.restore()}
  function drawBase(g,im,i,roll,pose=null,alpha=1,mode='analysis'){const r=coverRect(g.canvas,im,anchorX(i)),px=pose?pose.x*g.canvas.width/ANALYSIS_W:0,py=pose?pose.y*g.canvas.height/ANALYSIS_H:0,ps=pose?.scale||1,rot=roll+(pose?.roll||0);if(mode==='render'){drawTransformed(g,im,r,px,py,rot,CAMERA_EDGE_FILL_OVERSCAN*ps,'blur(12px) saturate(.92)',alpha);drawTransformed(g,im,r,px,py,rot,CAMERA_FOREGROUND_OVERSCAN*ps,'none',alpha)}else drawTransformed(g,im,r,px,py,rot,CAMERA_ANALYSIS_OVERSCAN*ps,'none',alpha)}

  async function analysisGray(i){if(grayCache.has(i))return grayCache.get(i);const p=(async()=>{const im=await loadCors(route[i]?.url);if(!im)return null;const c=document.createElement('canvas');c.width=ANALYSIS_W;c.height=ANALYSIS_H;const g=c.getContext('2d',{willReadFrequently:true}),r=coverRect(c,im,anchorX(i));g.drawImage(im,r.x,r.y,r.w,r.h);try{const d=g.getImageData(0,0,ANALYSIS_W,ANALYSIS_H).data,o=new Float32Array(ANALYSIS_W*ANALYSIS_H);for(let k=0,j=0;k<o.length;k++,j+=4)o[k]=d[j]*.299+d[j+1]*.587+d[j+2]*.114;return o}catch{return null}})();grayCache.set(i,p);return p}
  async function rawRoll(i){if(rollRawCache.has(i))return rollRawCache.get(i);const p=(async()=>{const gray=await analysisGray(i);if(!gray)return 0;let sx=0,sy=0,sum=0;for(let y=FAR_Y0;y<FAR_Y1;y+=2)for(let x=FAR_X0;x<FAR_X1;x+=2){const gx=gray[y*ANALYSIS_W+x+1]-gray[y*ANALYSIS_W+x-1],gy=gray[(y+1)*ANALYSIS_W+x]-gray[(y-1)*ANALYSIS_W+x],mag=Math.hypot(gx,gy);if(mag<20)continue;const th=Math.atan2(gy,gx),ad=Math.min(Math.abs(Math.sin(th)),Math.abs(Math.cos(th)));if(ad>.42)continue;const w=Math.min(mag,170);sx+=Math.cos(4*th)*w;sy+=Math.sin(4*th)*w;sum+=w}if(!sum||Math.hypot(sx,sy)/sum<.08)return 0;let c=-deg(Math.atan2(sy,sx))/4;while(c>22.5)c-=45;while(c<-22.5)c+=45;return clamp(c,-ROLL_LIMIT,ROLL_LIMIT)})();rollRawCache.set(i,p);return p}
  function smoothRoll(i){if(rollSmoothCache.has(i))return rollSmoothCache.get(i);const p=(async()=>{const raw=await rawRoll(i);if(i===0)return clamp(raw*.55,-ROLL_LIMIT,ROLL_LIMIT);const prev=await smoothRoll(i-1),target=prev*(1-ROLL_EMA)+raw*ROLL_EMA;return clamp(prev+clamp(target-prev,-ROLL_STEP_LIMIT,ROLL_STEP_LIMIT),-ROLL_LIMIT,ROLL_LIMIT)})();rollSmoothCache.set(i,p);return p}
  async function correctedGray(i){if(correctedGrayCache.has(i))return correctedGrayCache.get(i);const p=(async()=>{const im=await loadCors(route[i]?.url);if(!im)return null;const roll=await smoothRoll(i),c=document.createElement('canvas');c.width=ANALYSIS_W;c.height=ANALYSIS_H;const g=c.getContext('2d',{willReadFrequently:true});g.fillStyle='#111';g.fillRect(0,0,ANALYSIS_W,ANALYSIS_H);drawBase(g,im,i,roll);try{const d=g.getImageData(0,0,ANALYSIS_W,ANALYSIS_H).data,o=new Float32Array(ANALYSIS_W*ANALYSIS_H);for(let k=0,j=0;k<o.length;k++,j+=4)o[k]=d[j]*.299+d[j+1]*.587+d[j+2]*.114;return o}catch{return null}})();correctedGrayCache.set(i,p);return p}
  function farScore(a,b,dx,dy){let s=0,w=0;for(let y=FAR_Y0+2;y<FAR_Y1-2;y+=2){const by=y+dy;if(by<1||by>=ANALYSIS_H-1)continue;for(let x=FAR_X0+2;x<FAR_X1-2;x+=2){const bx=x+dx;if(bx<1||bx>=ANALYSIS_W-1)continue;s+=Math.abs(a[y*ANALYSIS_W+x]-b[by*ANALYSIS_W+bx]);w++}}return w?s/w:1e9}
  async function farPair(i){if(farPairCache.has(i))return farPairCache.get(i);const p=(async()=>{const[a,b]=await Promise.all([correctedGray(i),correctedGray(i+1)]);if(!a||!b)return{dx:0,dy:0,confidence:0};const base=farScore(a,b,0,0);let best={dx:0,dy:0,score:base};for(let dy=-FAR_SEARCH_Y;dy<=FAR_SEARCH_Y;dy++)for(let dx=-FAR_SEARCH_X;dx<=FAR_SEARCH_X;dx++){const sc=farScore(a,b,dx,dy);if(sc<best.score)best={dx,dy,score:sc}}const confidence=clamp((base-best.score)/Math.max(base,1),0,1);return confidence<FAR_MIN_CONFIDENCE?{dx:0,dy:0,confidence}:{dx:best.dx,dy:best.dy,confidence}})();farPairCache.set(i,p);return p}
  async function workerFeaturePair(i){if(workerPairCache.has(i))return workerPairCache.get(i);const p=(async()=>{const[a,b]=await Promise.all([correctedGray(i),correctedGray(i+1)]);if(!a||!b)return{dx:0,dy:0,roll:0,logScale:0,confidence:0,tracks:0,source:'fallback'};const result=requestWorker(a,b,i).then(r=>{if(r)diag.lastWorkerPair={frame:i,...r};return r});return await Promise.race([result,sleep(WORKER_WAIT_MS).then(()=>null)])||{dx:0,dy:0,roll:0,logScale:0,confidence:0,tracks:0,source:'worker-pending'}})();workerPairCache.set(i,p);return p}
  async function motionPair(i){if(motionPairCache.has(i))return motionPairCache.get(i);const p=(async()=>{const[wp,far]=await Promise.all([workerFeaturePair(i),farPair(i)]),sf=Number.isFinite(wp.safetyFactor)?clamp(wp.safetyFactor,0,1):1,strong=sf<.95?SAFETY_GUARD_STRONG:CAMERA_RANSAC_STRONG;if(wp.confidence>=strong)return wp;if(wp.confidence>=CAMERA_RANSAC_BLEND&&wp.tracks>=CAMERA_MIN_TRACKS){const w=clamp(.38+(wp.confidence-CAMERA_RANSAC_BLEND)/Math.max(.001,CAMERA_RANSAC_STRONG-CAMERA_RANSAC_BLEND)*.48,.30,.86);return{dx:clamp(wp.dx*w+far.dx*(1-w),-CAMERA_MAX_STEP_X,CAMERA_MAX_STEP_X),dy:clamp(wp.dy*w+far.dy*(1-w),-CAMERA_MAX_STEP_Y,CAMERA_MAX_STEP_Y),roll:wp.roll*w,logScale:wp.logScale*w,confidence:Math.max(wp.confidence*.9,far.confidence*.6),tracks:wp.tracks,source:'blend'}}return{dx:clamp(far.dx,-CAMERA_MAX_STEP_X,CAMERA_MAX_STEP_X),dy:clamp(far.dy,-CAMERA_MAX_STEP_Y,CAMERA_MAX_STEP_Y),roll:0,logScale:0,confidence:far.confidence*.58,tracks:0,source:'far'}})();motionPairCache.set(i,p);return p}
  function rawTrajectory(i){if(rawTrajectoryCache.has(i))return rawTrajectoryCache.get(i);const p=(async()=>{if(i<=0)return{x:0,y:0,roll:0,logScale:0,confidence:1};const[prev,pair]=await Promise.all([rawTrajectory(i-1),motionPair(i-1)]);return{x:prev.x+pair.dx,y:prev.y+pair.dy,roll:prev.roll+pair.roll,logScale:prev.logScale+pair.logScale,confidence:pair.confidence}})();rawTrajectoryCache.set(i,p);return p}
  function cameraPose(i){if(cameraPoseCache.has(i))return cameraPoseCache.get(i);const p=(async()=>{const start=Math.max(0,i-CAMERA_WINDOW_RADIUS),end=Math.min(route.length-1,i+CAMERA_WINDOW_RADIUS),inds=[];for(let k=start;k<=end;k++)inds.push(k);const list=await Promise.all(inds.map(rawTrajectory)),raw=await rawTrajectory(i);let sx=0,sy=0,sr=0,ss=0,sw=0;for(let n=0;n<list.length;n++){const d=Math.abs(inds[n]-i),w=d===0?6:d===1?4:d===2?2:1;sx+=list[n].x*w;sy+=list[n].y*w;sr+=list[n].roll*w;ss+=list[n].logScale*w;sw+=w}return{x:clamp(sx/sw-raw.x,-CAMERA_MAX_CORR_X,CAMERA_MAX_CORR_X),y:clamp(sy/sw-raw.y,-CAMERA_MAX_CORR_Y,CAMERA_MAX_CORR_Y),roll:clamp(sr/sw-raw.roll,-CAMERA_MAX_CORR_ROLL,CAMERA_MAX_CORR_ROLL),scale:clamp(Math.exp(ss/sw-raw.logScale),CAMERA_MIN_SCALE,CAMERA_MAX_SCALE),confidence:raw.confidence,source:'mixed'}})();cameraPoseCache.set(i,p);return p}
  async function stabilizedGray(i){if(stabilizedGrayCache.has(i))return stabilizedGrayCache.get(i);const p=(async()=>{const im=await loadCors(route[i]?.url);if(!im)return null;const[roll,pose]=await Promise.all([smoothRoll(i),cameraPose(i)]),c=document.createElement('canvas');c.width=ANALYSIS_W;c.height=ANALYSIS_H;const g=c.getContext('2d',{willReadFrequently:true});g.fillStyle='#111';g.fillRect(0,0,ANALYSIS_W,ANALYSIS_H);drawBase(g,im,i,roll,pose);try{const d=g.getImageData(0,0,ANALYSIS_W,ANALYSIS_H).data,o=new Float32Array(ANALYSIS_W*ANALYSIS_H);for(let k=0,j=0;k<o.length;k++,j+=4)o[k]=d[j]*.299+d[j+1]*.587+d[j+2]*.114;return o}catch{return null}})();stabilizedGrayCache.set(i,p);return p}
  function blockScore(a,b,x0,y0,x1,y1,dx,dy){let s=0,c=0;for(let y=y0+3;y<y1-3;y+=2){const by=y+dy;if(by<1||by>=ANALYSIS_H-1)continue;for(let x=x0+3;x<x1-3;x+=2){const bx=x+dx;if(bx<1||bx>=ANALYSIS_W-1)continue;s+=Math.abs(a[y*ANALYSIS_W+x]-b[by*ANALYSIS_W+bx]);c++}}return c?s/c:1e9}
  function smoothVectorField(vs){let field=vs.map(v=>({...v}));for(let pass=0;pass<VECTOR_PASSES;pass++){const prev=field;field=prev.map(v=>{let sx=v.vx*2.7,sy=v.vy*2.7,sw=2.7;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const c=v.col+dx,r=v.row+dy;if(c<0||c>=TILE_COLS||r<0||r>=TILE_ROWS)continue;const n=prev[r*TILE_COLS+c],w=dx&&dy?.52:.94;sx+=n.vx*w;sy+=n.vy*w;sw+=w}return{...v,vx:clamp(v.vx*(1-VECTOR_SMOOTH)+sx/sw*VECTOR_SMOOTH,-4.8,4.8),vy:clamp(v.vy*(1-VECTOR_SMOOTH)+sy/sw*VECTOR_SMOOTH,-3.6,3.6)}})}return field}
  async function tileVectors(i){if(tileCache.has(i))return tileCache.get(i);const p=(async()=>{const geo=geoAlignment(i),gx=geo.x/Math.max(320,innerWidth||390)*ANALYSIS_W,[a,b]=await Promise.all([stabilizedGray(i),stabilizedGray(i+1)]),vs=[];for(let row=0;row<TILE_ROWS;row++)for(let col=0;col<TILE_COLS;col++){let vx=gx,vy=0,confidence=0;if(a&&b){const x0=Math.floor(col*ANALYSIS_W/TILE_COLS),x1=Math.floor((col+1)*ANALYSIS_W/TILE_COLS),y0=Math.floor(row*ANALYSIS_H/TILE_ROWS),y1=Math.floor((row+1)*ANALYSIS_H/TILE_ROWS),base=blockScore(a,b,x0,y0,x1,y1,0,0);let best={dx:0,dy:0,score:base};for(let dy=-3;dy<=3;dy++)for(let dx=-3;dx<=3;dx++){const sc=blockScore(a,b,x0,y0,x1,y1,dx,dy);if(sc<best.score)best={dx,dy,score:sc}}confidence=clamp((base-best.score)/Math.max(base,1),0,1);if(confidence>=.018){vx=best.dx*.78+gx*.22;vy=best.dy*.78}}vs.push({col,row,vx:clamp(vx,-4.8,4.8),vy:clamp(vy,-3.6,3.6),confidence})}return smoothVectorField(vs)})();tileCache.set(i,p);return p}

  function createStabilizedFrame(i){if(stabilizedFrameCache.has(i)){diag.frameCacheHits++;return stabilizedFrameCache.get(i)}const p=(async()=>{const im=await loadRender(route[i]?.url),{w,h}=canvasSize(),[roll,pose]=await Promise.all([smoothRoll(i),cameraPose(i)]),c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d',{alpha:false});g.fillStyle='#05070a';g.fillRect(0,0,w,h);drawBase(g,im,i,roll,pose,1,'render');const out={canvas:c,roll:roll+pose.roll,pose,image:im,index:i};stabilizedFrameReadyCache.set(i,out);return out})();stabilizedFrameCache.set(i,p);p.catch(()=>{stabilizedFrameCache.delete(i);stabilizedFrameReadyCache.delete(i)});return p}
  function preparePair(i){if(preparedPairCache.has(i)){diag.pairCacheHits++;return preparedPairCache.get(i)}const p=(async()=>{if(!route[i]||!route[i+1])throw new Error('Pair画像が不足しています');const[a,b,vs]=await Promise.all([createStabilizedFrame(i),createStabilizedFrame(i+1),tileVectors(i)]);const out={i,a,b,vs,bs:perceptualBridgeStrength(i)};preparedPairReadyCache.set(i,out);return out})();preparedPairCache.set(i,p);p.catch(()=>{preparedPairCache.delete(i);preparedPairReadyCache.delete(i)});return p}

  function streamState(){return window.__journeyStreamState||null}
  function syncStreamFrames(){const s=streamState();if(!s||!Array.isArray(s.frames))return 0;const seen=new Set(route.map(f=>String(f?.id||f?.url||'')));let added=0;for(const f of s.frames){const k=String(f?.id||f?.url||'');if(!k||seen.has(k))continue;seen.add(k);route.push(f);added++}return added}
  function aheadCounts(i){let raw=0,st=0,pair=0;for(let k=i+1;k<=Math.min(route.length-1,i+RAW_PRELOAD_AHEAD);k++)if(renderReadyCache.has(route[k]?.url))raw++;for(let k=i+1;k<=Math.min(route.length-1,i+RAW_PRELOAD_AHEAD);k++)if(stabilizedFrameReadyCache.has(k))st++;for(let k=i;k<Math.min(route.length-1,i+PAIR_PRELOAD_AHEAD);k++)if(preparedPairReadyCache.has(k))pair++;diag.rawAheadReady=raw;diag.stabilizedAheadReady=st;diag.pairAheadReady=pair;return{raw,st,pair}}
  function warmAhead(i){syncStreamFrames();for(let k=i;k<Math.min(route.length,i+RAW_PRELOAD_AHEAD+1);k++){const u=route[k]?.url;if(u&&!renderReadyCache.has(u))loadRender(u).catch(()=>{})}idle(()=>{for(let k=i;k<Math.min(route.length,i+HEAVY_PRELOAD_AHEAD+1);k++)smoothRoll(k).catch(()=>{});for(let k=i;k<Math.min(route.length-1,i+HEAVY_PRELOAD_AHEAD);k++)workerFeaturePair(k).catch(()=>{});for(let k=i;k<Math.min(route.length-1,i+PAIR_PRELOAD_AHEAD);k++)preparePair(k).catch(()=>{})})}
  function trimJourneyCaches(i){const cut=Math.max(0,i-CACHE_BEHIND);for(let k=0;k<cut;k++){const u=route[k]?.url;if(u){renderCache.delete(u);renderReadyCache.delete(u);corsCache.delete(u)}grayCache.delete(k);rollRawCache.delete(k);rollSmoothCache.delete(k);correctedGrayCache.delete(k);farPairCache.delete(k);workerPairCache.delete(k);motionPairCache.delete(k);rawTrajectoryCache.delete(k);cameraPoseCache.delete(k);stabilizedGrayCache.delete(k);tileCache.delete(k);anchorCache.delete(k);stabilizedFrameCache.delete(k);stabilizedFrameReadyCache.delete(k);preparedPairCache.delete(k);preparedPairReadyCache.delete(k)}diag.rawReady=renderReadyCache.size}
  function updateHud(i,roll=0,pose=null,path=null){const s=streamState(),total=Math.max(route.length,s?.total||0),ahead=aheadCounts(i);window.__journeyPlaybackState={index:i,available:route.length,total,streaming:!!s?.active,targetMs:speedMs,lastDeltaMs:diag.lastDeltaMs,latenessMs:diag.latenessMs,maxLatenessMs:diag.maxLatenessMs,deadlineMisses:diag.deadlineMisses,lastRenderPath:path||diag.lastRenderPath,rawFallbacks:diag.rawFallbacks,opticalPairs:diag.opticalPairs,rawAheadReady:ahead.raw,stabilizedAheadReady:ahead.st,pairAheadReady:ahead.pair};ui.num.textContent=`${i+1} / ${total||route.length}`;ui.bar.style.width=`${total?((i+1)/total*100):0}%`;const d=travelBearing(i);ui.heading.textContent=Number.isFinite(d)?`${Math.round(d)}°`:'—°';ui.coord.textContent=hasCoords(route[i])?`${route[i].lat.toFixed(5)}, ${route[i].lng.toFixed(5)}`:'—';ui.net.textContent=s?.active?`再生中・続きを準備 ${route.length}/${total}`:`${(speedMs/1000).toFixed(2)}秒`}
  function drawRaw(i,im){const{w,h}=canvasSize();ctx.fillStyle='#05070a';ctx.fillRect(0,0,w,h);const r=coverRect(ui.canvas,im,anchorX(i));ctx.drawImage(im,r.x,r.y,r.w,r.h)}
  function presentFrame(i,dueAt){const now=performance.now(),late=Math.max(0,now-dueAt),st=stabilizedFrameReadyCache.get(i),im=renderReadyCache.get(route[i]?.url);diag.latenessMs=late;diag.maxLatenessMs=Math.max(diag.maxLatenessMs,late);if(late>speedMs*.45)diag.deadlineMisses++;let path;if(st){ctx.globalAlpha=1;ctx.drawImage(st.canvas,0,0,ui.canvas.width,ui.canvas.height);path=preparedPairReadyCache.has(i-1)?'optical-ready-frame':'stabilized';if(path==='optical-ready-frame')diag.opticalPairs++;updateHud(i,st.roll,st.pose,path)}else if(im){drawRaw(i,im);path='raw-fallback';diag.deadlineFallbacks++;diag.rawFallbacks++;updateHud(i,0,null,path)}else return false;diag.lastRenderPath=path;try{window.dispatchEvent(new CustomEvent('journey-frame-presented',{detail:{index:i,dueMs:Math.round(dueAt),actualMs:Math.round(now),latenessMs:Math.round(late*10)/10,path,ahead:aheadCounts(i)}}))}catch{}return true}
  async function showFirst(){syncStreamFrames();const f=route[0];if(!f?.url)throw new Error('先頭画像URLがありません');const im=await loadRender(f.url);drawRaw(0,im);ui.canvas.style.opacity='1';ui.a.style.opacity=ui.b.style.opacity='0';updateHud(0,0,null,'raw-first');try{window.dispatchEvent(new CustomEvent('journey-playback-started',{detail:{index:0,available:route.length,total:Math.max(route.length,streamState()?.total||0)}}))}catch{}}
  function clearJourneyCaches(){[renderCache,renderReadyCache,corsCache,grayCache,rollRawCache,rollSmoothCache,correctedGrayCache,farPairCache,workerPairCache,motionPairCache,rawTrajectoryCache,cameraPoseCache,stabilizedGrayCache,tileCache,anchorCache,blendAssetCache,stabilizedFrameCache,stabilizedFrameReadyCache,tileLayerCache,preparedPairCache,preparedPairReadyCache].forEach(c=>c.clear());Object.assign(diag,{lastPairMs:0,frameCacheHits:0,tileCacheHits:0,pairCacheHits:0,deadlineFallbacks:0,opticalPairs:0,rawReady:0,lastDeltaMs:0,latenessMs:0,maxLatenessMs:0,deadlineMisses:0,lastRenderPath:null,rawFallbacks:0,rawAheadReady:0,stabilizedAheadReady:0,pairAheadReady:0})}
  async function waitForStreamFrame(i,pt){while(pt===token){syncStreamFrames();if(i+1<route.length)return true;const s=streamState();if(!s||(!s.active&&s.complete))return false;ui.net.textContent=`バッファ待機 ${route.length}/${Math.max(route.length,s.total||0)}`;await sleep(STREAM_WAIT_MS)}return false}
  async function play(frames){const pt=++token;route=Array.isArray(frames)?frames.slice():[];syncStreamFrames();clearJourneyCaches();diag.targetMs=speedMs;if(!route.length)throw new Error('再生できる画像がありません');ui.place.textContent=route[0].sequenceId?`Sequence #${route[0].sequenceId}`:'Journey';await showFirst();warmAhead(0);let i=0,lastPresented=performance.now(),nextAt=lastPresented+speedMs;while(pt===token){syncStreamFrames();if(i>=route.length-1){const hasNext=await waitForStreamFrame(i,pt);if(!hasNext)break;nextAt=performance.now()+speedMs}warmAhead(i+1);const wait=nextAt-performance.now();if(wait>1)await sleep(Math.max(0,wait-1));if(pt!==token)return;while(performance.now()<nextAt&&pt===token)await new Promise(r=>requestAnimationFrame(r));if(pt!==token)return;const target=i+1;let ok=presentFrame(target,nextAt);if(!ok){const u=route[target]?.url;if(u)loadRender(u).catch(()=>{});diag.deadlineMisses++;diag.lastRenderPath='not-ready';try{window.dispatchEvent(new CustomEvent('journey-deadline-fallback',{detail:{index:target,reason:'image-not-ready',ahead:aheadCounts(i)}}))}catch{}await sleep(8);continue}const now=performance.now();diag.lastDeltaMs=now-lastPresented;lastPresented=now;i=target;trimJourneyCaches(i);warmAhead(i);nextAt=lastPresented+speedMs}if(pt===token){window.__journeyPlaybackState={...(window.__journeyPlaybackState||{}),index:i,available:route.length,total:Math.max(route.length,streamState()?.total||0),streaming:false,complete:true};try{window.dispatchEvent(new CustomEvent('journey-playback-ended',{detail:{index:i}}))}catch{}ui.net.textContent='Journey完了'}}

  async function fetchRoute(){const p=new URLSearchParams({source:'karta'});if(ui.coords.checked){const lat=Number(ui.lat.value),lng=Number(ui.lng.value);if(!Number.isFinite(lat)||!Number.isFinite(lng))throw new Error('緯度・経度を確認してください');p.set('lat',String(lat));p.set('lng',String(lng));p.set('radius','1200')}else{p.set('sequence','6187609');p.set('index','650')}const r=await fetch(`/api/imagery?${p}`,{cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`API error ${r.status}`);if(!Array.isArray(d.frames)||d.frames.length<2)throw new Error('連続して再生できる写真が見つかりませんでした');return d}
  async function requestWakeLock(){if(!('wakeLock'in navigator))return;try{wake=await navigator.wakeLock.request('screen')}catch{}}
  function showStartError(e){ui.canvas.style.opacity='0';ui.back.hidden=true;ui.err.textContent=e?.message||'不明なエラーが発生しました';ui.error.hidden=false;ui.start.hidden=true;ui.startBtn.disabled=false;ui.startBtn.textContent='旅をはじめる'}
  async function start(){if(directStarting)return;ui.startBtn.disabled=true;ui.startBtn.textContent='旅を準備中…';ui.error.hidden=true;speedMs=80;try{const d=await fetchRoute();ui.start.hidden=true;ui.back.hidden=false;requestWakeLock();await play(d.frames)}catch(e){showStartError(e)}}
  async function startFrames(initialFrames,streamStateArg=null){if(directStarting)return;directStarting=true;ui.error.hidden=true;speedMs=80;try{if(!Array.isArray(initialFrames)||initialFrames.length<2)throw new Error('地図側の初期バッファが不足しています');if(streamStateArg)window.__journeyStreamState=streamStateArg;ui.start.hidden=true;ui.back.hidden=false;requestWakeLock();await play(initialFrames)}catch(e){showStartError(e);throw e}finally{directStarting=false}}
  async function reset(){token++;ui.canvas.style.opacity='0';ui.a.style.opacity=ui.b.style.opacity='0';ui.back.hidden=true;ui.error.hidden=true;ui.start.hidden=false;try{await wake?.release?.()}catch{}wake=null}
  window.JourneyEngine={startFrames,reset,getState:()=>({...window.__journeyPlaybackState,routeLength:route.length,version:VERSION,frameCache:stabilizedFrameCache.size,tileLayerCache:tileLayerCache.size,pairCache:preparedPairCache.size,readyFrames:renderReadyCache.size,readyPairs:preparedPairReadyCache.size,deadlineFallbacks:diag.deadlineFallbacks,opticalPairs:diag.opticalPairs,targetMs:speedMs,lastDeltaMs:diag.lastDeltaMs,latenessMs:diag.latenessMs,maxLatenessMs:diag.maxLatenessMs,deadlineMisses:diag.deadlineMisses,lastRenderPath:diag.lastRenderPath,rawFallbacks:diag.rawFallbacks,rawAheadReady:diag.rawAheadReady,stabilizedAheadReady:diag.stabilizedAheadReady,pairAheadReady:diag.pairAheadReady})};
  try{window.dispatchEvent(new CustomEvent('journey-engine-ready',{detail:{version:VERSION}}))}catch{}
  ui.startBtn?.addEventListener('click',start);ui.retry?.addEventListener('click',reset);ui.back?.addEventListener('click',reset);console.info(`Streetview Journey v${VERSION}`);
})();