function closeSearch(){if(!$('searchPanel'))return;$('searchPanel').hidden=true;$('planner')?.classList.remove('search-open');$('searchResults').hidden=true}
function toggleSearch(){const panel=$('searchPanel'),open=panel.hidden;panel.hidden=!open;$('planner')?.classList.toggle('search-open',open);if(open){setTimeout(()=>$('mapSearch').focus(),80)}else $('searchResults').hidden=true}
async function handleSearch(){const q=$('mapSearch').value.trim();if(!q)return;$('searchResults').hidden=false;$('searchResults').innerHTML='<button disabled>検索中…</button>';try{const rows=await searchLocation(q);if(!rows?.length)throw new Error('見つかりませんでした');$('searchResults').innerHTML=rows.map((r,i)=>`<button type="button" data-i="${i}"><b>${escapeHtml(r.name.split(',')[0])}</b><small>${escapeHtml(r.name)}</small></button>`).join('');$('searchResults').querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{const r=rows[+btn.dataset.i];closeSearch();state.map.flyTo({center:[r.lng,r.lat],zoom:14});chooseDestination({name:r.name.split(',')[0],type:'attraction',lat:r.lat,lng:r.lng})}))}catch(e){$('searchResults').innerHTML=`<button disabled>${escapeHtml(e?.message||e)}</button>`}}
function boot(){
  initMap();resetPlanner();if(!token())openTokenSheet();
  $('showRoutes').addEventListener('click',beginRouteChoice);$('registerStart').addEventListener('click',registerStartPoint);$('resetRoute').addEventListener('click',resetPlanner);$('tripStart').addEventListener('click',startJourney);$('backToPlanner').addEventListener('click',backToPlanner);$('finishJourney').addEventListener('click',finishJourney);
  $('playToggle').addEventListener('click',()=>state.playing?pausePlayback('user-pause'):playback());$('toggleDiag').addEventListener('click',()=>{$('diag').classList.toggle('is-open');renderDiagnostics()});$('copyDiag').addEventListener('click',copyDiagnostics);$('speed').addEventListener('input',()=>{$('speedOut').value=`${(Number($('speed').value)/1000).toFixed(2)}s`});
  $('journeyProgress').addEventListener('pointerdown',()=>{state.seekWasPlaying=state.playing;if(state.playing)pausePlayback('scrub',true)});$('journeyProgress').addEventListener('input',()=>{const ratio=+$('journeyProgress').value/1000,f=state.route?.frames[Math.round(ratio*((state.route?.frames.length||1)-1))];if(f){$('journeyDistance').textContent=`${distanceLabel(f.distanceFromStartM)} / ${distanceLabel(state.route.totalDistanceM)}`;$('journeyRemaining').textContent=`残り ${distanceLabel(f.remainingDistanceM)}`}});$('journeyProgress').addEventListener('change',()=>seekToRatio(+$('journeyProgress').value/1000));
  $('tokenSettings').addEventListener('click',openTokenSheet);$('saveToken').addEventListener('click',saveToken);$('cancelToken').addEventListener('click',()=>{$('tokenSheet').hidden=true});$('searchToggle').addEventListener('click',toggleSearch);$('searchButton').addEventListener('click',handleSearch);$('mapSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();handleSearch()}if(e.key==='Escape')closeSearch()});$('clearSearch').addEventListener('click',()=>{$('mapSearch').value='';$('searchResults').hidden=true;$('mapSearch').focus()});$('closeSearch').addEventListener('click',closeSearch);
  state.tripClockTimer=setInterval(()=>{if(state.stage==='trip'&&!state.playing){resetTripTiming();renderTripTimes()}},30000);addEventListener('pagehide',()=>{state.preloadGeneration++;clearInterval(state.tripClockTimer);destroyViewer()},{once:true});renderDiagnostics()
}
boot();
