/* Streetview Journey v0.1.35 playback pipeline cache */
(() => {
  const VERSION='0.1.35';
  const BASE_FILTER='brightness(.9) contrast(1.08) saturate(.94)';
  const TILE_COLS=4,TILE_ROWS=5,ANALYSIS_W=80,ANALYSIS_H=120;
  const ROLL_LIMIT=3.0,ROLL_EMA=.13,ROLL_STEP_LIMIT=.22;
  const RAW_PRELOAD_AHEAD=18,HEAVY_PRELOAD_AHEAD=3,PAIR_PRELOAD_AHEAD=2;
  const VECTOR_SMOOTH=.62,VECTOR_PASSES=3;
  const MAX_NEIGHBOR_DX=1.65,MAX_NEIGHBOR_DY=1.25,TILE_OVERLAP_CSS_PX=12;
  const ACCUM_SCALE=.16,NORMALIZE_FPS=36,FAST_80_FPS=60,NORMALIZE_SCALE=.40,MIN_WEIGHT_BYTE=3;
  const BRIDGE_RADIAL_GAIN=.014,BRIDGE_BLUR_BOOST=1.20,BRIDGE_MIN_STRENGTH=.18;
  const FAR_X0=10,FAR_X1=70,FAR_Y0=18,FAR_Y1=82,FAR_SEARCH_X=6,FAR_SEARCH_Y=5,FAR_MIN_CONFIDENCE=.018;
  const ANCHOR_WINDOW_RADIUS=2,CAMERA_WINDOW_RADIUS=3,CAMERA_MIN_TRACKS=8;
  const CAMERA_MAX_STEP_X=5.2,CAMERA_MAX_STEP_Y=4.0;
  const CAMERA_MAX_CORR_X=8.5,CAMERA_MAX_CORR_Y=6.2,CAMERA_MAX_CORR_ROLL=2.4,CAMERA_MIN_SCALE=.980,CAMERA_MAX_SCALE=1.020;
  const CAMERA_RANSAC_STRONG=.34,CAMERA_RANSAC_BLEND=.14,SAFETY_GUARD_STRONG=.58;
  const CANVAS_BOX_SCALE=1.12,CAMERA_ANALYSIS_OVERSCAN=1.045,CAMERA_FOREGROUND_OVERSCAN=1.16,CAMERA_EDGE_FILL_OVERSCAN=1.38;
  const COMPARE_SPEEDS=[80,100,120],WORKER_WAIT_MS=85,STREAM_WAIT_MS=120,CACHE_BEHIND=14,RENDER_TIMEOUT_MS=8000,CORS_TIMEOUT_MS=1800;
  const $=id=>document.getElementById(id);
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const rad=v=>v*Math.PI/180,deg=v=>v*180/Math.PI;
  const cosineRamp=t=>.5-.5*Math.cos(Math.PI*clamp(t,0,1));
  const idle=fn=>('requestIdleCallback'in window?requestIdleCallback(()=>fn(),{timeout:90}):setTimeout(fn,0));

  function installUI(){
    const viewer=$('viewer'),card=document.querySelector('.start-card');
    if(viewer&&!$('flowCanvas')){const c=document.createElement('canvas');c.id='flowCanvas';c.className='flow-canvas';viewer.querySelector('#layerB')?.insertAdjacentElement('afterend',c);}
    if(viewer&&!$('journeyBack')){const b=document.createElement('button');b.id='journeyBack';b.className='journey-back';b.type='button';b.hidden=true;b.setAttribute('aria-label','トップ画面に戻る');b.innerHTML='<span aria-hidden="true">‹</span> 戻る';viewer.appendChild(b);}
    if(card){
      card.querySelector('.eyebrow').textContent='v0.1.35 PLAYBACK PIPELINE CACHE';
      card.querySelector('h1').textContent='再生を優先し、解析は先回りする。';
      card.querySelector('.lead').textContent='補正済みFrameとTileを再利用し、重い解析は2〜3枚先だけ。Pairを事前生成して0.08秒再生の待ち時間を減らす。';
      const p=card.querySelector('.preset-card');
      if(p){p.querySelector('.preset-title').textContent='Direct Journey Engine';p.querySelector('small').textContent='Phase 1傾き補正 + Safety Gate + Tile Optical Flow / 0.08秒標準';}
      document.querySelector('.speed-lab')?.remove();
      const compare=new URLSearchParams(location.search).get('compare')==='1',lab=document.createElement('div');lab.className='speed-lab';
      const opts=compare?COMPARE_SPEEDS.map(ms=>`<label><input type="radio" name="driveSpeed" value="${ms}" ${ms===80?'checked':''}><span>${(ms/1000).toFixed(2)}秒<small>${ms===80?'標準':'比較'}</small></span></label>`).join(''):'<label><input type="radio" name="driveSpeed" value="80" checked><span>0.08秒<small>標準</small></span></label>';
      lab.innerHTML=`<div class="speed-title"><strong>Journey Engine</strong><small>${compare?'比較モード':'0.08秒を基準に改善'}</small></div><div class="speed-grid ${compare?'':'is-single'}">${opts}</div>`;p?.insertAdjacentElement('beforebegin',lab);
    }
    let s=$('stabilizedTileStyles');if(!s){s=document.createElement('style');s.id='stabilizedTileStyles';document.head.appendChild(s);}
    s.textContent=`.flow-canvas{position:absolute;z-index:2;left:-6%;top:-6%;width:112%;height:112%;opacity:0;pointer-events:none;filter:${BASE_FILTER};will-change:contents}.scene-layer{z-index:1}.vignette,.motion-blur{z-index:3}.top-hud,.bottom-hud{z-index:4}.top-hud{padding-left:88px}.journey-back{position:absolute;z-index:6;left:14px;top:calc(var(--safe-top) + 12px);height:38px;padding:0 12px;border:1px solid rgba(255,255,255,.18);border-radius:999px;background:rgba(8,12,16,.55);color:#fff;font-size:11px;font-weight:750;backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);text-shadow:0 1px 8px rgba(0,0,0,.6)}.journey-back span{font-size:23px;line-height:0;vertical-align:-2px;margin-right:2px}.journey-back[hidden]{display:none!important}.motion-blur.drive-stabilized{opacity:1!important;background:transparent;backdrop-filter:blur(var(--drive-blur,.85px));-webkit-backdrop-filter:blur(var(--drive-blur,.85px));mask-image:radial-gradient(ellipse at center,transparent 0 31%,rgba(0,0,0,.18) 49%,#000 92%);-webkit-mask-image:radial-gradient(ellipse at center,transparent 0 31%,rgba(0,0,0,.18) 49%,#000 92%);transition:none}.speed-lab{margin:0 0 12px;padding:12px;border:1px solid rgba(255,255,255,.1);border-radius:16px;background:rgba(255,255,255,.04)}.speed-title{display:flex;align-items:end;justify-content:space-between;gap:8px;margin-bottom:9px}.speed-title strong{font-size:12px}.speed-title small{font-size:9px;color:rgba(255,255,255,.48)}.speed-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.speed-grid.is-single{grid-template-columns:1fr}.speed-grid label{position:relative}.speed-grid input{position:absolute;opacity:0;pointer-events:none}.speed-grid span{display:grid;gap:3px;text-align:center;padding:10px 4px;border:1px solid rgba(255,255,255,.1);border-radius:12px;background:rgba(255,255,255,.035);font-size:11px;font-weight:750}.speed-grid span small{font-size:8px;font-weight:500;color:rgba(255,255,255,.45)}.speed-grid input:checked+span{background:#fff;color:#080b0f;border-color:#fff}.speed-grid input:checked+span small{color:rgba(8,11,15,.55)}.start-panel{overflow-y:auto}#journeyDiag{left:auto!important;right:14px!important;top:calc(var(--safe-top) + 60px)!important;bottom:auto!important;padding:0!important;border:0!important;background:transparent!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;width:auto!important}#journeyDiag>.jd-head,#journeyDiag>#jdLine0,#journeyDiag>#jdLine1,#journeyDiag>#jdLine2,#journeyDiag>#jdLine3,#journeyDiag>#jdLine4,#journeyDiag>#jdApplied,#journeyDiag>#jdAxis,#journeyDiag .jd-log>span{display:none!important}#journeyDiag .jd-log{display:block!important;margin:0!important;padding:0!important;border:0!important}#journeyDiag #jdCopy{display:block!important;padding:8px 11px!important;font-size:10px!important;background:rgba(8,12,16,.55)!important;backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px)}`;
  }
  installUI();

  const ui={viewer:$('viewer'),a:$('layerA'),b:$('layerB'),canvas:$('flowCanvas'),back:$('journeyBack'),edgeBlur:document.querySelector('.motion-blur'),start:$('startPanel'),error:$('errorPanel'),startBtn:$('startButton'),retry:$('retryButton'),err:$('errorMessage'),bar:$('progressBar'),num:$('frameLabel'),place:$('placeLabel'),heading:$('headingLabel'),coord:$('coordLabel'),net:$('networkLabel'),lat:$('latInput'),lng:$('lngInput'),coords:$('useCoordinates')};
  let route=[],token=0,wake=null,speedMs=80,ctx=null,canvasDpr=1,canvasSignature='',currentImage=null,colorCanvas=null,colorCtx=null,weightCanvas=null,weightCtx=null,fallbackCanvas=null,fallbackCtx=null,outputImage=null,directStarting=false;
  const renderCache=new Map(),corsCache=new Map(),grayCache=new Map(),rollRawCache=new Map(),rollSmoothCache=new Map(),correctedGrayCache=new Map(),farPairCache=new Map(),workerPairCache=new Map(),motionPairCache=new Map(),rawTrajectoryCache=new Map(),cameraPoseCache=new Map(),stabilizedGrayCache=new Map(),tileCache=new Map(),blendAssetCache=new Map(),anchorCache=new Map();
  const stabilizedFrameCache=new Map(),tileLayerCache=new Map(),preparedPairCache=new Map();
  const diag=window.__journeyDiagnostics={version:VERSION,engine:'jsfeat-worker',worker:'starting',workerReady:false,workerError:null,lastWorkerPair:null,lastMotionRoute:null,lastPose:null,lastPairMs:0,cameraSamples:0,averageConfidence:0,pairSamples:0,averagePairMs:0,ransacSamples:0,averageRansacInlierRatio:0,averageCoverage:0,frameCacheHits:0,tileCacheHits:0,pairCacheHits:0};

  let motionWorker=null,workerReady=false,workerSeq=0;
  const workerPending=new Map();
  function ensureMotionWorker(){if(motionWorker)return;try{motionWorker=new Worker('/motion-worker.js?v=0.1.25');diag.worker='loading';motionWorker.onmessage=e=>{const m=e.data||{};if(m.type==='ready'){workerReady=true;diag.worker='ready';diag.workerReady=true;return}const p=workerPending.get(m.id);if(!p)return;workerPending.delete(m.id);p.resolve(m.type==='result'?m.result:null)};motionWorker.onerror=e=>{diag.worker='fallback';diag.workerError=e?.message||'worker error';workerReady=false;diag.workerReady=false;for(const p of workerPending.values())p.resolve(null);workerPending.clear()}}catch(e){diag.worker='fallback';diag.workerError=String(e?.message||e)}}
  ensureMotionWorker();
  function requestWorker(grayA,grayB,i){ensureMotionWorker();if(!motionWorker)return Promise.resolve(null);const a=new Uint8Array(grayA.length),b=new Uint8Array(grayB.length);for(let k=0;k<a.length;k++){a[k]=clamp(Math.round(grayA[k]),0,255);b[k]=clamp(Math.round(grayB[k]),0,255)}const id=++workerSeq;return new Promise(resolve=>{workerPending.set(id,{resolve});try{motionWorker.postMessage({type:'analyze',id,width:ANALYSIS_W,height:ANALYSIS_H,grayA:a.buffer,grayB:b.buffer,seed:i*31+a.length},[a.buffer,b.buffer])}catch{workerPending.delete(id);resolve(null)}})}

  function angle(a,b){if(!Number.isFinite(a)||!Number.isFinite(b))return 0;return((b-a+540)%360)-180}
  function hasCoords(f){return Number.isFinite(f?.lat)&&Number.isFinite(f?.lng)}
  function distanceMeters(a,b){if(!hasCoords(a)||!hasCoords(b))return Infinity;const p1=rad(a.lat),p2=rad(b.lat),dp=p2-p1,dl=rad(b.lng-a.lng),s=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 12742000*Math.atan2(Math.sqrt(s),Math.sqrt(Math.max(0,1-s)))}
  function bearing(a,b){if(!hasCoords(a)||!hasCoords(b))return null;const p1=rad(a.lat),p2=rad(b.lat),dl=rad(b.lng-a.lng),y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(deg(Math.atan2(y,x))+360)%360}
  function travelBearing(i){const c=route[i];if(!c)return null;let x=0,y=0,w=0;for(let s=1;s<=10&&i+s<route.length;s++){const n=route[i+s],d=distanceMeters(c,n);if(!Number.isFinite(d)||d<1)continue;const br=bearing(c,n),ww=Math.min(d,14)/Math.sqrt(s);x+=Math.cos(rad(br))*ww;y+=Math.sin(rad(br))*ww;w+=ww;if(d>=18)break}return w?(deg(Math.atan2(y,x))+360)%360:(Number.isFinite(c.heading)?c.heading:null)}
  function isSphere(f){return String(f?.projection||'').toUpperCase()==='SPHERE'||(Number.isFinite(f?.fieldOfView)&&f.fieldOfView>=180)}
  function rawAnchorX(i){const f=route[i];if(!f)return 50;const tr=travelBearing(i),ih=Number.isFinite(f.heading)?f.heading:f.projectionYaw;if(!Number.isFinite(tr)||!Number.isFinite(ih))return 50;const d=angle(ih,tr);return isSphere(f)?clamp(50+d/3.6,0,100):clamp(50+d/clamp(f.fieldOfView||100,45,170)*100,5,95)}
  function anchorX(i){if(anchorCache.has(i))return anchorCache.get(i);const base=rawAnchorX(i),sph=isSphere(route[i]);let sum=0,sw=0;for(let k=Math.max(0,i-ANCHOR_WINDOW_RADIUS);k<=Math.min(route.length-1,i+ANCHOR_WINDOW_RADIUS);k++){let v=rawAnchorX(k);if(sph||isSphere(route[k])){let d=v-base;if(d>50)d-=100;if(d<-50)d+=100;v=base+d}const d=Math.abs(k-i),w=d===0?4:d===1?2:1;sum+=v*w;sw+=w}let v=sw?sum/sw:base;if(sph)v=((v%100)+100)%100;else v=clamp(v,5,95);anchorCache.set(i,v);return v}
  function geoAlignment(i){let ad=anchorX(i)-anchorX(i+1);if(isSphere(route[i])||isSphere(route[i+1])){if(ad>50)ad-=100;if(ad<-50)ad+=100}const vw=window.innerWidth||390,turn=angle(travelBearing(i),travelBearing(i+1)),d=distanceMeters(route[i],route[i+1]);return{x:clamp(ad/100*vw*.16-turn*.18,-15,15),y:0,distance:Number.isFinite(d)?d:2}}
  function perceptualBridgeStrength(i){const d=distanceMeters(route[i],route[i+1]),t=Math.abs(angle(travelBearing(i),travelBearing(i+1))),dp=Number.isFinite(d)?clamp((d-1.2)/7,0,1):.35,tp=clamp(t/32,0,1);return clamp(BRIDGE_MIN_STRENGTH+dp*.62+tp*.20,BRIDGE_MIN_STRENGTH,1)}
  function setBridge(p,s){ui.edgeBlur?.style.setProperty('--drive-blur',`${(.85+BRIDGE_BLUR_BOOST*s*Math.sin(Math.PI*clamp(p,0,1))).toFixed(2)}px`)}
  function resetBridge(){ui.edgeBlur?.style.setProperty('--drive-blur','.85px')}

  function loadRender(url){if(!renderCache.has(url))renderCache.set(url,new Promise((res,rej)=>{const im=new Image(),timer=setTimeout(()=>{renderCache.delete(url);rej(new Error('画像読み込みがタイムアウトしました'))},RENDER_TIMEOUT_MS);im.decoding='async';im.referrerPolicy='no-referrer';im.onload=()=>{clearTimeout(timer);res(im)};im.onerror=()=>{clearTimeout(timer);renderCache.delete(url);rej(new Error('画像を読み込めませんでした'))};im.src=url}));return renderCache.get(url)}
  function loadCors(url){if(!corsCache.has(url))corsCache.set(url,new Promise(res=>{const im=new Image(),done=v=>{if(timer)clearTimeout(timer);res(v)},timer=setTimeout(()=>{corsCache.delete(url);res(null)},CORS_TIMEOUT_MS);im.crossOrigin='anonymous';im.referrerPolicy='no-referrer';im.onload=()=>done(im);im.onerror=()=>{corsCache.delete(url);done(null)};im.src=`${url}${url.includes('?')?'&':'?'}analysis=v0135`}));return corsCache.get(url)}
  function makeCanvas(w,h,alpha){const c=document.createElement('canvas');c.width=w;c.height=h;return{canvas:c,ctx:c.getContext('2d',{alpha,willReadFrequently:true})}}
  function canvasSize(){const dpr=Math.min(window.devicePixelRatio||1,1),w=Math.round((window.innerWidth||390)*CANVAS_BOX_SCALE*dpr),h=Math.round((window.innerHeight||844)*CANVAS_BOX_SCALE*dpr);if(ui.canvas.width!==w||ui.canvas.height!==h){ui.canvas.width=w;ui.canvas.height=h}ctx=ui.canvas.getContext('2d',{alpha:false,willReadFrequently:true});canvasDpr=dpr;const sig=`${w}x${h}@${dpr}`;if(sig!==canvasSignature){canvasSignature=sig;blendAssetCache.clear();stabilizedFrameCache.clear();tileLayerCache.clear();preparedPairCache.clear();const nw=Math.max(160,Math.round(w*NORMALIZE_SCALE)),nh=Math.max(260,Math.round(h*NORMALIZE_SCALE));({canvas:colorCanvas,ctx:colorCtx}=makeCanvas(nw,nh,false));({canvas:weightCanvas,ctx:weightCtx}=makeCanvas(nw,nh,false));({canvas:fallbackCanvas,ctx:fallbackCtx}=makeCanvas(nw,nh,false));outputImage=colorCtx.createImageData(nw,nh)}return{w,h,dpr}}
  function coverRect(c,im,a){const cw=c.width,ch=c.height,r=Math.max(cw/im.naturalWidth,ch/im.naturalHeight),dw=im.naturalWidth*r,dh=im.naturalHeight*r;return{x:(cw-dw)*a/100,y:(ch-dh)/2,w:dw,h:dh}}
  function drawTransformed(g,im,r,px,py,rot,scale,filter='none',alpha=1){const cx=g.canvas.width/2,cy=g.canvas.height/2;g.save();g.globalAlpha=alpha;g.filter=filter;g.translate(px,py);g.translate(cx,cy);g.rotate(rad(rot));g.scale(scale,scale);g.translate(-cx,-cy);g.drawImage(im,r.x,r.y,r.w,r.h);g.restore()}
  function drawBase(g,im,i,roll,pose=null,alpha=1,mode='analysis'){const r=coverRect(g.canvas,im,anchorX(i)),px=pose?pose.x*g.canvas.width/ANALYSIS_W:0,py=pose?pose.y*g.canvas.height/ANALYSIS_H:0,ps=pose?.scale||1,rot=roll+(pose?.roll||0);if(mode==='render'){drawTransformed(g,im,r,px,py,rot,CAMERA_EDGE_FILL_OVERSCAN*ps,'blur(12px) saturate(.92)',alpha);drawTransformed(g,im,r,px,py,rot,CAMERA_FOREGROUND_OVERSCAN*ps,'none',alpha)}else drawTransformed(g,im,r,px,py,rot,CAMERA_ANALYSIS_OVERSCAN*ps,'none',alpha)}

  async function analysisGray(i){if(grayCache.has(i))return grayCache.get(i);const p=(async()=>{const im=await loadCors(route[i]?.url);if(!im)return null;const c=document.createElement('canvas');c.width=ANALYSIS_W;c.height=ANALYSIS_H;const g=c.getContext('2d',{willReadFrequently:true}),r=coverRect(c,im,anchorX(i));g.drawImage(im,r.x,r.y,r.w,r.h);try{const d=g.getImageData(0,0,ANALYSIS_W,ANALYSIS_H).data,o=new Float32Array(ANALYSIS_W*ANALYSIS_H);for(let k=0,j=0;k<o.length;k++,j+=4)o[k]=d[j]*.299+d[j+1]*.587+d[j+2]*.114;return o}catch{return null}})();grayCache.set(i,p);return p}
  function edgeMap(gray){const o=new Float32Array(ANALYSIS_W*ANALYSIS_H);if(!gray)return o;for(let y=1;y<ANALYSIS_H-1;y++)for(let x=1;x<ANALYSIS_W-1;x++){const gx=gray[y*ANALYSIS_W+x+1]-gray[y*ANALYSIS_W+x-1],gy=gray[(y+1)*ANALYSIS_W+x]-gray[(y-1)*ANALYSIS_W+x];o[y*ANALYSIS_W+x]=Math.min(255,Math.abs(gx)+Math.abs(gy))}return o}
  async function rawRoll(i){if(rollRawCache.has(i))return rollRawCache.get(i);const p=(async()=>{const gray=await analysisGray(i);if(!gray)return 0;let sx=0,sy=0,sum=0;for(let y=FAR_Y0;y<FAR_Y1;y+=2){const yw=.65+.35*((y-FAR_Y0)/Math.max(1,FAR_Y1-FAR_Y0));for(let x=FAR_X0;x<FAR_X1;x+=2){const gx=gray[y*ANALYSIS_W+x+1]-gray[y*ANALYSIS_W+x-1],gy=gray[(y+1)*ANALYSIS_W+x]-gray[(y-1)*ANALYSIS_W+x],mag=Math.hypot(gx,gy);if(mag<20)continue;const th=Math.atan2(gy,gx),ad=Math.min(Math.abs(Math.sin(th)),Math.abs(Math.cos(th)));if(ad>.42)continue;const cw=1-Math.min(.45,Math.abs(x-ANALYSIS_W/2)/ANALYSIS_W),w=Math.min(mag,170)*yw*cw;sx+=Math.cos(4*th)*w;sy+=Math.sin(4*th)*w;sum+=w}}if(!sum||Math.hypot(sx,sy)/sum<.08)return 0;let c=-deg(Math.atan2(sy,sx))/4;while(c>22.5)c-=45;while(c<-22.5)c+=45;return clamp(c,-ROLL_LIMIT,ROLL_LIMIT)})();rollRawCache.set(i,p);return p}
  function smoothRoll(i){if(rollSmoothCache.has(i))return rollSmoothCache.get(i);const p=(async()=>{const raw=await rawRoll(i);if(i===0)return clamp(raw*.55,-ROLL_LIMIT,ROLL_LIMIT);const prev=await smoothRoll(i-1),target=prev*(1-ROLL_EMA)+raw*ROLL_EMA;return clamp(prev+clamp(target-prev,-ROLL_STEP_LIMIT,ROLL_STEP_LIMIT),-ROLL_LIMIT,ROLL_LIMIT)})();rollSmoothCache.set(i,p);return p}
  async function correctedGray(i){if(correctedGrayCache.has(i))return correctedGrayCache.get(i);const p=(async()=>{const im=await loadCors(route[i]?.url);if(!im)return null;const roll=await smoothRoll(i),c=document.createElement('canvas');c.width=ANALYSIS_W;c.height=ANALYSIS_H;const g=c.getContext('2d',{willReadFrequently:true});g.fillStyle='#111';g.fillRect(0,0,ANALYSIS_W,ANALYSIS_H);drawBase(g,im,i,roll,null,1,'analysis');try{const d=g.getImageData(0,0,ANALYSIS_W,ANALYSIS_H).data,o=new Float32Array(ANALYSIS_W*ANALYSIS_H);for(let k=0,j=0;k<o.length;k++,j+=4)o[k]=d[j]*.299+d[j+1]*.587+d[j+2]*.114;return o}catch{return null}})();correctedGrayCache.set(i,p);return p}
  function farScore(a,b,dx,dy){let s=0,w=0;for(let y=FAR_Y0+2;y<FAR_Y1-2;y+=2){const by=y+dy;if(by<1||by>=ANALYSIS_H-1)continue;for(let x=FAR_X0+2;x<FAR_X1-2;x+=2){const bx=x+dx;if(bx<1||bx>=ANALYSIS_W-1)continue;const av=a[y*ANALYSIS_W+x],bv=b[by*ANALYSIS_W+bx],lw=.45+Math.min(1.6,(av+bv)/120);s+=Math.abs(av-bv)*lw;w+=lw}}return w?s/w:1e9}
  async function farPair(i){if(farPairCache.has(i))return farPairCache.get(i);const p=(async()=>{const[ga,gb]=await Promise.all([correctedGray(i),correctedGray(i+1)]);if(!ga||!gb)return{dx:0,dy:0,confidence:0};const a=edgeMap(ga),b=edgeMap(gb),base=farScore(a,b,0,0);let best={dx:0,dy:0,score:base};for(let dy=-FAR_SEARCH_Y;dy<=FAR_SEARCH_Y;dy++)for(let dx=-FAR_SEARCH_X;dx<=FAR_SEARCH_X;dx++){const sc=farScore(a,b,dx,dy);if(sc<best.score)best={dx,dy,score:sc}}const conf=clamp((base-best.score)/Math.max(base,1),0,1);return conf<FAR_MIN_CONFIDENCE?{dx:0,dy:0,confidence:conf}:{dx:best.dx,dy:best.dy,confidence:conf}})();farPairCache.set(i,p);return p}
  async function workerFeaturePair(i){if(workerPairCache.has(i))return workerPairCache.get(i);const p=(async()=>{const[ga,gb]=await Promise.all([correctedGray(i),correctedGray(i+1)]);if(!ga||!gb)return{dx:0,dy:0,roll:0,logScale:0,confidence:0,tracks:0,source:'fallback'};const resultPromise=requestWorker(ga,gb,i).then(r=>{if(!r)return null;diag.lastWorkerPair={frame:i,...r};if(r.source==='ransac'){diag.ransacSamples++;diag.averageRansacInlierRatio+=(r.inlierRatio-diag.averageRansacInlierRatio)/diag.ransacSamples;diag.averageCoverage+=(r.coverage-diag.averageCoverage)/diag.ransacSamples}return r});const r=await Promise.race([resultPromise,sleep(WORKER_WAIT_MS).then(()=>null)]);if(!r)return{dx:0,dy:0,roll:0,logScale:0,confidence:0,tracks:0,source:'worker-pending'};return r})();workerPairCache.set(i,p);return p}
  function routeMotion(i,out,wp,weight){const ransacWeight=clamp(Number.isFinite(weight)?weight:0,0,1),farFieldWeight=1-ransacWeight,applied={frame:i,workerSource:wp?.source||'unknown',appliedSource:out?.source||'unknown',ransacWeight,farFieldWeight,workerConfidence:Number.isFinite(wp?.confidence)?wp.confidence:0,safetyFactor:Number.isFinite(wp?.safetyFactor)?wp.safetyFactor:1,safetyFlags:wp?.safetyFlags||'',appliedDx:Number.isFinite(out?.dx)?out.dx:0,appliedDy:Number.isFinite(out?.dy)?out.dy:0,appliedRoll:Number.isFinite(out?.roll)?out.roll:0,appliedLogScale:Number.isFinite(out?.logScale)?out.logScale:0,appliedConfidence:Number.isFinite(out?.confidence)?out.confidence:0};diag.lastMotionRoute=applied;try{window.dispatchEvent(new CustomEvent('journey-applied-motion',{detail:{...applied}}))}catch{}return out}
  async function motionPair(i){if(motionPairCache.has(i))return motionPairCache.get(i);const p=(async()=>{const[wp,far]=await Promise.all([workerFeaturePair(i),farPair(i)]),sf=Number.isFinite(wp.safetyFactor)?clamp(wp.safetyFactor,0,1):1,guarded=sf<.95,strongGate=guarded?SAFETY_GUARD_STRONG:CAMERA_RANSAC_STRONG;if(wp.confidence>=strongGate)return routeMotion(i,wp,wp,1);if(wp.confidence>=CAMERA_RANSAC_BLEND&&wp.tracks>=CAMERA_MIN_TRACKS){const dis=Math.hypot(wp.dx-far.dx,wp.dy-far.dy);let w=clamp(.38+(wp.confidence-CAMERA_RANSAC_BLEND)/Math.max(.001,CAMERA_RANSAC_STRONG-CAMERA_RANSAC_BLEND)*.48,.38,.86);if(guarded)w*=clamp(sf,.30,.82);if(dis>4.5&&wp.confidence<.50)w*=.75;const out={dx:clamp(wp.dx*w+far.dx*(1-w),-CAMERA_MAX_STEP_X,CAMERA_MAX_STEP_X),dy:clamp(wp.dy*w+far.dy*(1-w),-CAMERA_MAX_STEP_Y,CAMERA_MAX_STEP_Y),roll:wp.roll*w,logScale:wp.logScale*w,confidence:clamp(Math.max(wp.confidence*.92,far.confidence*.60),0,1),tracks:wp.tracks,source:'blend',inlierRatio:wp.inlierRatio||0,coverage:wp.coverage||0,safetyFactor:sf,safetyFlags:wp.safetyFlags||''};return routeMotion(i,out,wp,w)}const out={dx:clamp(far.dx,-CAMERA_MAX_STEP_X,CAMERA_MAX_STEP_X),dy:clamp(far.dy,-CAMERA_MAX_STEP_Y,CAMERA_MAX_STEP_Y),roll:0,logScale:0,confidence:clamp(far.confidence*.58,0,.35),tracks:wp.tracks||0,source:'far',inlierRatio:wp.inlierRatio||0,coverage:wp.coverage||0,safetyFactor:sf,safetyFlags:wp.safetyFlags||''};return routeMotion(i,out,wp,0)})();motionPairCache.set(i,p);return p}
  function rawTrajectory(i){if(rawTrajectoryCache.has(i))return rawTrajectoryCache.get(i);const p=(async()=>{if(i<=0)return{x:0,y:0,roll:0,logScale:0,confidence:1};const[prev,pair]=await Promise.all([rawTrajectory(i-1),motionPair(i-1)]);return{x:prev.x+pair.dx,y:prev.y+pair.dy,roll:prev.roll+pair.roll,logScale:prev.logScale+pair.logScale,confidence:pair.confidence}})();rawTrajectoryCache.set(i,p);return p}
  function cameraPose(i){if(cameraPoseCache.has(i))return cameraPoseCache.get(i);const p=(async()=>{const start=Math.max(0,i-CAMERA_WINDOW_RADIUS),end=Math.min(route.length-1,i+CAMERA_WINDOW_RADIUS),inds=[];for(let k=start;k<=end;k++)inds.push(k);const list=await Promise.all(inds.map(rawTrajectory)),raw=await rawTrajectory(i);let sx=0,sy=0,sr=0,ss=0,sw=0;for(let n=0;n<list.length;n++){const d=Math.abs(inds[n]-i),w=d===0?6:d===1?4:d===2?2:1;sx+=list[n].x*w;sy+=list[n].y*w;sr+=list[n].roll*w;ss+=list[n].logScale*w;sw+=w}const sm={x:sx/sw,y:sy/sw,roll:sr/sw,logScale:ss/sw},prom=[];for(let k=Math.max(0,i-3);k<Math.min(route.length-1,i+3);k++)prom.push(motionPair(k));const pairs=await Promise.all(prom),conf=pairs.length?pairs.reduce((s,p)=>s+p.confidence,0)/pairs.length:0,rs=pairs.filter(p=>p.source==='ransac'||p.source==='blend').length,share=pairs.length?rs/pairs.length:0,pose={x:clamp(sm.x-raw.x,-CAMERA_MAX_CORR_X,CAMERA_MAX_CORR_X),y:clamp(sm.y-raw.y,-CAMERA_MAX_CORR_Y,CAMERA_MAX_CORR_Y),roll:clamp(sm.roll-raw.roll,-CAMERA_MAX_CORR_ROLL,CAMERA_MAX_CORR_ROLL),scale:clamp(Math.exp(sm.logScale-raw.logScale),CAMERA_MIN_SCALE,CAMERA_MAX_SCALE),confidence:conf,ransacShare:share,source:workerReady&&share>=.50?'ransac':'mixed'};diag.lastPose={...pose,frame:i};diag.cameraSamples++;diag.averageConfidence+=(conf-diag.averageConfidence)/diag.cameraSamples;return pose})();cameraPoseCache.set(i,p);return p}
  async function stabilizedGray(i){if(stabilizedGrayCache.has(i))return stabilizedGrayCache.get(i);const p=(async()=>{const im=await loadCors(route[i]?.url);if(!im)return null;const[roll,pose]=await Promise.all([smoothRoll(i),cameraPose(i)]),c=document.createElement('canvas');c.width=ANALYSIS_W;c.height=ANALYSIS_H;const g=c.getContext('2d',{willReadFrequently:true});g.fillStyle='#111';g.fillRect(0,0,ANALYSIS_W,ANALYSIS_H);drawBase(g,im,i,roll,pose,1,'analysis');try{const d=g.getImageData(0,0,ANALYSIS_W,ANALYSIS_H).data,o=new Float32Array(ANALYSIS_W*ANALYSIS_H);for(let k=0,j=0;k<o.length;k++,j+=4)o[k]=d[j]*.299+d[j+1]*.587+d[j+2]*.114;return o}catch{return null}})();stabilizedGrayCache.set(i,p);return p}
  function blockScore(a,b,x0,y0,x1,y1,dx,dy){let s=0,c=0;for(let y=y0+3;y<y1-3;y+=2){const by=y+dy;if(by<1||by>=ANALYSIS_H-1)continue;for(let x=x0+3;x<x1-3;x+=2){const bx=x+dx;if(bx<1||bx>=ANALYSIS_W-1)continue;s+=Math.abs(a[y*ANALYSIS_W+x]-b[by*ANALYSIS_W+bx]);c++}}return c?s/c:1e9}
  function tileDepth(col,row){const nx=Math.abs((col+.5)/TILE_COLS-.5)*2,ny=(row+.5)/TILE_ROWS;return clamp(.50+.55*ny+.22*nx,.55,1.28)}
  function smoothVectorField(vectors){let field=vectors.map(v=>({...v}));for(let pass=0;pass<VECTOR_PASSES;pass++){const prev=field;field=prev.map(v=>{let sx=v.vx*2.7,sy=v.vy*2.7,sw=2.7;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const c=v.col+dx,r=v.row+dy;if(c<0||c>=TILE_COLS||r<0||r>=TILE_ROWS)continue;const n=prev[r*TILE_COLS+c],w=dx&&dy?.52:.94;sx+=n.vx*w;sy+=n.vy*w;sw+=w}return{...v,vx:clamp(v.vx*(1-VECTOR_SMOOTH)+sx/sw*VECTOR_SMOOTH,-4.8,4.8),vy:clamp(v.vy*(1-VECTOR_SMOOTH)+sy/sw*VECTOR_SMOOTH,-3.6,3.6)}})}for(let p=0;p<2;p++){const next=field.map(v=>({...v}));for(const v of field){const ns=[];if(v.col>0)ns.push(field[v.row*TILE_COLS+v.col-1]);if(v.col<TILE_COLS-1)ns.push(field[v.row*TILE_COLS+v.col+1]);if(v.row>0)ns.push(field[(v.row-1)*TILE_COLS+v.col]);if(v.row<TILE_ROWS-1)ns.push(field[(v.row+1)*TILE_COLS+v.col]);if(!ns.length)continue;const ax=ns.reduce((s,n)=>s+n.vx,0)/ns.length,ay=ns.reduce((s,n)=>s+n.vy,0)/ns.length,it=next[v.row*TILE_COLS+v.col];it.vx=clamp(it.vx,ax-MAX_NEIGHBOR_DX,ax+MAX_NEIGHBOR_DX);it.vy=clamp(it.vy,ay-MAX_NEIGHBOR_DY,ay+MAX_NEIGHBOR_DY)}field=next}return field}
  async function tileVectors(i){if(tileCache.has(i))return tileCache.get(i);const p=(async()=>{const geo=geoAlignment(i),gx=geo.x/Math.max(320,window.innerWidth||390)*ANALYSIS_W,gy=geo.y/Math.max(600,window.innerHeight||844)*ANALYSIS_H,[a,b]=await Promise.all([stabilizedGray(i),stabilizedGray(i+1)]),vs=[];for(let row=0;row<TILE_ROWS;row++)for(let col=0;col<TILE_COLS;col++){const depth=tileDepth(col,row);let vx=gx*depth,vy=gy*depth,confidence=0;if(a&&b){const x0=Math.floor(col*ANALYSIS_W/TILE_COLS),x1=Math.floor((col+1)*ANALYSIS_W/TILE_COLS),y0=Math.floor(row*ANALYSIS_H/TILE_ROWS),y1=Math.floor((row+1)*ANALYSIS_H/TILE_ROWS),base=blockScore(a,b,x0,y0,x1,y1,0,0);let best={dx:0,dy:0,score:base};for(let dy=-3;dy<=3;dy++)for(let dx=-3;dx<=3;dx++){const sc=blockScore(a,b,x0,y0,x1,y1,dx,dy);if(sc<best.score)best={dx,dy,score:sc}}confidence=clamp((base-best.score)/Math.max(base,1),0,1);if(confidence>=.018){vx=(best.dx*.78+gx*.22)*depth;vy=(best.dy*.78+gy*.22)*depth}}vs.push({col,row,vx:clamp(vx,-4.8,4.8),vy:clamp(vy,-3.6,3.6),confidence,depth})}return smoothVectorField(vs)})();tileCache.set(i,p);return p}

  function createStabilizedFrame(i){if(stabilizedFrameCache.has(i)){diag.frameCacheHits++;return stabilizedFrameCache.get(i)}const p=(async()=>{const im=await loadRender(route[i]?.url);const{w,h}=canvasSize(),[roll,pose]=await Promise.all([smoothRoll(i),cameraPose(i)]),c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d',{alpha:false});g.fillStyle='#05070a';g.fillRect(0,0,w,h);drawBase(g,im,i,roll,pose,1,'render');return{canvas:c,roll:roll+pose.roll,pose,image:im,index:i}})();stabilizedFrameCache.set(i,p);return p}
  function blendAsset(col,row){const w=colorCanvas.width,h=colorCanvas.height,ov=Math.max(3,Math.round(TILE_OVERLAP_CSS_PX*canvasDpr*NORMALIZE_SCALE)),x0=Math.floor(col*w/TILE_COLS),y0=Math.floor(row*h/TILE_ROWS),x1=Math.ceil((col+1)*w/TILE_COLS),y1=Math.ceil((row+1)*h/TILE_ROWS),l=col>0?ov:0,r=col<TILE_COLS-1?ov:0,t=row>0?ov:0,b=row<TILE_ROWS-1?ov:0,sx=Math.max(0,x0-l),sy=Math.max(0,y0-t),ex=Math.min(w,x1+r),ey=Math.min(h,y1+b),sw=ex-sx,sh=ey-sy,key=`${canvasSignature}:${col}:${row}:${ov}:${sw}x${sh}`;if(blendAssetCache.has(key))return blendAssetCache.get(key);const mask=document.createElement('canvas');mask.width=sw;mask.height=sh;const g=mask.getContext('2d',{alpha:true}),im=g.createImageData(sw,sh),d=im.data,fw=Math.max(1,ov*2),fh=Math.max(1,ov*2);for(let y=0;y<sh;y++){let wy=1;if(row>0&&y<fh)wy*=cosineRamp(y/fh);if(row<TILE_ROWS-1&&y>=sh-fh)wy*=cosineRamp((sh-1-y)/fh);for(let x=0;x<sw;x++){let wx=1;if(col>0&&x<fw)wx*=cosineRamp(x/fw);if(col<TILE_COLS-1&&x>=sw-fw)wx*=cosineRamp((sw-1-x)/fw);const a=Math.round(clamp(wx*wy,0,1)*255),k=(y*sw+x)*4;d[k]=d[k+1]=d[k+2]=255;d[k+3]=a}}g.putImageData(im,0,0);const asset={sx,sy,sw,sh,mask};blendAssetCache.set(key,asset);return asset}
  function prepareTileLayers(frame,i){if(tileLayerCache.has(i)){diag.tileCacheHits++;return tileLayerCache.get(i)}const layers=[],sx=frame.width/colorCanvas.width,sy=frame.height/colorCanvas.height;for(let row=0;row<TILE_ROWS;row++)for(let col=0;col<TILE_COLS;col++){const a=blendAsset(col,row),c=document.createElement('canvas');c.width=a.sw;c.height=a.sh;const g=c.getContext('2d',{alpha:true});g.drawImage(frame,a.sx*sx,a.sy*sy,a.sw*sx,a.sh*sy,0,0,a.sw,a.sh);g.globalCompositeOperation='destination-in';g.drawImage(a.mask,0,0);g.globalCompositeOperation='source-over';layers.push({asset:a,color:c})}tileLayerCache.set(i,layers);return layers}
  function preparePair(i){if(preparedPairCache.has(i)){diag.pairCacheHits++;return preparedPairCache.get(i)}const p=(async()=>{if(!route[i]||!route[i+1])throw new Error('Pair画像が不足しています');const[a,b,vs]=await Promise.all([createStabilizedFrame(i),createStabilizedFrame(i+1),tileVectors(i)]);return{i,a,b,vs,la:prepareTileLayers(a.canvas,i),lb:prepareTileLayers(b.canvas,i+1),bs:perceptualBridgeStrength(i)}})();preparedPairCache.set(i,p);p.catch(()=>preparedPairCache.delete(i));return p}
  function clearAccumulator(g,w,h){g.globalCompositeOperation='source-over';g.globalAlpha=1;g.fillStyle='#000';g.fillRect(0,0,w,h);g.globalCompositeOperation='lighter'}
  function accumulateLayer(layer,v,p,incoming,ta,bs){const sx=colorCanvas.width/ANALYSIS_W,sy=colorCanvas.height/ANALYSIS_H,f=incoming?-(1-p):p,cx=layer.asset.sx+layer.asset.sw*.5,cy=layer.asset.sy+layer.asset.sh*.5,vx=colorCanvas.width*.5,vy=colorCanvas.height*.46,rp=incoming?-(1-p):p,rg=BRIDGE_RADIAL_GAIN*bs*rp,dx=layer.asset.sx+v.vx*sx*f+(cx-vx)*rg,dy=layer.asset.sy+v.vy*sy*f+(cy-vy)*rg,a=ta*ACCUM_SCALE;colorCtx.globalAlpha=a;colorCtx.drawImage(layer.color,dx,dy);weightCtx.globalAlpha=a;weightCtx.drawImage(layer.asset.mask,dx,dy)}
  function drawFallback(a,b,p){const w=fallbackCanvas.width,h=fallbackCanvas.height;fallbackCtx.globalCompositeOperation='source-over';fallbackCtx.globalAlpha=1;fallbackCtx.drawImage(a,0,0,w,h);fallbackCtx.globalAlpha=p;fallbackCtx.drawImage(b,0,0,w,h);fallbackCtx.globalAlpha=1}
  function normalizeAccumulation(a,b,la,lb,vs,p,bs){const w=colorCanvas.width,h=colorCanvas.height;clearAccumulator(colorCtx,w,h);clearAccumulator(weightCtx,w,h);for(let n=0;n<vs.length;n++)accumulateLayer(la[n],vs[n],p,false,1-p,bs);for(let n=0;n<vs.length;n++)accumulateLayer(lb[n],vs[n],p,true,p,bs);colorCtx.globalCompositeOperation='source-over';weightCtx.globalCompositeOperation='source-over';colorCtx.globalAlpha=weightCtx.globalAlpha=1;drawFallback(a,b,p);const c=colorCtx.getImageData(0,0,w,h).data,wt=weightCtx.getImageData(0,0,w,h).data,fb=fallbackCtx.getImageData(0,0,w,h).data,o=outputImage.data;for(let k=0;k<o.length;k+=4){const wb=wt[k];if(wb>MIN_WEIGHT_BYTE){const sc=255/wb;o[k]=clamp(Math.round(c[k]*sc),0,255);o[k+1]=clamp(Math.round(c[k+1]*sc),0,255);o[k+2]=clamp(Math.round(c[k+2]*sc),0,255)}else{o[k]=fb[k];o[k+1]=fb[k+1];o[k+2]=fb[k+2]}o[k+3]=255}colorCtx.globalCompositeOperation='copy';colorCtx.putImageData(outputImage,0,0);colorCtx.globalCompositeOperation='source-over';ctx.imageSmoothingEnabled=true;ctx.drawImage(colorCanvas,0,0,w,h,0,0,ui.canvas.width,ui.canvas.height)}

  function streamState(){return window.__journeyStreamState||null}
  function syncStreamFrames(){const s=streamState();if(!s||!Array.isArray(s.frames))return 0;const seen=new Set(route.map(f=>String(f?.id||f?.url||'')));let added=0;for(const f of s.frames){const k=String(f?.id||f?.url||'');if(!k||seen.has(k))continue;seen.add(k);route.push(f);added++}return added}
  function trimJourneyCaches(i){const cut=Math.max(0,i-CACHE_BEHIND);for(let k=0;k<cut;k++){const u=route[k]?.url;if(u){renderCache.delete(u);corsCache.delete(u)}grayCache.delete(k);rollRawCache.delete(k);rollSmoothCache.delete(k);correctedGrayCache.delete(k);farPairCache.delete(k);workerPairCache.delete(k);motionPairCache.delete(k);stabilizedGrayCache.delete(k);tileCache.delete(k);anchorCache.delete(k);stabilizedFrameCache.delete(k);tileLayerCache.delete(k);preparedPairCache.delete(k)}for(let k=0;k<Math.max(0,cut-2);k++){cameraPoseCache.delete(k);rawTrajectoryCache.delete(k)}}
  function warmAhead(i){syncStreamFrames();const rawEnd=Math.min(route.length,i+RAW_PRELOAD_AHEAD+1);for(let k=i+1;k<rawEnd;k++)loadRender(route[k].url).catch(()=>{});idle(()=>{const heavyEnd=Math.min(route.length,i+HEAVY_PRELOAD_AHEAD+1);for(let k=i;k<heavyEnd;k++)smoothRoll(k).catch(()=>{});for(let k=i;k<Math.min(route.length-1,i+HEAVY_PRELOAD_AHEAD);k++)workerFeaturePair(k).catch(()=>{});for(let k=i;k<Math.min(route.length,i+2);k++)cameraPose(k).catch(()=>{});for(let k=i;k<Math.min(route.length-1,i+PAIR_PRELOAD_AHEAD);k++)preparePair(k).catch(()=>{})})}
  function updateHud(i,roll=0,pose=null){const f=route[i],s=streamState(),total=Math.max(route.length,s?.total||0);window.__journeyPlaybackState={index:i,available:route.length,total,streaming:!!s?.active};ui.num.textContent=`${i+1} / ${total||route.length}`;ui.bar.style.width=`${total?((i+1)/total*100):0}%`;const d=travelBearing(i);ui.heading.textContent=Number.isFinite(d)?`${Math.round(d)}°`:'—°';ui.coord.textContent=hasCoords(f)?`${f.lat.toFixed(5)}, ${f.lng.toFixed(5)}`:'—';const conf=pose&&Number.isFinite(pose.confidence)?Math.round(pose.confidence*100):0,avg=Math.round((diag.averageConfidence||0)*100),src=pose?.source==='ransac'?'RS':'Mix';ui.net.textContent=s?.active?`再生中・続きを準備 ${route.length}/${total}`:`${(speedMs/1000).toFixed(2)}秒・${src} ${conf}%・Avg ${avg}%・水平 ${roll>=0?'+':''}${roll.toFixed(1)}°`}
  async function showFirst(){syncStreamFrames();const firstFrame=route[0];if(!firstFrame?.url)throw new Error('先頭画像URLがありません');ui.a.src=firstFrame.url;ui.a.style.opacity='1';ui.b.style.opacity='0';ui.canvas.style.opacity='0';const im=await loadRender(firstFrame.url);currentImage=im;updateHud(0,0,{x:0,y:0,roll:0,scale:1,confidence:0,source:'mixed'});try{window.dispatchEvent(new CustomEvent('journey-playback-started',{detail:{index:0,available:route.length,total:Math.max(route.length,streamState()?.total||0)}}))}catch{}return im}
  async function animatePair(i){const ps=performance.now(),prepared=await preparePair(i),{a,b,vs,la,lb,bs}=prepared,fast=speedMs===80,duration=fast?80:Math.max(88,Math.round(speedMs*.92)),minMs=1000/(fast?FAST_80_FPS:NORMALIZE_FPS),start=performance.now();ui.canvas.style.opacity='1';ui.a.style.opacity=ui.b.style.opacity='0';ui.edgeBlur?.classList.add('drive-stabilized');let last=-Infinity;await new Promise(resolve=>{function tick(now){const t=clamp((now-start)/duration,0,1);if(t>=1||now-last>=minMs){setBridge(t,bs);try{normalizeAccumulation(a.canvas,b.canvas,la,lb,vs,t,bs)}catch{ctx.globalAlpha=1;ctx.drawImage(a.canvas,0,0);ctx.globalAlpha=t;ctx.drawImage(b.canvas,0,0);ctx.globalAlpha=1}last=now}if(t<1)requestAnimationFrame(tick);else resolve()}requestAnimationFrame(tick)});resetBridge();ctx.globalAlpha=1;ctx.drawImage(b.canvas,0,0);currentImage=b.image;const elapsed=performance.now()-ps;diag.lastPairMs=elapsed;diag.pairSamples++;diag.averagePairMs+=(elapsed-diag.averagePairMs)/diag.pairSamples;updateHud(i+1,b.roll,b.pose)}

  function clearJourneyCaches(){[renderCache,corsCache,grayCache,rollRawCache,rollSmoothCache,correctedGrayCache,farPairCache,workerPairCache,motionPairCache,rawTrajectoryCache,cameraPoseCache,stabilizedGrayCache,tileCache,blendAssetCache,anchorCache,stabilizedFrameCache,tileLayerCache,preparedPairCache].forEach(c=>c.clear());Object.assign(diag,{lastWorkerPair:null,lastMotionRoute:null,lastPose:null,cameraSamples:0,averageConfidence:0,pairSamples:0,averagePairMs:0,ransacSamples:0,averageRansacInlierRatio:0,averageCoverage:0,frameCacheHits:0,tileCacheHits:0,pairCacheHits:0})}
  async function waitForStreamFrame(i,playToken){while(playToken===token){syncStreamFrames();if(i+1<route.length)return true;const s=streamState();if(!s||(!s.active&&s.complete))return false;ui.net.textContent=`バッファ待機 ${route.length}/${Math.max(route.length,s.total||0)}`;await sleep(STREAM_WAIT_MS)}return false}
  async function play(frames){const playToken=++token;route=Array.isArray(frames)?frames.slice():[];syncStreamFrames();clearJourneyCaches();if(!route.length)throw new Error('再生できる画像がありません');ui.place.textContent=route[0].sequenceId?`Sequence #${route[0].sequenceId}`:'KartaView route';await showFirst();warmAhead(0);preparePair(0).catch(()=>{});await sleep(20);let nextAt=performance.now()+speedMs,i=0;while(playToken===token){syncStreamFrames();if(i>=route.length-1){const hasNext=await waitForStreamFrame(i,playToken);if(!hasNext)break;nextAt=performance.now()+speedMs}warmAhead(i+1);const rem=nextAt-performance.now();if(rem>0)await sleep(rem);if(playToken!==token)return;try{await animatePair(i);i++;trimJourneyCaches(i)}catch(e){if(i+1<route.length){route.splice(i+1,1);clearJourneyCaches();syncStreamFrames();continue}const s=streamState();if(s?.active){await sleep(STREAM_WAIT_MS);continue}throw e}nextAt+=speedMs;if(nextAt<performance.now())nextAt=performance.now()+Math.max(8,speedMs*.10)}if(playToken===token){const s=streamState();if(s){ui.net.textContent='Journey完了';window.__journeyPlaybackState={index:i,available:route.length,total:Math.max(route.length,s.total||0),streaming:false,complete:true}}else{ui.net.textContent=`${(speedMs/1000).toFixed(2)}秒・再スタート`;await sleep(500);if(playToken===token)play(frames)}}}
  async function fetchRoute(){const p=new URLSearchParams({source:'karta'});if(ui.coords.checked){const lat=Number(ui.lat.value),lng=Number(ui.lng.value);if(!Number.isFinite(lat)||!Number.isFinite(lng))throw new Error('緯度・経度を確認してください');p.set('lat',String(lat));p.set('lng',String(lng));p.set('radius','1200')}else{p.set('sequence','6187609');p.set('index','650')}const r=await fetch(`/api/imagery?${p}`,{cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`API error ${r.status}`);if(!Array.isArray(d.frames)||d.frames.length<2)throw new Error('連続して再生できる写真が見つかりませんでした');return d}
  async function requestWakeLock(){if(!('wakeLock'in navigator))return;try{wake=await navigator.wakeLock.request('screen')}catch{}}
  function showStartError(e){ui.edgeBlur?.classList.remove('drive-stabilized');resetBridge();ui.canvas.style.opacity='0';ui.back.hidden=true;ui.err.textContent=e?.message||'不明なエラーが発生しました';ui.error.hidden=false;ui.start.hidden=true;ui.startBtn.disabled=false;ui.startBtn.textContent='旅をはじめる'}
  async function start(){if(directStarting)return;ui.startBtn.disabled=true;ui.startBtn.textContent='旅を準備中…';ui.error.hidden=true;speedMs=Number(document.querySelector('input[name="driveSpeed"]:checked')?.value||80);try{const wakeP=requestWakeLock(),d=await fetchRoute();ui.start.hidden=true;ui.back.hidden=false;ui.startBtn.disabled=false;ui.startBtn.textContent='旅をはじめる';wakeP.catch(()=>{});await play(d.frames)}catch(e){showStartError(e)}}
  async function startFrames(initialFrames,streamStateArg=null){if(directStarting)return;directStarting=true;ui.error.hidden=true;speedMs=Number(document.querySelector('input[name="driveSpeed"]:checked')?.value||80);try{if(!Array.isArray(initialFrames)||initialFrames.length<2)throw new Error('地図側の初期バッファが不足しています');if(streamStateArg)window.__journeyStreamState=streamStateArg;ui.start.hidden=true;ui.back.hidden=false;ui.startBtn.disabled=false;const wakeP=requestWakeLock();wakeP.catch(()=>{});await play(initialFrames)}catch(e){showStartError(e);throw e}finally{directStarting=false}}
  async function reset(){token++;ui.edgeBlur?.classList.remove('drive-stabilized');resetBridge();ui.canvas.style.opacity='0';ui.a.style.opacity=ui.b.style.opacity='0';ui.back.hidden=true;ui.error.hidden=true;ui.start.hidden=false;currentImage=null;try{await wake?.release?.()}catch{}wake=null}
  window.JourneyEngine={startFrames,reset,getState:()=>({...window.__journeyPlaybackState,routeLength:route.length,version:VERSION,frameCache:stabilizedFrameCache.size,tileLayerCache:tileLayerCache.size,pairCache:preparedPairCache.size})};
  try{window.dispatchEvent(new CustomEvent('journey-engine-ready',{detail:{version:VERSION}}))}catch{}
  ui.startBtn.addEventListener('click',start);ui.retry.addEventListener('click',reset);ui.back.addEventListener('click',reset);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&(!wake||wake.released)&&ui.start.hidden)requestWakeLock()});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js?v=0.1.32').catch(()=>{}));console.info(`Streetview Journey v${VERSION}`);
})();