/* Streetview Journey Quality / Progressive Loading / Optical Bridge v0.3.0 */
(()=>{
  'use strict';
  if(window.__journeyHybridQualityInstalled)return;
  window.__journeyHybridQualityInstalled=true;

  const VERSION='0.3.0-a-c-d';
  const GRAPH='https://graph.mapillary.com';
  const TOKEN_KEY='streetview:mapillary-token';
  const ROUTE_KEY='streetview:journey-route';

  /* Phase A: configurable quality model. */
  const QUALITY_WEIGHTS=Object.freeze({image:.40,direction:.20,spacing:.15,roll:.15,resolution:.10});
  const QUALITY_THRESHOLDS=Object.freeze({preferred:.70,normal:.55,conditional:.40,maxRejectRatio:.18,minJourneyScore:42});
  const MAX_BRIDGE_METERS=24,MAX_BRIDGE_HEADING_DEG=58,MAX_BRIDGE_TIME_MS=12000,QUALITY_BATCH=35;
  const QUALITY_FIELDS_FULL='id,sequence,captured_at,computed_geometry,compass_angle,computed_compass_angle,thumb_256_url,thumb_1024_url,thumb_2048_url,is_pano,width,height,on_foot,quality_score';
  const QUALITY_FIELDS_NO_SCORE='id,sequence,captured_at,computed_geometry,compass_angle,computed_compass_angle,thumb_256_url,thumb_1024_url,thumb_2048_url,is_pano,width,height,on_foot';
  const QUALITY_FIELDS_CORE='id,sequence,captured_at,computed_geometry,compass_angle,thumb_256_url,thumb_1024_url,thumb_2048_url,is_pano';

  /* Phase C: progressive quality lane. Base continuity stays owned by raw-runtime/app.js. */
  const NETWORK_FAST_MS=350,NETWORK_SLOW_MS=900,LOAD_EWMA_ALPHA=.24;
  const MIN_RAW_AHEAD=5,FAR_URL_AHEAD=48;
  const MAX_2048_CACHE=4,MAX_1024_CACHE=18;
  const TIER_LONG_EDGE={1024:900,2048:1750};
  const MAX_LOADS={FAST:3,NORMAL:2,SLOW:1};
  const QUALITY_PLAN={
    FAST:{high2048:4,near1024:12,far1024:18},
    NORMAL:{high2048:2,near1024:10,far1024:14},
    SLOW:{high2048:0,near1024:7,far1024:9}
  };

  /* Phase D: existing app.js 4x5 preparedPair is rendered only when already ready. */
  const INTERMEDIATE_T=.5,WARP_MIN_RAW_AHEAD=4,WARP_MAX_DISTANCE_M=18,WARP_MAX_TURN_DEG=38;
  const WARP_MIN_GOOD_TILES=8,WARP_MIN_TILE_CONF=.018,WARP_MIN_AVG_CONF=.025,WARP_MAX_RENDER_MS=14;
  const TEST_SPEEDS=Object.freeze([80,100,120,150]);

  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const median=a=>{const s=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!s.length)return null;const m=s.length>>1;return s.length&1?s[m]:(s[m-1]+s[m])*.5};
  const average=a=>{const s=a.filter(Number.isFinite);return s.length?s.reduce((x,y)=>x+y,0)/s.length:null};
  const rad=v=>v*Math.PI/180,deg=v=>v*180/Math.PI;
  const angle=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)?((b-a+540)%360)-180:null;
  const emit=(phase,detail={})=>{try{window.dispatchEvent(new CustomEvent('journey-hybrid-quality',{detail:{phase,version:VERSION,...detail}}))}catch{}};
  const token=()=>{try{return localStorage.getItem(TOKEN_KEY)||''}catch{return''}};
  const runtime=()=>window.__journeyRawRuntime||{};
  const playback=()=>window.__journeyPlaybackState||{};
  const engine=()=>window.JourneyEngine?.getState?.()||{};
  const bridge=()=>window.__journeyOpticalBridge||null;
  const frames=()=>window.__journeyStreamState?.frames||window.__journeySelectedRoute?.frames||[];
  const currentIndex=()=>{const p=playback(),e=engine();return Number.isFinite(p.index)?p.index:(Number.isFinite(e.index)?e.index:0)};
  const rawAhead=()=>{const r=runtime(),p=playback(),e=engine();const v=Number.isFinite(r.contiguousRawAhead)?r.contiguousRawAhead:(p.rawAheadReady??e.actualRenderableAhead??e.rawAheadReady??0);return Math.max(0,Number(v)||0)};
  const remainingAhead=()=>Math.max(0,frames().length-currentIndex()-1);
  const requiredRawAhead=()=>Math.min(MIN_RAW_AHEAD,remainingAhead());
  const hasCoords=f=>Number.isFinite(Number(f?.lat))&&Number.isFinite(Number(f?.lng));
  function distanceMeters(a,b){if(!hasCoords(a)||!hasCoords(b))return null;const p1=rad(Number(a.lat)),p2=rad(Number(b.lat)),dp=p2-p1,dl=rad(Number(b.lng)-Number(a.lng)),s=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 12742000*Math.atan2(Math.sqrt(s),Math.sqrt(Math.max(0,1-s)))}
  function bearing(a,b){if(!hasCoords(a)||!hasCoords(b))return null;const p1=rad(Number(a.lat)),p2=rad(Number(b.lat)),dl=rad(Number(b.lng)-Number(a.lng)),y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(deg(Math.atan2(y,x))+360)%360}
  function capturedMs(f){const v=f?.capturedAt??f?.captured_at;if(v==null)return null;if(Number.isFinite(Number(v))){const n=Number(v);return n<1e12?n*1000:n}const n=Date.parse(String(v));return Number.isFinite(n)?n:null}
  function frameHeading(f){const a=Number(f?.computedHeading??f?.computed_compass_angle),b=Number(f?.heading??f?.compass_angle);return Number.isFinite(a)?a:(Number.isFinite(b)?b:null)}
  function metaCoords(m){const c=m?.computed_geometry?.coordinates;return Array.isArray(c)&&c.length>=2?{lat:Number(c[1]),lng:Number(c[0])}:null}
  function isSphere(f){return String(f?.projection||'').toUpperCase()==='SPHERE'||f?.is_pano===true||Number(f?.fieldOfView)>=180}
  function mapillaryScore(f){const q=Number(f?.mapillaryQualityScore??f?.quality_score);return Number.isFinite(q)&&q>0&&q<=1?q:null}
  function longEdge(f){const w=Number(f?.width),h=Number(f?.height);if(Number.isFinite(w)&&Number.isFinite(h)&&w>0&&h>0)return Math.max(w,h);if(f?.raw2048Url||f?.thumb_2048_url||f?.sourceUrl)return 2048;if(f?.raw1024Url||f?.thumb_1024_url)return 1024;if(f?.raw256Url||f?.thumb_256_url)return 256;return 0}
  function aspectScore(f){const w=Number(f?.width),h=Number(f?.height);if(!Number.isFinite(w)||!Number.isFinite(h)||w<=0||h<=0)return 85;const r=w/h;if(r>4.5||r<.22)return 18;if(r>3.1||r<.32)return 48;if(r>2.5||r<.40)return 72;return 100}
  function resolutionScore(f){const l=longEdge(f);if(l>=1900)return 100;if(l>=1000)return 82;if(l>=700)return 64;if(l>=500)return 48;if(l>=250)return 30;return 15}
  function travelBearingFor(list,i){const c=list[i];if(!c)return null;let x=0,y=0,w=0;for(let s=1;s<=8&&i+s<list.length;s++){const n=list[i+s];if(String(c.sequenceId||'')&&String(n.sequenceId||'')&&String(c.sequenceId)!==String(n.sequenceId))break;const d=distanceMeters(c,n);if(!Number.isFinite(d)||d<.7)continue;const br=bearing(c,n),ww=Math.min(d,20)/Math.pow(s,.55);x+=Math.cos(rad(br))*ww;y+=Math.sin(rad(br))*ww;w+=ww;if(d>=25)break}if(!w&&i>0){const p=list[i-1];if(!String(c.sequenceId||'')||!String(p.sequenceId||'')||String(c.sequenceId)===String(p.sequenceId)){const br=bearing(p,c),d=distanceMeters(p,c);if(Number.isFinite(br)&&Number.isFinite(d)&&d>.7)return br}}return w?(deg(Math.atan2(y,x))+360)%360:frameHeading(c)}
  function localSpacing(list,i){const ds=[];if(i>0){const d=distanceMeters(list[i-1],list[i]);if(Number.isFinite(d))ds.push(d)}if(i+1<list.length){const d=distanceMeters(list[i],list[i+1]);if(Number.isFinite(d))ds.push(d)}return average(ds)}
  function scoreFrame(list,i,medianSpacing){const f=list[i],mq=mapillaryScore(f),res=resolutionScore(f),aspect=aspectScore(f),imageBase=mq!=null?mq*100:clamp(res*.58+aspect*.27+80*.15,0,100);const tr=travelBearingFor(list,i),hd=frameHeading(f),diff=Number.isFinite(tr)&&Number.isFinite(hd)?Math.abs(angle(hd,tr)):null,direction=diff==null?72:clamp(100-diff/95*100,0,100);const spacing=localSpacing(list,i),spacingScore=Number.isFinite(spacing)&&Number.isFinite(medianSpacing)&&medianSpacing>.2?clamp(100-Math.abs(spacing-medianSpacing)/Math.max(medianSpacing,1)*55,15,100):72;const rollValue=Math.abs(Number(f?.rollDeg??f?.roll??0)),rollKnown=Number.isFinite(Number(f?.rollDeg??f?.roll)),rollScore=rollKnown?clamp(100-rollValue/5*100,0,100):72;const score=clamp(imageBase*QUALITY_WEIGHTS.image+direction*QUALITY_WEIGHTS.direction+spacingScore*QUALITY_WEIGHTS.spacing+rollScore*QUALITY_WEIGHTS.roll+res*QUALITY_WEIGHTS.resolution,0,100);return{journeyQualityScore:Math.round(score*10)/10,mapillaryQualityScore:mq,imageScore:Math.round(imageBase*10)/10,directionScore:Math.round(direction*10)/10,spacingScore:Math.round(spacingScore*10)/10,rollScore:Math.round(rollScore*10)/10,resolutionScore:res,headingDeltaDeg:diff==null?null:Math.round(diff*10)/10,localSpacingMeters:Number.isFinite(spacing)?Math.round(spacing*10)/10:null}}
  function sequenceStats(list){const distances=[],intervals=[],headings=[],qs=[];for(let i=0;i<list.length;i++){const q=mapillaryScore(list[i]);if(q!=null)qs.push(q);const h=frameHeading(list[i]);if(Number.isFinite(h))headings.push(h);if(i){const d=distanceMeters(list[i-1],list[i]);if(Number.isFinite(d))distances.push(d);const a=capturedMs(list[i-1]),b=capturedMs(list[i]);if(Number.isFinite(a)&&Number.isFinite(b)&&b>a)intervals.push(b-a)}}const headingD=[];for(let i=1;i<headings.length;i++)headingD.push(Math.abs(angle(headings[i-1],headings[i])));return{medianQuality:median(qs),medianSpacing:median(distances),meanSpacing:average(distances),medianInterval:median(intervals),headingStabilityDeg:median(headingD),qualitySamples:qs.length}}
  function canBridge(list,i,medianSpacing,medianInterval){if(i<=0||i>=list.length-1)return false;const a=list[i-1],b=list[i+1],c=list[i],seq=String(c?.sequenceId||'');if(String(a?.sequenceId||'')!==seq||String(b?.sequenceId||'')!==seq)return false;const d=distanceMeters(a,b),limit=Math.max(MAX_BRIDGE_METERS,Number.isFinite(medianSpacing)?Math.min(48,medianSpacing*3.25):0);if(!Number.isFinite(d)||d>limit)return false;const local=bearing(a,b),before=bearing(a,c),after=bearing(c,b),turn=Math.max(Math.abs(angle(before,local)||0),Math.abs(angle(local,after)||0));if(turn>MAX_BRIDGE_HEADING_DEG)return false;const ta=capturedMs(a),tb=capturedMs(b),dt=Number.isFinite(ta)&&Number.isFinite(tb)?Math.abs(tb-ta):null,timeLimit=Math.max(MAX_BRIDGE_TIME_MS,Number.isFinite(medianInterval)?Math.min(20000,medianInterval*3.5):0);return !Number.isFinite(dt)||dt<=timeLimit}
  function qualityBand(q){if(q==null)return'unknown';if(q>=QUALITY_THRESHOLDS.preferred)return'preferred';if(q>=QUALITY_THRESHOLDS.normal)return'normal';if(q>=QUALITY_THRESHOLDS.conditional)return'conditional';return'reject'}
  function qualityDecision(list,i,stats,rejectCount){const f=list[i],q=mapillaryScore(f),s=f.journeyQualityScore,band=qualityBand(q),candidate=band==='reject'||(band==='conditional'&&s<55)||(q==null&&s<QUALITY_THRESHOLDS.minJourneyScore);if(!candidate)return{reject:false,band,reason:'usable'};const maxReject=Math.max(1,Math.floor(list.length*QUALITY_THRESHOLDS.maxRejectRatio));if(rejectCount>=maxReject)return{reject:false,band,reason:'sequence-reject-cap'};if(i<=0||i>=list.length-1)return{reject:false,band,reason:'sequence-endpoint'};if(list[i-1]?._qualityRejected||list[i+1]?._qualityRejected)return{reject:false,band,reason:'avoid-adjacent-drop'};if(!canBridge(list,i,stats.medianSpacing,stats.medianInterval))return{reject:false,band,reason:'continuity-override'};return{reject:true,band,reason:q!=null?`mapillary-${band}`:'journey-score'}}

  const qualityById=new Map(),sequenceQuality=new Map(),qualityRejectedIds=new Set(),qualityKeptForContinuity=new Set();
  let qualityScoreFieldAvailable=null,qualityPreparationDone=false,qualityPreparationError=null,qualityRejectedFrames=0,qualityUnknownFrames=0,qualityMedian=0,qualityAverage=0,playbackStarted=false;
  function applyQualityToSequence(list){const stats=sequenceStats(list);for(let i=0;i<list.length;i++)Object.assign(list[i],scoreFrame(list,i,stats.medianSpacing));let rejectCount=0;for(let i=0;i<list.length;i++){const d=qualityDecision(list,i,stats,rejectCount);list[i].qualityBand=d.band;list[i].qualityDecision=d.reason;list[i]._qualityRejected=!!d.reject;if(d.reject)rejectCount++;else if(d.reason==='continuity-override')qualityKeptForContinuity.add(String(list[i].id||''))}const scores=list.map(f=>f.journeyQualityScore).filter(Number.isFinite);return{...stats,medianJourneyQualityScore:median(scores),meanJourneyQualityScore:average(scores),badFrameRatio:list.length?rejectCount/list.length:0,rejectedFrames:rejectCount,totalFrames:list.length}}
  function groupSequences(all){const groups=[];let current=[];for(const f of all){if(current.length&&String(current[0].sequenceId||'')!==String(f.sequenceId||'')){groups.push(current);current=[]}current.push(f)}if(current.length)groups.push(current);return groups}
  function updateQualitySummary(all){qualityRejectedFrames=qualityRejectedIds.size;const scores=all.map(f=>f.journeyQualityScore).filter(Number.isFinite);qualityMedian=median(scores)||0;qualityAverage=average(scores)||0;qualityUnknownFrames=all.filter(f=>mapillaryScore(f)==null).length}
  function computeQuality(all,allowStructuralFilter){qualityById.clear();sequenceQuality.clear();qualityRejectedIds.clear();qualityKeptForContinuity.clear();for(const group of groupSequences(all)){const stats=applyQualityToSequence(group);sequenceQuality.set(String(group[0]?.sequenceId||'unknown'),stats);for(const f of group){qualityById.set(String(f.id||''),f);if(f._qualityRejected)qualityRejectedIds.add(String(f.id||''))}}const selected=window.__journeySelectedRoute;if(selected&&allowStructuralFilter){const live=Array.isArray(selected.frames)?selected.frames:[],keep=live.filter(f=>!qualityRejectedIds.has(String(f.id||'')));if(keep.length>=2)live.splice(0,live.length,...keep);if(Array.isArray(selected.streamPending))selected.streamPending=selected.streamPending.filter(r=>!qualityRejectedIds.has(String(r.id||'')));if(selected.selection)selected.selection.totalImageIds=(selected.frames?.length||0)+(selected.streamPending?.length||0);try{sessionStorage.setItem(ROUTE_KEY,JSON.stringify(selected))}catch{}const stream=window.__journeyStreamState;if(stream){stream.frames=selected.frames;stream.total=selected.selection?.totalImageIds||selected.frames.length}}updateQualitySummary(all)}
  function currentRouteRecords(){const selected=window.__journeySelectedRoute;if(!selected)return[];return[...(selected.frames||[]),...(selected.streamPending||[]).map(x=>({...x,provider:selected.provider||'Mapillary'}))]}
  computeQuality(currentRouteRecords(),true);

  async function graphBatch(ids,fields){const t=token();if(!t)throw new Error('Mapillary token missing');const url=`${GRAPH}/images?image_ids=${encodeURIComponent(ids.join(','))}&fields=${encodeURIComponent(fields)}`;const r=await fetch(url,{headers:{Authorization:`OAuth ${t}`},cache:'no-store'}),j=await r.json().catch(()=>({}));if(!r.ok||j?.error)throw Object.assign(new Error(j?.error?.message||`Mapillary API ${r.status}`),{status:r.status});return j?.data||[]}
  async function fetchQualityMeta(ids){const out=new Map();if(!ids.length||!token())return out;for(let s=0;s<ids.length;s+=QUALITY_BATCH){const part=ids.slice(s,s+QUALITY_BATCH);let rows=null;if(qualityScoreFieldAvailable!==false){try{rows=await graphBatch(part,QUALITY_FIELDS_FULL);qualityScoreFieldAvailable=true}catch(e){if(e?.status===400)qualityScoreFieldAvailable=false;else throw e}}if(!rows){try{rows=await graphBatch(part,QUALITY_FIELDS_NO_SCORE)}catch{rows=await graphBatch(part,QUALITY_FIELDS_CORE)}}for(const row of rows||[])out.set(String(row.id),row)}return out}
  function mergeMeta(target,m){if(!target||!m)return target;const c=metaCoords(m);if(c){target.lat=c.lat;target.lng=c.lng}if(m.sequence!=null)target.sequenceId=String(m.sequence?.id??m.sequence);if(m.captured_at!=null)target.capturedAt=m.captured_at;const ch=Number(m.computed_compass_angle),eh=Number(m.compass_angle);if(Number.isFinite(ch)){target.heading=ch;target.headingSource='sfm-computed';target.computedHeading=ch}else if(Number.isFinite(eh)){target.heading=eh;target.headingSource=target.headingSource||'exif'}if(Number.isFinite(eh))target.exifHeading=eh;if(m.thumb_256_url){target.raw256Url=m.thumb_256_url;target.thumb_256_url=m.thumb_256_url}if(m.thumb_1024_url){target.raw1024Url=m.thumb_1024_url;target.thumb_1024_url=m.thumb_1024_url}if(m.thumb_2048_url){target.raw2048Url=m.thumb_2048_url;target.thumb_2048_url=m.thumb_2048_url;target.sourceUrl=target.sourceUrl||m.thumb_2048_url}if(Number.isFinite(Number(m.width)))target.width=Number(m.width);if(Number.isFinite(Number(m.height)))target.height=Number(m.height);if(typeof m.on_foot==='boolean')target.onFoot=m.on_foot;const q=Number(m.quality_score);if(Number.isFinite(q)&&q>0&&q<=1)target.mapillaryQualityScore=q;target.qualityScoreAvailable=qualityScoreFieldAvailable===true;return target}
  async function prepareQuality(){const selected=window.__journeySelectedRoute;if(!selected||selected.provider!=='Mapillary'){qualityPreparationDone=true;return}try{const all=currentRouteRecords(),ids=[...new Set(all.map(x=>String(x?.id||'')).filter(Boolean))],meta=await fetchQualityMeta(ids);for(const f of all)mergeMeta(f,meta.get(String(f.id||'')));computeQuality(all,!playbackStarted);for(const live of frames()){const q=qualityById.get(String(live?.id||''));if(q)Object.assign(live,q)}qualityPreparationDone=true;emit('quality-prepared',{qualityScoreFieldAvailable,total:all.length,rejected:qualityRejectedFrames,continuityOverrides:qualityKeptForContinuity.size,medianJourneyQualityScore:qualityMedian,sequenceStats:Object.fromEntries(sequenceQuality)})}catch(e){qualityPreparationError=String(e?.message||e);qualityPreparationDone=true;emit('quality-preparation-error',{message:qualityPreparationError})}}
  window.__journeyQualityReady=prepareQuality();

  /* Phase C */
  const tierCache=new Map(),tierInflight=new Map(),tierRejected=new Set(),metaTierInflight=new Map();
  let qualityShell=null,qualityLayer=null,currentTier='256',currentQualityIndex=-1,loadEwma=null,loadSamples=0,networkClass='NORMAL',networkSource='default',qualityLoads=0,qualityErrors=0,highResAhead=0;
  function initialNetwork(){const e=String(navigator.connection?.effectiveType||'').toLowerCase();if(e==='4g'){networkClass='FAST';networkSource='navigator'}else if(e==='2g'||e==='slow-2g'){networkClass='SLOW';networkSource='navigator'}else if(e==='3g'){networkClass='NORMAL';networkSource='navigator'}}initialNetwork();
  function recordLoad(ms){if(!Number.isFinite(ms)||ms<=0)return;loadEwma=loadEwma==null?ms:loadEwma*(1-LOAD_EWMA_ALPHA)+ms*LOAD_EWMA_ALPHA;loadSamples++;if(loadSamples>=2){networkClass=loadEwma<NETWORK_FAST_MS?'FAST':loadEwma<NETWORK_SLOW_MS?'NORMAL':'SLOW';networkSource='measured'}emit('network-sample',{elapsedMs:Math.round(ms),ewmaMs:Math.round(loadEwma),networkClass,source:networkSource})}
  window.addEventListener('journey-image-load',e=>{const d=e.detail||{};if(d.purpose==='raw'&&d.phase==='complete')recordLoad(Number(d.elapsedMs))});
  const tierKey=(i,t)=>`${i}:${t}`;
  function localTierUrl(f,tier){if(!f)return'';if(tier===2048)return String(f.raw2048Url||f.thumb_2048_url||f.sourceUrl||'');return String(f.raw1024Url||f.thumb_1024_url||'')}
  async function resolveTierUrl(index,tier){const f=frames()[index];if(!f)return'';const local=localTierUrl(f,tier);if(local)return local;if(f.provider!=='Mapillary'||!f.id||!token())return'';const k=`${f.id}:${tier}`;if(metaTierInflight.has(k))return await metaTierInflight.get(k);const field=tier===2048?'thumb_2048_url':'thumb_1024_url',p=(async()=>{try{const r=await fetch(`${GRAPH}/${encodeURIComponent(String(f.id))}?fields=${field}`,{headers:{Authorization:`OAuth ${token()}`},cache:'force-cache'}),j=await r.json().catch(()=>({})),u=r.ok&&!j?.error?String(j?.[field]||''):'';if(u){if(tier===2048){f.raw2048Url=u;f.thumb_2048_url=u}else{f.raw1024Url=u;f.thumb_1024_url=u}}return u}catch{return''}finally{metaTierInflight.delete(k)}})();metaTierInflight.set(k,p);return await p}
  function loadTier(index,tier){const key=tierKey(index,tier);if(tierCache.has(key))return Promise.resolve(tierCache.get(key));if(tierInflight.has(key))return tierInflight.get(key);if(tierRejected.has(key))return Promise.resolve(null);const p=(async()=>{const url=await resolveTierUrl(index,tier);if(!url)return null;const started=performance.now(),im=new Image();im.decoding='async';im.referrerPolicy='no-referrer';const ok=await new Promise(resolve=>{let done=false;const finish=v=>{if(done)return;done=true;im.onload=null;im.onerror=null;resolve(v)};im.onload=()=>finish(true);im.onerror=()=>finish(false);im.src=url});const elapsed=performance.now()-started;recordLoad(elapsed);if(!ok){tierRejected.add(key);qualityErrors++;return null}try{if(typeof im.decode==='function')await im.decode()}catch{}const edge=Math.max(im.naturalWidth||0,im.naturalHeight||0);if(edge<TIER_LONG_EDGE[tier]){tierRejected.add(key);qualityErrors++;return null}tierCache.set(key,im);qualityLoads++;emit('tier-load-complete',{index,tier,elapsedMs:Math.round(elapsed),width:im.naturalWidth,height:im.naturalHeight,networkClass});if(index===currentIndex())presentQuality(index);return im})().catch(()=>{tierRejected.add(key);qualityErrors++;return null}).finally(()=>tierInflight.delete(key));tierInflight.set(key,p);return p}
  function planForCurrent(){return QUALITY_PLAN[networkClass]||QUALITY_PLAN.NORMAL}
  function scheduleQuality(){const base=currentIndex(),ahead=rawAhead(),required=requiredRawAhead(),plan=planForCurrent();if(ahead<required)return;const cap=MAX_LOADS[networkClass]||2;if(tierInflight.size>=cap)return;const jobs=[];for(let offset=1;offset<=plan.far1024&&base+offset<frames().length;offset++){let tier=1024;if(offset<=plan.high2048)tier=2048;else if(offset>plan.near1024&&ahead<Math.max(12,required+5))continue;const key=tierKey(base+offset,tier);if(tierCache.has(key)||tierInflight.has(key)||tierRejected.has(key))continue;jobs.push([base+offset,tier]);if(jobs.length>=cap-tierInflight.size)break}for(const [i,t] of jobs)loadTier(i,t);updateHighResAhead(base)}
  function updateHighResAhead(base=currentIndex()){let n=0;for(let i=base+1;i<=Math.min(frames().length-1,base+18);i++){if(tierCache.has(tierKey(i,2048))||tierCache.has(tierKey(i,1024)))n++;else break}highResAhead=n;return n}
  function ensureQualityLayer(){if(qualityLayer?.isConnected)return qualityLayer;const viewer=document.getElementById('viewer');if(!viewer)return null;for(const id of ['journeyQualityLayer','journeyHybridQualityLayer']){const old=document.getElementById(id);if(old)old.style.display='none'}qualityShell=document.createElement('div');qualityShell.id='journeyAdaptiveQualityShell';qualityShell.style.cssText='position:absolute;inset:0;z-index:3;pointer-events:none;opacity:0;transform:translateZ(0);backface-visibility:hidden;-webkit-mask-image:linear-gradient(to right,transparent 1%,rgba(0,0,0,.18) 8%,rgba(0,0,0,.60) 18%,#000 28%,#000 72%,rgba(0,0,0,.60) 82%,rgba(0,0,0,.18) 92%,transparent 99%);mask-image:linear-gradient(to right,transparent 1%,rgba(0,0,0,.18) 8%,rgba(0,0,0,.60) 18%,#000 28%,#000 72%,rgba(0,0,0,.60) 82%,rgba(0,0,0,.18) 92%,transparent 99%);will-change:opacity';qualityLayer=document.createElement('img');qualityLayer.id='journeyAdaptiveQualityLayer';qualityLayer.alt='';qualityLayer.decoding='async';qualityLayer.draggable=false;qualityLayer.style.cssText='position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center;opacity:1;pointer-events:none;transform:translate3d(0,0,0);backface-visibility:hidden';qualityShell.appendChild(qualityLayer);viewer.appendChild(qualityShell);return qualityLayer}
  function alignQualityLayer(index){if(!qualityLayer)return;const x=window.__journeyTravelAxis?.anchorForFrame?.(index,50),v=window.__journeyVerticalCenter;qualityLayer.style.objectPosition=`${Number.isFinite(x)?clamp(x,2,98):50}% 50%`;qualityLayer.style.transform=`translate3d(0,${Number.isFinite(v?.frame)&&v.frame===index?Number(v.shift||0)*100:0}%,0)`}
  function bestTierImage(index){const hi=tierCache.get(tierKey(index,2048));if(hi)return{image:hi,tier:2048};const mid=tierCache.get(tierKey(index,1024));if(mid)return{image:mid,tier:1024};return null}
  function presentQuality(index){ensureQualityLayer();if(!qualityLayer)return false;const best=bestTierImage(index);if(!best){currentTier='256';currentQualityIndex=-1;if(qualityShell)qualityShell.style.opacity='0';return false}const src=String(best.image.currentSrc||best.image.src||'');if(!src)return false;if(qualityLayer.getAttribute('src')!==src)qualityLayer.setAttribute('src',src);alignQualityLayer(index);qualityShell.style.opacity='1';currentTier=String(best.tier);currentQualityIndex=index;emit('quality-present',{index,tier:best.tier,networkClass,rawAhead:rawAhead(),highResAhead});return true}
  function pruneTierCache(base=currentIndex()){const hiKeys=[],midKeys=[];for(const [key] of tierCache){const [iRaw,tRaw]=key.split(':'),i=Number(iRaw),t=Number(tRaw);if(i<base-1||i>base+20){tierCache.delete(key);continue}(t===2048?hiKeys:midKeys).push({key,i})}hiKeys.sort((a,b)=>Math.abs(a.i-base)-Math.abs(b.i-base));midKeys.sort((a,b)=>Math.abs(a.i-base)-Math.abs(b.i-base));for(let n=MAX_2048_CACHE;n<hiKeys.length;n++)tierCache.delete(hiKeys[n].key);for(let n=MAX_1024_CACHE;n<midKeys.length;n++)tierCache.delete(midKeys[n].key);for(const key of tierRejected){const i=Number(String(key).split(':')[0]);if(i<base-2||i>base+22)tierRejected.delete(key)}}

  /* Phase D */
  let warpCanvas=null,warpCtx=null,tileCanvas=null,tileCtx=null,intermediateFramesGenerated=0,warpRenderMs=0,warpFallbackReason='not-started',warpEnabled=false,opticalConfidence=0,warpCooldownUntil=0,scheduledWarp=0;
  function ensureWarpSurfaces(w,h,cols,rows,overlap){if(!warpCanvas){warpCanvas=document.createElement('canvas');warpCtx=warpCanvas.getContext('2d',{alpha:false})}if(warpCanvas.width!==w||warpCanvas.height!==h){warpCanvas.width=w;warpCanvas.height=h}const tw=Math.ceil(w/cols+overlap*2+6),th=Math.ceil(h/rows+overlap*2+6);if(!tileCanvas){tileCanvas=document.createElement('canvas');tileCtx=tileCanvas.getContext('2d',{alpha:true})}if(tileCanvas.width!==tw||tileCanvas.height!==th){tileCanvas.width=tw;tileCanvas.height=th}return{tw,th}}
  function neighborClamp(vs,cols,rows,maxDx,maxDy){const out=vs.map(v=>({...v}));for(let pass=0;pass<2;pass++){const prev=out.map(v=>({...v}));for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const i=r*cols+c,v=out[i],ns=[];if(c>0)ns.push(prev[i-1]);if(c+1<cols)ns.push(prev[i+1]);if(r>0)ns.push(prev[i-cols]);if(r+1<rows)ns.push(prev[i+cols]);if(!ns.length)continue;const ax=average(ns.map(n=>n.vx)),ay=average(ns.map(n=>n.vy));v.vx=ax+clamp(v.vx-ax,-maxDx,maxDx);v.vy=ay+clamp(v.vy-ay,-maxDy,maxDy)}}return out}
  function pairGate(i,pair){const b=bridge(),aFrame=b?.getRouteFrame?.(i)||frames()[i],zFrame=b?.getRouteFrame?.(i+1)||frames()[i+1];if(!b)return'bridge-missing';if(!pair||!pair.a?.canvas||!pair.b?.canvas)return'pair-not-ready';if(isSphere(aFrame)||isSphere(zFrame))return'sphere';if(String(aFrame?.sequenceId||'')!==String(zFrame?.sequenceId||''))return'sequence-boundary';if(rawAhead()<Math.min(WARP_MIN_RAW_AHEAD,remainingAhead()))return'raw-ahead-low';const d=distanceMeters(aFrame,zFrame);if(Number.isFinite(d)&&d>WARP_MAX_DISTANCE_M)return'distance';const ba=Number(b.getTravelBearing?.(i)),bb=Number(b.getTravelBearing?.(i+1)),turn=Number.isFinite(ba)&&Number.isFinite(bb)?Math.abs(angle(ba,bb)):0;if(turn>WARP_MAX_TURN_DEG)return'heading';const vs=Array.isArray(pair.vs)?pair.vs:[],good=vs.filter(v=>Number(v.confidence)>=WARP_MIN_TILE_CONF),avg=average(vs.map(v=>Number(v.confidence)||0))||0;opticalConfidence=Math.round(avg*1000)/1000;if(vs.length<12||good.length<WARP_MIN_GOOD_TILES||avg<WARP_MIN_AVG_CONF)return'tile-confidence';const wp=b.getWorkerPair?.(i);if(wp){if(Number(wp.parallaxFactor)>2.4&&Number(wp.safetyFactor)<.95)return'extreme-parallax';if(Number(wp.confidence)<.12&&Number(wp.tracks)<8)return'worker-confidence'}if(performance.now()<warpCooldownUntil)return'performance-cooldown';return null}
  function featherScratch(w,h,feather){tileCtx.globalCompositeOperation='destination-in';let g=tileCtx.createLinearGradient(0,0,w,0);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(clamp(feather/w,0,.35),'rgba(0,0,0,1)');g.addColorStop(1-clamp(feather/w,0,.35),'rgba(0,0,0,1)');g.addColorStop(1,'rgba(0,0,0,0)');tileCtx.fillStyle=g;tileCtx.fillRect(0,0,w,h);g=tileCtx.createLinearGradient(0,0,0,h);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(clamp(feather/h,0,.35),'rgba(0,0,0,1)');g.addColorStop(1-clamp(feather/h,0,.35),'rgba(0,0,0,1)');g.addColorStop(1,'rgba(0,0,0,0)');tileCtx.fillStyle=g;tileCtx.fillRect(0,0,w,h);tileCtx.globalCompositeOperation='source-over'}
  function renderIntermediate(i){const b=bridge(),pair=b?.getPreparedPair?.(i),reason=pairGate(i,pair);if(reason){warpEnabled=false;warpFallbackReason=reason;return false}const target=document.getElementById('flowCanvas');if(!target?.getContext){warpEnabled=false;warpFallbackReason='canvas-missing';return false}const cfg=b.getTileConfig?.()||{cols:4,rows:5,analysisW:80,analysisH:120,overlapPx:12,maxNeighborDx:1.65,maxNeighborDy:1.25},w=target.width,h=target.height;if(!w||!h){warpEnabled=false;warpFallbackReason='canvas-size';return false}const started=performance.now(),overlap=Math.max(4,Number(cfg.overlapPx)||12),cols=Number(cfg.cols)||4,rows=Number(cfg.rows)||5;ensureWarpSurfaces(w,h,cols,rows,overlap);warpCtx.globalAlpha=1;warpCtx.globalCompositeOperation='source-over';warpCtx.drawImage(pair.a.canvas,0,0,w,h);warpCtx.globalAlpha=.5;warpCtx.drawImage(pair.b.canvas,0,0,w,h);warpCtx.globalAlpha=1;const vectors=neighborClamp(pair.vs,cols,rows,Number(cfg.maxNeighborDx)||1.65,Number(cfg.maxNeighborDy)||1.25),tileW=w/cols,tileH=h/rows,sxScale=w/(Number(cfg.analysisW)||80),syScale=h/(Number(cfg.analysisH)||120);for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const v=vectors[r*cols+c]||{vx:0,vy:0,confidence:0},x0=Math.max(0,Math.floor(c*tileW-overlap)),y0=Math.max(0,Math.floor(r*tileH-overlap)),x1=Math.min(w,Math.ceil((c+1)*tileW+overlap)),y1=Math.min(h,Math.ceil((r+1)*tileH+overlap)),sw=x1-x0,sh=y1-y0;if(sw<=1||sh<=1)continue;tileCtx.clearRect(0,0,tileCanvas.width,tileCanvas.height);const mag=Math.hypot(Number(v.vx)||0,Number(v.vy)||0),depthGain=.82+clamp((mag-.35)/4.2,0,1)*.30,dx=(Number(v.vx)||0)*sxScale*depthGain,dy=(Number(v.vy)||0)*syScale*depthGain;tileCtx.globalAlpha=.5;tileCtx.drawImage(pair.a.canvas,x0,y0,sw,sh,dx*INTERMEDIATE_T,dy*INTERMEDIATE_T,sw,sh);tileCtx.drawImage(pair.b.canvas,x0,y0,sw,sh,-dx*(1-INTERMEDIATE_T),-dy*(1-INTERMEDIATE_T),sw,sh);tileCtx.globalAlpha=1;featherScratch(sw,sh,Math.min(overlap,Math.max(4,Math.min(sw,sh)*.18)));warpCtx.globalAlpha=clamp(.55+(Number(v.confidence)||0)*2.2,.58,.88);warpCtx.drawImage(tileCanvas,0,0,sw,sh,x0,y0,sw,sh)}warpCtx.globalAlpha=1;const elapsed=performance.now()-started;warpRenderMs=Math.round(elapsed*10)/10;if(elapsed>WARP_MAX_RENDER_MS){warpCooldownUntil=performance.now()+600;warpEnabled=false;warpFallbackReason='render-budget';return false}const ctx=target.getContext('2d',{alpha:false});ctx.globalAlpha=1;ctx.drawImage(warpCanvas,0,0,w,h);intermediateFramesGenerated++;warpEnabled=true;warpFallbackReason=null;try{Object.assign(window.__journeyDiagnostics||{},{opticalConfidence,warpEnabled:true,warpFallbackReason:null,intermediateFramesGenerated,warpRenderMs})}catch{}emit('intermediate-rendered',{index,t:INTERMEDIATE_T,tiles:cols*rows,opticalConfidence,warpRenderMs});return true}
  function scheduleIntermediate(index){scheduledWarp++;const ticket=scheduledWarp,b=bridge(),ms=Number(b?.getSpeedMs?.()||playback().targetMs||80),delay=Math.max(8,ms*.5-2);setTimeout(()=>{if(ticket!==scheduledWarp||currentIndex()!==index)return;renderIntermediate(index)},delay)}

  function onFramePresented(e){const i=Number(e.detail?.index);if(!Number.isFinite(i))return;playbackStarted=true;presentQuality(i);pruneTierCache(i);scheduleQuality();scheduleIntermediate(i);updateHighResAhead(i)}
  window.addEventListener('journey-frame-presented',onFramePresented);
  window.addEventListener('journey-playback-started',()=>{playbackStarted=true;ensureQualityLayer();scheduleQuality()});
  window.addEventListener('journey-stream-updated',()=>{scheduleQuality()});
  setInterval(()=>{scheduleQuality();pruneTierCache()},120);

  window.__journeyPlaybackTest={speeds:TEST_SPEEDS.slice(),set(ms){const v=Number(ms);if(!TEST_SPEEDS.includes(v))throw new Error(`speed must be one of ${TEST_SPEEDS.join(',')}`);const b=bridge();if(!b?.setPlaybackMs)throw new Error('Journey optical bridge is not ready');return b.setPlaybackMs(v)},get(){return Number(bridge()?.getSpeedMs?.()||playback().targetMs||80)}};
  window.__journeyHybridQuality={version:VERSION,state:()=>({
    version:VERSION,
    journeyQualityScore:qualityMedian,journeyQualityAverage:qualityAverage,qualityRejectedFrames,qualityUnknownFrames,qualityScoreFieldAvailable,qualityPreparationDone,qualityPreparationError,qualityWeights:QUALITY_WEIGHTS,qualityThresholds:QUALITY_THRESHOLDS,qualityContinuityOverrides:qualityKeptForContinuity.size,sequenceQuality:Object.fromEntries(sequenceQuality),
    networkClass,networkSource,loadEwmaMs:loadEwma==null?null:Math.round(loadEwma),loadSamples,currentImageTier:currentTier,highResAhead,rawAhead:rawAhead(),urlAhead:FAR_URL_AHEAD,qualityLoads,qualityErrors,qualityCache:{tier1024:[...tierCache.keys()].filter(k=>k.endsWith(':1024')).length,tier2048:[...tierCache.keys()].filter(k=>k.endsWith(':2048')).length,inflight:tierInflight.size},
    opticalConfidence,warpEnabled,warpFallbackReason,intermediateFramesGenerated,warpRenderMs,warpConfig:{t:INTERMEDIATE_T,minRawAhead:WARP_MIN_RAW_AHEAD,maxDistanceMeters:WARP_MAX_DISTANCE_M,maxTurnDeg:WARP_MAX_TURN_DEG,maxRenderMs:WARP_MAX_RENDER_MS},testSpeeds:TEST_SPEEDS.slice(),
    qualityNote:'A: quality_score is runtime-probed and falls back to JourneyQualityScore. C: raw continuity stays first; 1024/2048 are adaptive overlays. D: existing preparedPair/tile vectors are rendered only when already ready and never block 80ms playback.'
  }),test:{scoreFrame,sequenceStats,applyQualityToSequence,canBridge,qualityBand,qualityDecision,neighborClamp,pairGate}};
  emit('ready',{phase:'A+C+D',networkClass,qualityWeights:QUALITY_WEIGHTS,qualityThresholds:QUALITY_THRESHOLDS,progressivePlan:QUALITY_PLAN,intermediateT:INTERMEDIATE_T,testSpeeds:TEST_SPEEDS.slice()});
})();
