(() => {
  'use strict';
  const STYLE_URL='https://tiles.openfreemap.org/styles/liberty';
  const TOKEN_KEY='streetview:mapillary-token';
  const ROUTE_KEY='streetview:journey-route';
  const KARTA_SOURCE='kartaview-coverage',KARTA_LAYER='kartaview-coverage-layer';
  const MLY_SOURCE='mapillary-coverage',MLY_GLOW='mapillary-sequence-glow',MLY_LINE='mapillary-sequence-line',MLY_IMAGE='mapillary-image-points';
  const GRAPH='https://graph.mapillary.com';
  const MAX_FRAMES=72;
  const $=id=>document.getElementById(id);
  let map=null,loaded=false,mapillaryReady=false,candidateAbort=null,currentCandidate=null;

  function getToken(){try{return localStorage.getItem(TOKEN_KEY)||'';}catch{return'';}}
  function setToken(v){try{if(v)localStorage.setItem(TOKEN_KEY,v);else localStorage.removeItem(TOKEN_KEY);}catch{}}
  function setStatus(t){if($('mapStatus'))$('mapStatus').textContent=t;}
  function setLayerVisible(id,on){if(map?.getLayer(id))map.setLayoutProperty(id,'visibility',on?'visible':'none');}
  function removeMapillary(){if(!map)return;for(const id of [MLY_IMAGE,MLY_LINE,MLY_GLOW])if(map.getLayer(id))map.removeLayer(id);if(map.getSource(MLY_SOURCE))map.removeSource(MLY_SOURCE);mapillaryReady=false;}
  function dist(a,b){const r=Math.PI/180,p1=a.lat*r,p2=b.lat*r,dp=(b.lat-a.lat)*r,dl=(b.lng-a.lng)*r,s=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 12742000*Math.atan2(Math.sqrt(s),Math.sqrt(Math.max(0,1-s)));}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

  function installCandidateUI(){
    if($('journeyCandidate'))return;
    const style=document.createElement('style');style.textContent=`.coverage-map{cursor:crosshair}.journey-candidate{position:fixed;z-index:12;left:14px;right:14px;bottom:calc(var(--safe-bottom) + 14px);transform:translateY(125%);opacity:0;pointer-events:none;transition:transform .28s cubic-bezier(.2,.8,.2,1),opacity .2s;padding:14px;border:1px solid rgba(255,255,255,.15);border-radius:20px;background:rgba(7,15,14,.94);box-shadow:0 16px 46px rgba(0,0,0,.34);backdrop-filter:blur(22px);-webkit-backdrop-filter:blur(22px)}.journey-candidate.is-open{transform:translateY(0);opacity:1;pointer-events:auto}.journey-candidate.is-loading .jc-main{opacity:.55}.provider-panel.has-candidate{transform:translateY(125%);opacity:0;pointer-events:none}.provider-panel{transition:transform .28s cubic-bezier(.2,.8,.2,1),opacity .2s}.jc-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.jc-kicker{font-size:8px;font-weight:850;letter-spacing:.16em;color:#65e8ff}.jc-kicker.mapillary{color:#73ffa1}.jc-close{width:32px;height:32px;border:1px solid rgba(255,255,255,.12);border-radius:999px;background:rgba(255,255,255,.06);color:#fff;font-size:18px}.jc-main{display:grid;gap:5px;margin-top:8px}.jc-main strong{font-size:18px;letter-spacing:-.025em}.jc-main p{margin:0;font-size:10px;line-height:1.5;color:rgba(255,255,255,.58)}.jc-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:11px}.jc-stat{display:grid;gap:3px;padding:9px 10px;border:1px solid rgba(255,255,255,.09);border-radius:12px;background:rgba(255,255,255,.035)}.jc-stat small{font-size:8px;color:rgba(255,255,255,.42)}.jc-stat b{font-size:11px;overflow:hidden;text-overflow:ellipsis}.jc-actions{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:10px}.jc-actions button{display:grid;place-items:center;min-height:44px;border:1px solid rgba(255,255,255,.12);border-radius:13px;font-size:11px;font-weight:800}.jc-actions .primary{background:#fff;color:#07110f}.jc-actions .secondary{padding:0 15px;background:rgba(255,255,255,.06);color:#fff}.jc-error{color:#ffcf9b!important}@media(orientation:landscape){.journey-candidate{left:14px;right:auto;width:min(390px,42vw)}}`;
    document.head.appendChild(style);
    const card=document.createElement('section');card.id='journeyCandidate';card.className='journey-candidate';card.innerHTML=`<div class="jc-head"><span id="candidateKicker" class="jc-kicker">JOURNEY CANDIDATE</span><button id="candidateClose" class="jc-close" type="button">×</button></div><div class="jc-main"><strong id="candidateTitle">撮影済みルートを確認中</strong><p id="candidateText">sequenceを直接確認している。</p></div><div id="candidateStats" class="jc-stats" hidden></div><div id="candidateActions" class="jc-actions" hidden><button id="candidateStart" class="primary" type="button">このルートでJourney開始</button><button id="candidateDismiss" class="secondary" type="button">戻る</button></div>`;document.body.appendChild(card);
    $('candidateClose').addEventListener('click',closeCandidate);$('candidateDismiss').addEventListener('click',closeCandidate);$('candidateStart').addEventListener('click',startCandidateJourney);
  }
  function closeCandidate(){candidateAbort?.abort();candidateAbort=null;currentCandidate=null;$('journeyCandidate')?.classList.remove('is-open','is-loading');document.querySelector('.provider-panel')?.classList.remove('has-candidate');}
  function openLoading(provider,text){installCandidateUI();currentCandidate=null;const c=$('journeyCandidate');c.classList.add('is-open','is-loading');document.querySelector('.provider-panel')?.classList.add('has-candidate');$('candidateKicker').textContent=`${provider.toUpperCase()} JOURNEY CANDIDATE`;$('candidateKicker').classList.toggle('mapillary',provider==='Mapillary');$('candidateTitle').textContent='撮影済みsequenceを読み込み中';$('candidateText').classList.remove('jc-error');$('candidateText').textContent=text;$('candidateStats').hidden=true;$('candidateActions').hidden=true;}
  function renderError(provider,msg){$('journeyCandidate').classList.remove('is-loading');$('candidateKicker').textContent=`${provider.toUpperCase()} JOURNEY CANDIDATE`;$('candidateKicker').classList.toggle('mapillary',provider==='Mapillary');$('candidateTitle').textContent='この場所では候補を作れなかった';$('candidateText').classList.add('jc-error');$('candidateText').textContent=msg;$('candidateStats').hidden=true;$('candidateActions').hidden=true;}
  function formatDistance(d){return Number.isFinite(d)?(d<1000?`${Math.round(d)}m`:`${(d/1000).toFixed(1)}km`):'直接選択';}
  function renderRouteCandidate(payload,extra={}){currentCandidate=payload;const p=payload.provider||payload.source||'Coverage',frames=payload.frames||[],sel=payload.selection||{};$('journeyCandidate').classList.remove('is-loading');$('candidateKicker').textContent=`${p.toUpperCase()} JOURNEY CANDIDATE`;$('candidateKicker').classList.toggle('mapillary',p==='Mapillary');$('candidateTitle').textContent=`Sequence ${payload.sequenceId||'—'}`;$('candidateText').classList.remove('jc-error');$('candidateText').textContent=`${p}の撮影済みsequenceを直接選択した。広域の別sequence探索はしていない。`;const stats=$('candidateStats');stats.hidden=false;stats.innerHTML=`<div class="jc-stat"><small>Provider</small><b>${esc(p)}</b></div><div class="jc-stat"><small>連続画像</small><b>${frames.length}枚</b></div><div class="jc-stat"><small>${extra.thirdLabel||'タップ地点から'}</small><b>${esc(extra.thirdValue||formatDistance(Number(sel.proximityMeters)))}</b></div>`;$('candidateActions').hidden=false;}
  function startCandidateJourney(){if(!currentCandidate?.frames?.length)return;try{sessionStorage.setItem(ROUTE_KEY,JSON.stringify(currentCandidate));}catch(e){renderError(currentCandidate.provider||'Coverage','選択ルートをJourney Engineへ渡せませんでした。');return;}location.href='/journey-map.html?autostart=1';}

  async function findKartaDirect(ll){if(!$('kartaToggle')?.checked)return;openLoading('KartaView',`${ll.lat.toFixed(5)}, ${ll.lng.toFixed(5)} の紫ルートから最寄り写真を直接特定中…`);candidateAbort?.abort();candidateAbort=new AbortController();try{const q=new URLSearchParams({source:'karta',mode:'nearest',lat:String(ll.lat),lng:String(ll.lng)}),r=await fetch(`/api/imagery?${q}`,{signal:candidateAbort.signal,cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'KartaView sequenceを特定できませんでした');renderRouteCandidate(d);}catch(e){if(e?.name!=='AbortError')renderError('KartaView',e?.message||'KartaView候補を作れませんでした');}finally{candidateAbort=null;}}

  async function mlyFetch(path){const token=getToken();if(!token)throw new Error('Mapillary Access Tokenが未設定です');const r=await fetch(`${GRAPH}${path}`,{headers:{Authorization:`OAuth ${token}`}});const d=await r.json().catch(()=>({}));if(!r.ok||d?.error)throw new Error(d?.error?.message||`Mapillary API ${r.status}`);return d;}
  async function imageMeta(id){const fields='id,sequence,captured_at,computed_geometry,compass_angle,thumb_2048_url,is_pano';return mlyFetch(`/${encodeURIComponent(id)}?fields=${fields}`);}
  function featureId(f){return String(f?.properties?.id??f?.properties?.image_id??f?.properties?.sequence_id??f?.id??'').trim();}
  async function pool(items,limit,fn){const out=new Array(items.length);let at=0;async function worker(){while(true){const i=at++;if(i>=items.length)return;try{out[i]=await fn(items[i],i);}catch{out[i]=null;}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out;}
  function normalizeMlyFrame(m,seq,index){const c=m?.computed_geometry?.coordinates;if(!Array.isArray(c)||c.length<2||!m?.thumb_2048_url)return null;return{id:String(m.id),sequenceId:String(seq),sequenceIndex:index,lat:Number(c[1]),lng:Number(c[0]),heading:Number.isFinite(Number(m.compass_angle))?Number(m.compass_angle):null,projection:m.is_pano?'SPHERE':'RECTILINEAR',fieldOfView:m.is_pano?360:100,url:m.thumb_2048_url,provider:'Mapillary',capturedAt:m.captured_at||null};}
  async function mapillarySequencePayload(sequenceId,anchorImageId,ll){const idsData=await mlyFetch(`/image_ids?sequence_id=${encodeURIComponent(sequenceId)}`),ids=(idsData?.data||[]).map(x=>String(x?.id??x)).filter(Boolean);if(ids.length<2)throw new Error('このMapillary sequenceには連続画像がありません');let anchor=anchorImageId?ids.indexOf(String(anchorImageId)):-1;if(anchor<0)anchor=Math.floor(ids.length/2);let start=Math.max(0,anchor-Math.floor(MAX_FRAMES*.35));if(start+MAX_FRAMES>ids.length)start=Math.max(0,ids.length-MAX_FRAMES);const windowIds=ids.slice(start,start+MAX_FRAMES),meta=await pool(windowIds,8,id=>imageMeta(id)),frames=meta.map((m,i)=>normalizeMlyFrame(m,sequenceId,start+i)).filter(Boolean);if(frames.length<2)throw new Error('Mapillary画像URLを取得できませんでした');let nearest=null;if(ll){for(const f of frames){const d=dist(ll,f);if(nearest===null||d<nearest)nearest=d;}}return{version:'0.2.1',source:'Mapillary',provider:'Mapillary',sequenceId:String(sequenceId),anchorIndex:anchor,selection:{strategy:'direct-vector-feature',direction:'forward',alignmentErrorDeg:null,proximityMeters:nearest,searchMode:anchorImageId?'mapillary-image-feature':'mapillary-sequence-feature',candidateCount:1,visualOverride:false},frames,candidateRoutes:[]};}
  async function findMapillaryDirect(feature,ll){const token=getToken();if(!token){openSheet();return;}const layer=feature?.layer?.id||'',id=featureId(feature);if(!id){renderError('Mapillary','タップしたMapillary featureからIDを取得できませんでした');return;}openLoading('Mapillary','Vector Tileのfeature IDからMapillary sequenceを直接読み込み中…');try{let sequenceId=null,anchorImageId=null;if(layer===MLY_IMAGE){anchorImageId=id;const m=await imageMeta(id);sequenceId=String(m?.sequence?.id??m?.sequence??'');}else sequenceId=id;if(!sequenceId)throw new Error('Mapillary sequence IDを取得できませんでした');const payload=await mapillarySequencePayload(sequenceId,anchorImageId,ll);renderRouteCandidate(payload,{thirdLabel:'Mapillary',thirdValue:anchorImageId?'画像点を直接選択':'sequence線を直接選択'});}catch(e){renderError('Mapillary',e?.message||'Mapillary候補を作れませんでした');}}

  function installKartaView(){if(!map||map.getSource(KARTA_SOURCE))return;map.addSource(KARTA_SOURCE,{type:'raster',tiles:['https://api.openstreetcam.org/2.0/sequence/tiles/{x}/{y}/{z}.png'],tileSize:256,minzoom:0,maxzoom:20,attribution:'© KartaView'});map.addLayer({id:KARTA_LAYER,type:'raster',source:KARTA_SOURCE,paint:{'raster-opacity':.88,'raster-contrast':.16,'raster-saturation':.35,'raster-brightness-max':1}});$('kartaStatus').textContent='実データ表示中';}
  function installMapillary(token){if(!map||!loaded||!token)return;removeMapillary();const url=`https://tiles.mapillary.com/maps/vtp/mly1_public/2/{z}/{x}/{y}?access_token=${encodeURIComponent(token)}`;map.addSource(MLY_SOURCE,{type:'vector',tiles:[url],minzoom:6,maxzoom:14,attribution:'© Mapillary'});map.addLayer({id:MLY_GLOW,type:'line',source:MLY_SOURCE,'source-layer':'sequence',minzoom:6,paint:{'line-color':'#58ff93','line-width':['interpolate',['linear'],['zoom'],6,2,11,5,14,10],'line-opacity':.25,'line-blur':3}});map.addLayer({id:MLY_LINE,type:'line',source:MLY_SOURCE,'source-layer':'sequence',minzoom:6,paint:{'line-color':'#73ffa1','line-width':['interpolate',['linear'],['zoom'],6,.8,11,1.7,14,3.1],'line-opacity':.92}});map.addLayer({id:MLY_IMAGE,type:'circle',source:MLY_SOURCE,'source-layer':'image',minzoom:14,paint:{'circle-radius':['interpolate',['linear'],['zoom'],14,2,18,4.2],'circle-color':'#dcffe6','circle-opacity':.86,'circle-stroke-width':1,'circle-stroke-color':'#43ff86'}});mapillaryReady=true;$('mapillaryToggle').checked=true;$('mapillaryStatus').textContent='接続中';}
  function openSheet(){const s=$('tokenSheet');if(!s)return;$('mapillaryToken').value=getToken();s.hidden=false;requestAnimationFrame(()=>$('mapillaryToken').focus());}
  function closeSheet(){$('tokenSheet').hidden=true;}
  function updateMapillaryState(){const token=getToken();if(!token){removeMapillary();$('mapillaryToggle').checked=false;$('mapillaryStatus').textContent='トークン未設定';return;}if(loaded&&!mapillaryReady)installMapillary(token);}
  function mapillaryFeatureAt(point){if(!mapillaryReady||!$('mapillaryToggle')?.checked)return null;const layers=[MLY_IMAGE,MLY_LINE].filter(id=>map.getLayer(id));if(!layers.length)return null;const r=12,b=[[point.x-r,point.y-r],[point.x+r,point.y+r]],fs=map.queryRenderedFeatures(b,{layers});if(!fs.length)return null;return fs.find(f=>f.layer?.id===MLY_IMAGE)||fs[0];}

  function init(){installCandidateUI();if(!window.maplibregl){setStatus('MapLibreを読み込めませんでした');return;}map=new maplibregl.Map({container:'coverageMap',style:STYLE_URL,center:[135.7681,35.0116],zoom:11.3,pitch:0,bearing:0,attributionControl:false,maxPitch:55});map.addControl(new maplibregl.NavigationControl({showCompass:true,showZoom:true}),'top-right');map.addControl(new maplibregl.GeolocateControl({positionOptions:{enableHighAccuracy:true},trackUserLocation:false,showUserHeading:true,fitBoundsOptions:{maxZoom:15}}),'top-right');map.addControl(new maplibregl.AttributionControl({compact:true}),'bottom-right');map.on('load',()=>{loaded=true;installKartaView();updateMapillaryState();setStatus('実データ表示中');});map.on('click',e=>{const f=mapillaryFeatureAt(e.point);if(f){findMapillaryDirect(f,{lat:e.lngLat.lat,lng:e.lngLat.lng});return;}findKartaDirect(e.lngLat);});map.on('sourcedata',e=>{if(e.sourceId===MLY_SOURCE&&e.isSourceLoaded){$('mapillaryStatus').textContent='実データ表示中';setStatus('Mapillary + KartaView');}});map.on('error',e=>{const msg=String(e?.error?.message||'');if(msg.includes('mapillary')||msg.includes('401')||msg.includes('403'))$('mapillaryStatus').textContent='トークンを確認';});$('kartaToggle').addEventListener('change',e=>{setLayerVisible(KARTA_LAYER,e.target.checked);closeCandidate();});$('mapillaryToggle').addEventListener('change',e=>{if(!getToken()){e.target.checked=false;openSheet();return;}for(const id of [MLY_GLOW,MLY_LINE,MLY_IMAGE])setLayerVisible(id,e.target.checked);closeCandidate();});$('mapillarySettings').addEventListener('click',openSheet);$('tokenBackdrop').addEventListener('click',closeSheet);$('closeTokenSheet').addEventListener('click',closeSheet);$('saveToken').addEventListener('click',()=>{const token=$('mapillaryToken').value.trim();if(!token)return;setToken(token);removeMapillary();installMapillary(token);closeSheet();});$('removeToken').addEventListener('click',()=>{setToken('');$('mapillaryToken').value='';updateMapillaryState();closeSheet();});}
  init();
})();
