(()=>{'use strict';
const VERSION='mapillaryjs-preload-default-v4',TOKEN_KEY='streetview:mapillary-token',ROUTE_KEY='streetview:mapillaryjs-route-cache',LOAD_KEY='streetview:mapillaryjs-load-estimate-ms',SIG='karasuma-oike-shijo-50',GRAPH='https://graph.mapillary.com',SEQ='eRtWQS4YlTPjy1rxpokA2q',START_ID='1660100068763369',GOAL_ID='2131906120977191',START={lat:35.01039,lng:135.75943},GOAL={lat:35.00367,lng:135.75937},TARGET=50,MAX_ROUTE_M=50,CACHE_DEPTH={sequence:4,spherical:0,step:0,turn:0},PRELOAD_CADENCE=800,PRELOAD_SAMPLE=6,PRELOAD_MIN=10,PRELOAD_MAX=34,PRELOAD_SAFETY=4,REG_SOFT=.018,REG_HARD=.08,REG_STREAK=3,$=id=>document.getElementById(id),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const s={viewer:null,preloader:null,frames:[],sequenceId:'—',direction:'—',cursor:0,playing:false,token:0,success:0,transition:[],cadence:[],logs:[],initialMs:null,lastTransition:null,lastCadence:null,lastDisplay:null,progress:null,routeDistance:null,travelHeading:null,viewHeading:null,viewOffset:0,heldOffset:0,projection:'—',pointer:false,correcting:false,maxProgress:null,regStreak:0,reverse:0,jumps:0,stopReason:'not-started',setupStart:performance.now(),setupMs:null,preloadReady:0,preloadTarget:0,preloadDur:[],preloadEstimate:null,preloadMs:null,preloadFailures:0,preloaded:new Set(),warmIndex:1,warming:false,deadlineMisses:0,routeCacheHit:false};
const token=()=>{try{return localStorage.getItem(TOKEN_KEY)||''}catch{return''}},status=t=>{$('status').textContent=t},norm=v=>(+v%360+360)%360,diff=(a,b)=>{let d=norm(a)-norm(b);if(d>180)d-=360;if(d<-180)d+=360;return d},clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null,fmt=(v,d=0,u='')=>Number.isFinite(v)?`${(+v).toFixed(d)}${u}`:'—';
function distance(a,b){const r=Math.PI/180,p1=a.lat*r,p2=b.lat*r,dp=(b.lat-a.lat)*r,dl=(b.lng-a.lng)*r,q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 12742000*Math.atan2(Math.sqrt(q),Math.sqrt(Math.max(0,1-q)))}
function bearing(a,b){const r=Math.PI/180,p1=a.lat*r,p2=b.lat*r,dl=(b.lng-a.lng)*r,y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return norm(Math.atan2(y,x)*180/Math.PI)}
function metrics(p){const lat0=(START.lat+GOAL.lat)*.5*Math.PI/180,c=Math.cos(lat0),mx=111320*c,my=111320,vx=(GOAL.lng-START.lng)*mx,vy=(GOAL.lat-START.lat)*my,px=(p.lng-START.lng)*mx,py=(p.lat-START.lat)*my,den=vx*vx+vy*vy,t=den?(px*vx+py*vy)/den:0,tc=clamp(t,0,1);return{progress:t,distance:Math.hypot(px-vx*tc,py-vy*tc)}}
async function api(path){const res=await fetch(`${GRAPH}${path}${path.includes('?')?'&':'?'}access_token=${encodeURIComponent(token())}`,{cache:'no-store'}),j=await res.json().catch(()=>({}));if(!res.ok||j?.error)throw new Error(j?.error?.message||`Mapillary API ${res.status}`);return j}
async function ordered(){const j=await api(`/image_ids?sequence_id=${encodeURIComponent(SEQ)}`);return(j?.data||[]).map(x=>String(x?.id??x)).filter(Boolean)}
async function meta(ids){const out=new Map(),fields='id,computed_geometry,computed_compass_angle,compass_angle,is_pano';for(let i=0;i<ids.length;i+=24){const part=ids.slice(i,i+24),j=await api(`/images?image_ids=${encodeURIComponent(part.join(','))}&limit=${part.length}&fields=${encodeURIComponent(fields)}`);for(const m of j?.data||[])out.set(String(m.id),m)}return out}
function sample(ids,n=TARGET){if(ids.length<=n)return ids.slice();const out=[],used=new Set(),step=(ids.length-1)/(n-1);for(let i=0;i<n;i++){const id=ids[Math.round(i*step)];if(id&&!used.has(id)){used.add(id);out.push(id)}}return out}
function loadCached(){try{const c=JSON.parse(localStorage.getItem(ROUTE_KEY)||'null');if(c?.signature!==SIG||c?.sequenceId!==SEQ||!Array.isArray(c.frames)||c.frames.length!==TARGET)return null;if(!c.frames.every(f=>f?.id&&Number.isFinite(+f.routeProgress)&&Number.isFinite(+f.routeDistance)))return null;s.routeCacheHit=true;return c}catch{return null}}
function saveCached(route){try{localStorage.setItem(ROUTE_KEY,JSON.stringify({signature:SIG,savedAt:Date.now(),...route}))}catch{}}
async function route(){const c=loadCached();if(c)return c;status('成功済みsequenceをGPSで確認中…');const ids=await ordered(),a=ids.indexOf(START_ID),b=ids.indexOf(GOAL_ID);if(a<0||b<0||a===b)throw new Error('known-good sequenceのanchorを確認できません');const sign=b>a?1:-1,dense=[];for(let i=a;;i+=sign){dense.push(ids[i]);if(i===b)break}let chosen=sample(dense),mm=await meta(chosen),frames=[];for(const id of chosen){const m=mm.get(id),c=m?.computed_geometry?.coordinates;if(!Array.isArray(c))continue;const p={lat:+c[1],lng:+c[0]},rm=metrics(p);frames.push({id,lat:p.lat,lng:p.lng,routeProgress:rm.progress,routeDistance:rm.distance,isPano:!!m.is_pano})}if(frames.length<45)throw new Error('50枚のGPSメタデータを準備できません');if(frames[frames.length-1].routeProgress<frames[0].routeProgress){frames.reverse()}const direction=sign>0?'Next':'Prev',r={sequenceId:SEQ,direction,frames:frames.slice(0,TARGET),denseFrameCount:dense.length,startDistance:distance(START,frames[0]),goalDistance:distance(GOAL,frames[frames.length-1]),source:'known-good-sequence'};if(r.frames.some(f=>f.routeDistance>MAX_ROUTE_M))throw new Error('routeから50m超の画像を含みます');saveCached(r);return r}
function current(){return s.frames[s.cursor]}
function next(){return s.frames[s.cursor+1]}
function interval(){return +$('speed').value||800}
function travel(){const a=current(),b=next();if(a&&b)s.travelHeading=bearing(a,b);else if(s.cursor>0){const p=s.frames[s.cursor-1];s.travelHeading=bearing(p,a)}else s.travelHeading=null}
function pctl(values,p=.75){const a=values.filter(Number.isFinite).slice().sort((x,y)=>x-y);return a.length?a[Math.min(a.length-1,Math.max(0,Math.ceil(a.length*p)-1))]:null}
function savedLoad(){try{const v=+localStorage.getItem(LOAD_KEY);return Number.isFinite(v)&&v>=300&&v<=6000?v:2000}catch{return 2000}}
function preloadCount(load){const L=Math.max(PRELOAD_CADENCE,+load||2000),deficit=Math.max(0,1-PRELOAD_CADENCE/L),n=Math.ceil((TARGET-1)*deficit)+PRELOAD_SAFETY;return clamp(n,PRELOAD_MIN,PRELOAD_MAX)}
function preloadUI(){const target=Math.max(1,s.preloadTarget),pct=Math.min(100,100*s.preloadReady/target);$('preloadBar').style.width=`${pct}%`;$('preloadText').textContent=`先読み ${s.preloadReady}/${s.preloadTarget||'…'}枚`}
function diag(){const f=current(),rows=[['version',VERSION],['frame / step',`${Math.min(s.cursor+1,s.frames.length)} / ${s.frames.length} (success ${s.success})`],['sequenceId',s.sequenceId],['Next / Prev',s.direction],['requested cadence',fmt(interval(),0,'ms')],['actual cadence',fmt(s.lastCadence,0,'ms')],['avg cadence',fmt(avg(s.cadence),0,'ms')],['preload ready / target',`${s.preloadReady} / ${s.preloadTarget}`],['preload estimate',fmt(s.preloadEstimate,0,'ms')],['preload avg',fmt(avg(s.preloadDur),0,'ms')],['preload time',fmt(s.preloadMs,0,'ms')],['preload failures',String(s.preloadFailures)],['preload ahead',String(Math.max(0,s.preloadReady-s.cursor))],['routeProgress',Number.isFinite(s.progress)?`${(s.progress*100).toFixed(1)}%`:'—'],['routeDistance',fmt(s.routeDistance,1,'m')],['travelHeading',fmt(s.travelHeading,1,'°')],['userViewOffset',fmt(s.viewOffset,1,'°')],['currentViewHeading',fmt(s.viewHeading,1,'°')],['imageTransitionMs',fmt(s.lastTransition,0,'ms')],['avgTransitionMs',fmt(avg(s.transition),0,'ms')],['transition mode','Default (61c4)'],['cache depth','sequence 4'],['route cache',s.routeCacheHit?'HIT':'MISS'],['deadline misses',String(s.deadlineMisses)],['initialDisplayMs',fmt(s.initialMs,0,'ms')],['360 / Rectilinear',s.projection],['360 in route',`${s.frames.filter(x=>x.isPano).length}/${s.frames.length}`],['reverse events',String(s.reverse)],['regression streak',String(s.regStreak)],['view jumps',String(s.jumps)],['stopReason',s.stopReason],['frameId',f?.id||'—']];$('diagGrid').innerHTML=rows.map(([a,b])=>`<span>${a}</span><b>${b}</b>`).join('');preloadUI()}
function setMetrics(){const f=current();if(!f)return;s.progress=f.routeProgress;s.routeDistance=f.routeDistance;s.maxProgress=Number.isFinite(s.maxProgress)?Math.max(s.maxProgress,f.routeProgress):f.routeProgress;travel();if(Number.isFinite(s.viewHeading)&&Number.isFinite(s.travelHeading)){s.viewOffset=diff(s.viewHeading,s.travelHeading);s.heldOffset=s.viewOffset}diag()}
async function readBearing(){try{const b=await s.viewer.getBearing();if(Number.isFinite(b))return s.viewHeading=norm(b)}catch{}return null}
async function preserve(offset){if(!s.viewer||s.pointer||s.projection!=='360'||!Number.isFinite(s.travelHeading))return;const before=await readBearing();if(!Number.isFinite(before))return;const desired=norm(s.travelHeading+offset),d=diff(desired,before);if(Math.abs(d)<3)return;if(Math.abs(d)>45)s.jumps++;if(Math.abs(d)>75)return;let c;try{c=await s.viewer.getCenter()}catch{return}s.correcting=true;for(let i=1;i<=6;i++){if(s.pointer)break;const e=1-Math.pow(1-i/6,2),x=((+c[0]+d/360*e)%1+1)%1;s.viewer.setCenter([x,clamp(+c[1],.08,.92)]);await sleep(26)}s.correcting=false}
async function moveRetry(viewer,id,n=3){let e;for(let i=0;i<n;i++)try{return await viewer.moveTo(id)}catch(err){e=err;if(i<n-1)await sleep(250*(i+1))}throw e}
async function preloadOne(i){if(i<=0||i>=s.frames.length||s.preloaded.has(s.frames[i].id))return true;const t=performance.now();try{await moveRetry(s.preloader,s.frames[i].id,2);const dt=performance.now()-t;s.preloadDur.push(dt);s.preloaded.add(s.frames[i].id);s.preloadReady=s.preloaded.size;diag();return true}catch{s.preloadFailures++;diag();return false}}
async function preloader(){const M=window.mapillary;s.preloader=new M.Viewer({accessToken:token(),container:'mlyPreload',imageTiling:true,transitionMode:M.TransitionMode.Instantaneous,component:{cover:false,cache:{depth:CACHE_DEPTH}}});try{s.preloader.getComponent('cache').configure({depth:CACHE_DEPTH})}catch{};try{await moveRetry(s.preloader,s.frames[0].id,2);s.preloaded.add(s.frames[0].id)}catch{}s.preloadReady=s.preloaded.size}
async function preloadBefore(){const t0=performance.now();await preloader();status('0.8秒再生に必要な先読み量を測定中…');for(let i=1;i<=Math.min(PRELOAD_SAMPLE,s.frames.length-1);i++)await preloadOne(i);const measured=pctl(s.preloadDur.slice(-PRELOAD_SAMPLE),.75)||savedLoad();s.preloadEstimate=measured;try{localStorage.setItem(LOAD_KEY,String(Math.round(measured)))}catch{}s.preloadTarget=preloadCount(measured);for(let i=s.preloadReady;i<s.preloadTarget&&i<s.frames.length;i++)await preloadOne(i);s.warmIndex=Math.max(1,s.preloadTarget);s.preloadMs=performance.now()-t0;diag()}
async function warm(){if(s.warming||!s.preloader)return;s.warming=true;while(s.playing&&s.warmIndex<s.frames.length){const ahead=s.preloadReady-s.cursor;if(ahead>12){await sleep(350);continue}await preloadOne(s.warmIndex++);await sleep(80)}s.warming=false}
function reverseGuard(t){if(t.routeDistance>MAX_ROUTE_M)return`off-route-${Math.round(t.routeDistance)}m`;const behind=(s.maxProgress??current().routeProgress)-t.routeProgress;if(behind>REG_HARD){s.reverse++;return'route-progress-hard-regression'}if(behind>REG_SOFT)s.regStreak++;else s.regStreak=Math.max(0,s.regStreak-1);if(s.regStreak>=REG_STREAK){s.reverse++;return'route-progress-sustained-regression'}return null}
function log(){const f=current();s.logs.push({step:s.cursor+1,id:f?.id,routeProgress:s.progress,routeDistance:s.routeDistance,travelHeading:s.travelHeading,userViewOffset:s.viewOffset,currentViewHeading:s.viewHeading,imageTransitionMs:s.lastTransition,projection:s.projection,preloadAhead:Math.max(0,s.preloadReady-s.cursor),stopReason:s.stopReason})}
function stop(reason='user-stop'){s.playing=false;s.token++;s.stopReason=reason;$('start').disabled=false;$('stop').disabled=true;status(reason==='completed-50'?`完了: ${s.success}/${TARGET}枚`:`停止: ${reason}`);diag()}
async function moveOne(){const t=next();if(!t){stop('completed-50');return false}const g=reverseGuard(t);if(g){stop(g);return false}const run=s.token,held=s.viewOffset,t0=performance.now();try{const image=await moveRetry(s.viewer,t.id,3);if(!s.playing||run!==s.token)return false;const now=performance.now(),dt=now-t0;s.lastTransition=dt;s.transition.push(dt);if(Number.isFinite(s.lastDisplay)){s.lastCadence=now-s.lastDisplay;s.cadence.push(s.lastCadence)}s.lastDisplay=now;s.cursor++;s.success++;s.projection=String(image?.cameraType||'').toLowerCase()==='spherical'||t.isPano?'360':'Rectilinear';setMetrics();await readBearing();await preserve(s.pointer?s.heldOffset:held);setMetrics();log();return true}catch(e){stop(`moveTo-error: ${e?.message||e}`);return false}}
async function playback(){const run=++s.token;s.playing=true;s.stopReason='playing';$('start').disabled=true;$('stop').disabled=false;try{s.viewer.setTransitionMode(window.mapillary.TransitionMode.Default)}catch{}status(`${s.direction} / ${interval()}ms / Default transition / 先読み${s.preloadReady}枚`);warm();let due=performance.now()+interval();while(s.playing&&run===s.token){if(s.cursor>=TARGET-1){stop('completed-50');break}const wait=due-performance.now();if(wait>0)await sleep(wait);else if(wait<-80)s.deadlineMisses++;const scheduled=due,ok=await moveOne();if(!ok)break;due=scheduled+interval();if(due<performance.now()-interval())due=performance.now()} }
function pointer(){const el=s.viewer?.getCanvasContainer?.()||$('mly');for(const n of ['touchstart'])el.addEventListener(n,()=>s.pointer=true,{passive:true});for(const n of ['touchend','touchcancel'])el.addEventListener(n,()=>s.pointer=false,{passive:true})}
function events(){s.viewer.on('pov',async e=>{const b=await e.target.getBearing().catch(()=>null);if(!Number.isFinite(b))return;s.viewHeading=norm(b);if(Number.isFinite(s.travelHeading)&&(!s.correcting||s.pointer)){const o=diff(s.viewHeading,s.travelHeading);s.viewOffset=o;if(s.pointer||!s.playing)s.heldOffset=o}diag()});s.viewer.on('image',e=>{if(e?.image){s.projection=String(e.image.cameraType||'').toLowerCase()==='spherical'?'360':'Rectilinear';diag()}})}
async function init(r){const M=window.mapillary;if(!M?.Viewer)throw new Error('MapillaryJSを読み込めませんでした');Object.assign(s,{frames:r.frames,sequenceId:r.sequenceId,direction:r.direction,stopReason:'preloading'});s.viewer=new M.Viewer({accessToken:token(),container:'mly',imageTiling:true,transitionMode:M.TransitionMode.Default,component:{cover:false,cache:{depth:CACHE_DEPTH}}});try{s.viewer.getComponent('pointer').configure({dragPan:true,scrollZoom:false,touchZoom:true});s.viewer.getComponent('cache').configure({depth:CACHE_DEPTH})}catch{}pointer();events();const t=performance.now(),image=await moveRetry(s.viewer,s.frames[0].id,3);s.initialMs=performance.now()-t;s.success=1;s.projection=String(image?.cameraType||'').toLowerCase()==='spherical'||s.frames[0].isPano?'360':'Rectilinear';s.lastDisplay=performance.now();await readBearing();setMetrics();log();await preloadBefore();s.stopReason='ready';s.setupMs=performance.now()-s.setupStart;$('start').disabled=false;status(`${s.direction} / ${s.frames.length}枚 / 0.8秒用 ${s.preloadReady}/${s.preloadTarget}枚先読み完了`);diag()}
function text(){return JSON.stringify({test:'MapillaryJS',version:VERSION,route:'烏丸御池 -> 四条烏丸',sequenceId:s.sequenceId,direction:s.direction,targetFrames:TARGET,requestedCadenceMs:interval(),preloadCadenceMs:PRELOAD_CADENCE,preloadTargetFrames:s.preloadTarget,preloadReadyFrames:s.preloadReady,preloadEstimatedLoadMs:s.preloadEstimate,preloadAverageMs:avg(s.preloadDur),preloadMs:s.preloadMs,preloadFailures:s.preloadFailures,successfulFrames:s.success,initialDisplayMs:s.initialMs,averageImageTransitionMs:avg(s.transition),averageCadenceMs:avg(s.cadence),deadlineMisses:s.deadlineMisses,transitionMode:'Default',cacheDepth:CACHE_DEPTH,routeCacheHit:s.routeCacheHit,reverseEvents:s.reverse,regressionStreak:s.regStreak,viewJumps:s.jumps,panoFrames:s.frames.filter(f=>f.isPano).length,totalPreparedFrames:s.frames.length,stopReason:s.stopReason,setupMs:s.setupMs,frames:s.logs},null,2)}
async function copy(){const x=text();try{await navigator.clipboard.writeText(x)}catch{const t=document.createElement('textarea');t.value=x;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}status('Diagnosticsをコピーしました')}
async function boot(){if(!token()){$('tokenSheet').hidden=false;status('Mapillary Access Tokenを設定してください');return}try{await init(await route())}catch(e){s.stopReason=`setup-error: ${e?.message||e}`;status(s.stopReason);diag();$('diag').classList.add('is-open')}}
$('start').onclick=()=>{if(!s.playing)playback()};$('stop').onclick=()=>stop();$('toggleDiag').onclick=()=>{$('diag').classList.toggle('is-open');diag()};$('copyDiag').onclick=copy;$('speed').oninput=()=>{$('speedOut').value=`${(interval()/1000).toFixed(2)}s`;diag()};$('saveToken').onclick=()=>{const v=$('tokenInput').value.trim();if(v){try{localStorage.setItem(TOKEN_KEY,v)}catch{}location.reload()}};$('cancelToken').onclick=()=>location.href='/';addEventListener('pagehide',()=>{try{s.viewer?.remove()}catch{}try{s.preloader?.remove()}catch{}},{once:true});diag();boot();
})();
