(() => {
'use strict';
const DEST_KEY='streetview:phase3-destination',OVERPASS='https://overpass-api.de/api/interpreter',WIKI='https://ja.wikipedia.org/w/api.php',PAGEVIEWS='https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/ja.wikipedia.org/all-access/all-agents';
let map=null,mode='browse',selected=null,abort=null,markers=[];
const $=id=>document.getElementById(id),rad=d=>d*Math.PI/180;
function d(a,b){const R=6371000,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng),s=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(s),Math.sqrt(1-s))}
function status(t){if($('phase3Status'))$('phase3Status').textContent=t}
function clear(){while(markers.length)try{markers.pop().remove()}catch{}}
async function json(u,o={}){const r=await fetch(u,o);if(!r.ok)throw new Error(String(r.status));return r.json()}
async function osm(c,r,s){const q=`[out:json][timeout:14];(nwr(around:${Math.round(r)},${c.lat},${c.lng})[name][tourism=attraction];nwr(around:${Math.round(r)},${c.lat},${c.lng})[name][tourism=viewpoint];nwr(around:${Math.round(r)},${c.lat},${c.lng})[name][natural=peak];nwr(around:${Math.round(r)},${c.lat},${c.lng})[name][historic];);out center tags 50;`,j=await json(OVERPASS,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:'data='+encodeURIComponent(q),signal:s});return(j.elements||[]).map(e=>{const t=e.tags||{},lat=+(e.lat??e.center?.lat),lng=+(e.lon??e.center?.lon);if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;let category='landmark';if(t.natural==='peak')category='peak';else if(t.tourism==='viewpoint')category='viewpoint';else if(t.tourism==='attraction')category='attraction';return{id:`osm:${e.type}:${e.id}`,title:t['name:ja']||t.name,lat,lng,category,source:'OpenStreetMap',wikiTitle:t.wikipedia?.startsWith('ja:')?t.wikipedia.slice(3):null,views:0}}).filter(Boolean)}
async function wiki(c,r,s){const p=new URLSearchParams({origin:'*',action:'query',format:'json',generator:'geosearch',ggscoord:`${c.lat}|${c.lng}`,ggsradius:String(Math.min(10000,Math.round(r))),ggslimit:'20',prop:'coordinates|pageimages',piprop:'thumbnail',pithumbsize:'320'}),j=await json(`${WIKI}?${p}`,{signal:s});return Object.values(j?.query?.pages||{}).map(x=>{const c=x.coordinates?.[0];return c?{id:`wiki:${x.pageid}`,pageid:x.pageid,title:x.title,lat:+c.lat,lng:+c.lon,category:'landmark',source:'Wikipedia',wikiTitle:x.title,thumbnail:x.thumbnail?.source||null,views:0}:null}).filter(Boolean)}
function merge(os,wi,c){const all=[...os];for(const w of wi){let best=null,bd=180;for(const o of all){const x=d(w,o);if(x<bd){bd=x;best=o}}if(best){best.wikiTitle=best.wikiTitle||w.wikiTitle;best.thumbnail=best.thumbnail||w.thumbnail;best.views=Math.max(best.views||0,w.views||0)}else all.push(w)}for(const x of all)x.distance=d(c,x);return all.sort((a,b)=>((Math.log10(1+(b.views||0)))+(b.category==='peak'?0.35:b.category==='viewpoint'?0.3:b.category==='attraction'?0.25:0.15)-b.distance/25000)-((Math.log10(1+(a.views||0)))+(a.category==='peak'?0.35:a.category==='viewpoint'?0.3:a.category==='attraction'?0.25:0.15)-a.distance/25000)).slice(0,24)}
function icon(c){return c==='peak'?'▲':c==='viewpoint'?'◎':c==='attraction'?'★':'◆'}function label(c){return c==='peak'?'山':c==='viewpoint'?'展望地':c==='attraction'?'観光地':'名所'}
function render(items){clear();for(const p of items){const el=document.createElement('button');el.className=`phase3-poi ${p.category}`;el.type='button';el.innerHTML=`<span>${icon(p.category)}</span>`;el.addEventListener('click',e=>{e.stopPropagation();selected=p;const s=$('destinationSheet');s?.classList.add('open');$('destinationCategory').textContent=label(p.category);$('destinationTitle').textContent=p.title;$('destinationMeta').textContent=[p.source,p.views?`Wikipedia 30日 ${p.views.toLocaleString()}閲覧`:null].filter(Boolean).join(' · ');const im=$('destinationImage');if(p.thumbnail){im.src=p.thumbnail;im.hidden=false}else{im.hidden=true;im.removeAttribute('src')}});markers.push(new maplibregl.Marker({element:el,anchor:'center'}).setLngLat([p.lng,p.lat]).addTo(map))}}
function radius(){const b=map.getBounds(),c=map.getCenter();return Math.max(1500,Math.min(10000,Math.max(d({lat:c.lat,lng:c.lng},{lat:b.getNorthEast().lat,lng:b.getNorthEast().lng}),d({lat:c.lat,lng:c.lng},{lat:b.getSouthWest().lat,lng:b.getSouthWest().lng}))))}
function day(x){return`${x.getUTCFullYear()}${String(x.getUTCMonth()+1).padStart(2,'0')}${String(x.getUTCDate()).padStart(2,'0')}`}
async function views(x,s){if(!x.wikiTitle)return 0;const e=new Date(Date.now()-2*864e5),st=new Date(e.getTime()-29*864e5),a=encodeURIComponent(x.wikiTitle.replace(/ /g,'_'));try{const j=await json(`${PAGEVIEWS}/${a}/daily/${day(st)}/${day(e)}`,{signal:s});return(j.items||[]).reduce((n,z)=>n+(+z.views||0),0)}catch{return 0}}
async function load(){if(!map||mode!=='destination')return;abort?.abort();abort=new AbortController();const s=abort.signal,cc=map.getCenter(),c={lat:cc.lat,lng:cc.lng},r=radius();clear();status('名所を探しています…');let os=[],wi=[],shown=false;const refresh=()=>{if(s.aborted||mode!=='destination')return;const m=merge(os,wi,c);if(m.length){render(m);status(`${m.length}件の候補`);shown=true}};const op=osm(c,r,s).then(v=>{os=v;refresh()}).catch(()=>{}),wp=wiki(c,r,s).then(async v=>{wi=v;refresh();const top=wi.slice(0,10);let i=0;async function worker(){while(i<top.length){const x=top[i++];x.views=await views(x,s)}}await Promise.all(Array.from({length:3},worker));refresh()}).catch(()=>{});setTimeout(()=>{if(!shown&&!s.aborted)status('候補データを読み込み中…')},700);await Promise.allSettled([op,wp]);if(!shown&&!s.aborted)status('この範囲に候補がありません')}
function routes(on){for(const id of ['kartaview-coverage-layer','mapillary-sequence-glow','mapillary-sequence-line','mapillary-image-points'])try{if(map.getLayer(id))map.setLayoutProperty(id,'visibility',on?'visible':'none')}catch{}}
function close(){selected=null;$('destinationSheet')?.classList.remove('open')}
function register(){if(!selected)return;const dest={...selected,registeredAt:new Date().toISOString()};try{sessionStorage.setItem(DEST_KEY,JSON.stringify(dest))}catch{}mode='browse';clear();close();routes(true);document.body.classList.remove('phase3-destination-mode');$('phase3Start').innerHTML=`<small>到着地</small><b>${String(dest.title).replace(/[<>]/g,'')}</b>`;$('phase3Start').classList.add('has-destination');status('撮影済みルートから出発地を選択')}
function begin(){mode='destination';selected=null;routes(false);document.body.classList.add('phase3-destination-mode');$('phase3Start').classList.remove('has-destination');$('phase3Start').innerHTML='<b>到着地を選んでください</b><small>観光地・山・展望地・名所</small>';load()}
function install(){if($('phase3Start'))return;const b=document.createElement('button');b.id='phase3Start';b.className='phase3-start';b.innerHTML='<b>旅をはじめる</b><small>まず到着地を選ぶ</small>';b.addEventListener('click',()=>{if(mode==='browse')begin()});document.body.appendChild(b);const st=document.createElement('div');st.id='phase3Status';st.className='phase3-status';document.body.appendChild(st);const sh=document.createElement('section');sh.id='destinationSheet';sh.className='destination-sheet';sh.innerHTML='<button id="destinationBackdrop" class="destination-backdrop" type="button"></button><div class="destination-card"><div class="destination-handle"></div><div class="destination-body"><img id="destinationImage" hidden alt=""><div><span id="destinationCategory">名所</span><h2 id="destinationTitle">目的地</h2><p id="destinationMeta"></p></div></div><button id="registerDestination" class="destination-primary" type="button">到着地登録</button><button id="cancelDestination" class="destination-secondary" type="button">戻る</button></div>';document.body.appendChild(sh);$('destinationBackdrop').onclick=close;$('cancelDestination').onclick=close;$('registerDestination').onclick=register}
function attach(m){if(map===m)return;map=m;install();map.on('moveend',()=>{if(mode==='destination')load()});if(mode==='destination')load()}
const t=setInterval(()=>{if(window.__streetviewCoverageMap){clearInterval(t);attach(window.__streetviewCoverageMap)}},60);setTimeout(()=>clearInterval(t),15000);
})();