(() => {
'use strict';
const TOKEN_KEY='streetview:mapillary-token',DEST_KEY='streetview:phase3-destination',ROUTE_KEY='streetview:journey-route',GRAPH='https://graph.mapillary.com';
const MLY_SOURCE='mapillary-coverage',MLY_LINE='mapillary-sequence-line',MLY_IMAGE='mapillary-image-points';
const ROUTE_SOURCE='selected-journey-route',ROUTE_GLOW='selected-journey-route-glow',ROUTE_LINE='selected-journey-route-line';
const CONNECT_METERS=115,MAX_HOPS=18,INITIAL_READY=32;
let map=null,busy=false,startMarker=null,endMarker=null,lastPinnedKey='';
const $=id=>document.getElementById(id),rad=d=>d*Math.PI/180;
function token(){try{return localStorage.getItem(TOKEN_KEY)||''}catch{return''}}
function destination(){try{const x=JSON.parse(sessionStorage.getItem(DEST_KEY)||'null');return x&&Number.isFinite(+x.lat)&&Number.isFinite(+x.lng)?{...x,lat:+x.lat,lng:+x.lng}:null}catch{return null}}
function dist(a,b){const p1=rad(+a.lat),p2=rad(+b.lat),dp=rad(+b.lat-+a.lat),dl=rad(+b.lng-+a.lng),s=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 12742000*Math.atan2(Math.sqrt(s),Math.sqrt(Math.max(0,1-s)))}
function bearing(a,b){const p1=rad(+a.lat),p2=rad(+b.lat),dl=rad(+b.lng-+a.lng),y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function adiff(a,b){return Math.abs(((b-a+540)%360)-180)}
function fid(f){return String(f?.properties?.id??f?.properties?.sequence_id??f?.properties?.image_id??f?.id??'').trim()}
async function api(path){const t=token();if(!t)throw new Error('Mapillary Access Tokenが未設定です');const r=await fetch(`${GRAPH}${path}`,{headers:{Authorization:`OAuth ${t}`}}),j=await r.json().catch(()=>({}));if(!r.ok||j?.error)throw new Error(j?.error?.message||`Mapillary API ${r.status}`);return j}
async function imageMeta(id){return api(`/${encodeURIComponent(id)}?fields=id,sequence,captured_at,computed_geometry,compass_angle,thumb_2048_url,is_pano`)}
async function imageIds(seq){const j=await api(`/image_ids?sequence_id=${encodeURIComponent(seq)}`);return(j?.data||[]).map(x=>String(x?.id??x)).filter(Boolean)}
async function pmap(items,limit,fn){const out=new Array(items.length);let n=0;async function w(){for(;;){const i=n++;if(i>=items.length)return;try{out[i]=await fn(items[i],i)}catch{out[i]=null}}}await Promise.all(Array.from({length:Math.min(limit,items.length||1)},w));return out}
function frame(m,seq,i){const c=m?.computed_geometry?.coordinates;if(!Array.isArray(c)||c.length<2||!m?.thumb_2048_url)return null;return{id:String(m.id),sequenceId:String(seq),sequenceIndex:i,lat:+c[1],lng:+c[0],heading:Number.isFinite(+m.compass_angle)?+m.compass_angle:null,projection:m.is_pano?'SPHERE':'RECTILINEAR',fieldOfView:m.is_pano?360:100,url:m.thumb_2048_url,provider:'Mapillary',capturedAt:m.captured_at||null}}
function coordsOf(g){if(!g)return[];if(g.type==='LineString')return g.coordinates||[];if(g.type==='MultiLineString')return(g.coordinates||[]).flat();return[]}
function point(c){return{lng:+c[0],lat:+c[1]}}
function sample(cs,max=42){if(cs.length<=max)return cs;const step=Math.max(1,Math.ceil(cs.length/max)),out=[];for(let i=0;i<cs.length;i+=step)out.push(cs[i]);out.push(cs[cs.length-1]);return out}
function featureMap(features){const m=new Map();for(const f of features){const id=fid(f),cs=coordsOf(f.geometry);if(!id||cs.length<2)continue;if(!m.has(id))m.set(id,{id,coords:[]});m.get(id).coords.push(...cs)}for(const n of m.values())n.coords=sample(n.coords);return m}
function nearestCoord(cs,p){let index=0,distance=Infinity;for(let i=0;i<cs.length;i++){const d=dist(point(cs[i]),p);if(d<distance){distance=d;index=i}}return{index,distance}}
function forwardNode(node,current,dest){const cs=node.coords,near=nearestCoord(cs,current),i=near.index;if(i>=cs.length-1)return null;const part=cs.slice(i),entry=point(part[0]),exit=point(part[part.length-1]),next=point(part[Math.min(2,part.length-1)]),goal=bearing(current,dest),headingError=adiff(goal,bearing(current,next));return{id:node.id,coords:part,entry,exit,connector:near.distance,destDistance:dist(exit,dest),headingError}}
function pickNext(nodes,visited,current,dest,currentDest){let best=null,bestScore=Infinity;for(const n of nodes.values()){if(visited.has(n.id))continue;const o=forwardNode(n,current,dest);if(!o||o.connector>CONNECT_METERS)continue;const improvement=currentDest-o.destDistance;if(improvement<-40||o.headingError>125)continue;const score=o.destDistance+o.connector*2.4+o.headingError*15-Math.max(0,improvement)*.4;if(score<bestScore){bestScore=score;best={...o,improvement}}}return best}
function greedyRoute(nodes,startSeq,startPoint,dest){const visited=new Set(),plans=[],routeCoords=[];let current=startPoint,id=startSeq;for(let hop=0;hop<MAX_HOPS&&id;hop++){const n=nodes.get(id);if(!n)break;const o=forwardNode(n,current,dest);if(!o)break;visited.add(id);plans.push({sequenceId:id,entry:o.entry,exit:o.exit,headingError:o.headingError});routeCoords.push(...o.coords);current=o.exit;const currentDest=dist(current,dest);if(currentDest<=140)break;const next=pickNext(nodes,visited,current,dest,currentDest);if(!next||next.improvement<8)break;id=next.id}return{plans,routeCoords,destinationDistance:dist(current,dest)}}
function removeMarker(m){try{m?.remove()}catch{}return null}
function pin(label,kind,lnglat){const el=document.createElement('div');el.className=`phase4-route-pin ${kind}`;el.textContent=label;return new maplibregl.Marker({element:el,anchor:'center'}).setLngLat(lnglat).addTo(map)}
function setPins(start,dest){const key=`${(+start.lng).toFixed(5)},${(+start.lat).toFixed(5)}:${(+dest.lng).toFixed(5)},${(+dest.lat).toFixed(5)}`;if(key===lastPinnedKey)return;lastPinnedKey=key;startMarker=removeMarker(startMarker);endMarker=removeMarker(endMarker);startMarker=pin('出','start',[+start.lng,+start.lat]);endMarker=pin('着','end',[+dest.lng,+dest.lat])}
function hideCoverage(){for(const id of ['kartaview-coverage-layer','mapillary-sequence-glow','mapillary-sequence-line','mapillary-image-points'])try{if(map.getLayer(id))map.setLayoutProperty(id,'visibility','none')}catch{}}
function showRoute(coords,start,dest){if(coords.length<2)return;const data={type:'Feature',properties:{provider:'Mapillary'},geometry:{type:'LineString',coordinates:coords}},src=map.getSource(ROUTE_SOURCE);if(src?.setData)src.setData(data);else{try{if(map.getLayer(ROUTE_LINE))map.removeLayer(ROUTE_LINE);if(map.getLayer(ROUTE_GLOW))map.removeLayer(ROUTE_GLOW);if(map.getSource(ROUTE_SOURCE))map.removeSource(ROUTE_SOURCE)}catch{}map.addSource(ROUTE_SOURCE,{type:'geojson',data});map.addLayer({id:ROUTE_GLOW,type:'line',source:ROUTE_SOURCE,paint:{'line-color':'#58ff93','line-width':12,'line-opacity':.28,'line-blur':4}});map.addLayer({id:ROUTE_LINE,type:'line',source:ROUTE_SOURCE,paint:{'line-color':'#58ff93','line-width':4.5,'line-opacity':1}})}hideCoverage();setPins(start,dest)}
function ensureCandidate(){return $('journeyCandidate')&&$('candidateTitle')&&$('candidateText')}
function openLoading(){if(!ensureCandidate())return;const c=$('journeyCandidate');c.classList.add('is-open','is-loading');document.querySelector('.provider-panel')?.classList.add('has-candidate');$('candidateKicker').textContent='MAPILLARY JOURNEY ROUTE';$('candidateKicker').classList.add('mapillary');$('candidateTitle').textContent='撮影ルートを検索中';$('candidateText').classList.remove('jc-error');$('candidateText').textContent='撮影方向を保ったまま、到着地へ近づくsequenceを探している。';$('candidateStats').hidden=true;$('candidateActions').hidden=true}
function setupCard(payload){const path=payload.sequenceIds,dd=payload.selection.destinationDistanceMeters,c=$('journeyCandidate');c.classList.remove('is-loading');$('candidateTitle').textContent=path.length>1?`${path.length} sequencesを接続`:`Sequence ${path[0]}`;$('candidateText').textContent=`撮影方向を維持して接続。到着地まで残り ${dd<1000?Math.round(dd)+'m':(dd/1000).toFixed(1)+'km'}。`;$('candidateStats').hidden=false;$('candidateStats').innerHTML=`<div class="jc-stat"><small>Provider</small><b>Mapillary</b></div><div class="jc-stat"><small>準備済み</small><b id="streamReadyCount">0枚</b></div><div class="jc-stat"><small>接続sequence</small><b>${path.length}本</b></div>`;$('candidateActions').hidden=false;const old=$('candidateStart'),btn=old.cloneNode(true);old.replaceWith(btn);btn.disabled=true;btn.textContent='先頭画像を準備中…';btn.addEventListener('click',()=>{if(btn.disabled)return;try{payload.streamOpen=payload.streamPending.length>0;sessionStorage.setItem(ROUTE_KEY,JSON.stringify(payload));location.href='/journey-map.html?autostart=1'}catch{}});payload._button=btn}
function updateReady(payload){const n=payload.frames.length,total=payload.selection.totalImageIds||n,el=$('streamReadyCount');if(el)el.textContent=`${n} / ${total}枚`;if(payload._button&&n>=Math.min(INITIAL_READY,total)){payload._button.disabled=false;payload._button.textContent='このルートでJourney開始'}}
function renderError(msg){if(!ensureCandidate())return;$('journeyCandidate').classList.remove('is-loading');$('candidateTitle').textContent='撮影ルートを接続できなかった';$('candidateText').classList.add('jc-error');$('candidateText').textContent=msg;$('candidateStats').hidden=true;$('candidateActions').hidden=true}
async function buildRefs(plans,anchorImageId){const lists=await pmap(plans,8,async plan=>{let ids=await imageIds(plan.sequenceId);if(plan===plans[0]&&anchorImageId){const i=ids.indexOf(String(anchorImageId));if(i>=0)ids=ids.slice(i)}return ids.map((id,i)=>({id,sequenceId:plan.sequenceId,sequenceIndex:i}))});return lists.filter(Boolean).flat()}
async function refsToFrames(refs){const meta=await pmap(refs,16,r=>imageMeta(r.id));return meta.map((m,i)=>frame(m,refs[i].sequenceId,refs[i].sequenceIndex)).filter(Boolean)}
async function waitTiles(){for(let i=0;i<6;i++){let fs=[];try{fs=map.querySourceFeatures(MLY_SOURCE,{sourceLayer:'sequence'})||[]}catch{}if(fs.length>8)return fs;await new Promise(r=>setTimeout(r,90))}try{return map.querySourceFeatures(MLY_SOURCE,{sourceLayer:'sequence'})||[]}catch{return[]}}
async function handle(feature,ll,anchorImageId=null){if(busy)return;const dest=destination();if(!dest||!token())return;busy=true;openLoading();try{let startSeq=fid(feature);if(feature?.layer?.id===MLY_IMAGE){anchorImageId=fid(feature);const m=await imageMeta(anchorImageId);startSeq=String(m?.sequence?.id??m?.sequence??'')}if(!startSeq)throw new Error('開始sequenceを特定できませんでした');const b=new maplibregl.LngLatBounds([ll.lng,ll.lat],[ll.lng,ll.lat]);b.extend([dest.lng,dest.lat]);map.fitBounds(b,{padding:70,maxZoom:13,duration:0});const features=await waitTiles(),nodes=featureMap(features);if(!nodes.has(startSeq)){const cs=coordsOf(feature.geometry);nodes.set(startSeq,{id:startSeq,coords:cs.length?sample(cs):[[ll.lng,ll.lat],[ll.lng,ll.lat]]})}const route=greedyRoute(nodes,startSeq,{lat:ll.lat,lng:ll.lng},dest);if(!route.plans.length)throw new Error('撮影方向を保って到着地へ進めるsequenceが見つかりません');showRoute(route.routeCoords,{lat:ll.lat,lng:ll.lng},dest);const payload={version:'0.4.4-forward-stream',source:'Mapillary',provider:'Mapillary',sequenceId:route.plans.map(x=>x.sequenceId).join('→'),sequenceIds:route.plans.map(x=>x.sequenceId),frames:[],destination:dest,streamOpen:true,streamPending:[],selection:{strategy:'mapillary-forward-greedy-stream',destinationDistanceMeters:route.destinationDistance,candidateCount:route.plans.length,totalImageIds:0,maxHeadingErrorDeg:Math.max(...route.plans.map(x=>x.headingError||0))}};setupCard(payload);const refs=await buildRefs(route.plans,anchorImageId);if(refs.length<2)throw new Error('再生できるMapillary画像が不足しています');payload.selection.totalImageIds=refs.length;const first=refs.slice(0,Math.min(INITIAL_READY,refs.length));payload.streamPending=refs.slice(first.length);payload.frames.push(...await refsToFrames(first));updateReady(payload)}catch(e){renderError(e?.message||'Mapillaryルート接続に失敗しました')}finally{busy=false}}
function domPoint(e){const r=map.getCanvas().getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function captureClick(e){const dest=destination();if(!dest||!token()||busy)return;const p=domPoint(e);let fs=[];try{fs=map.queryRenderedFeatures(p,{layers:[MLY_IMAGE,MLY_LINE]})||[]}catch{}if(!fs[0])return;e.preventDefault();e.stopImmediatePropagation();let feature=fs[0],anchor=null;if(feature.layer?.id!==MLY_IMAGE){try{const ims=map.queryRenderedFeatures([[p.x-22,p.y-22],[p.x+22,p.y+22]],{layers:[MLY_IMAGE]})||[];if(ims[0])anchor=fid(ims[0])}catch{}}const ll=map.unproject(p);handle(feature,ll,anchor)}
function attach(m){if(map===m)return;map=m;const style=document.createElement('style');style.textContent='.phase4-route-pin{width:38px;height:38px;border-radius:999px;display:grid;place-items:center;border:3px solid #fff;box-shadow:0 5px 20px rgba(0,0,0,.38);font-size:12px;font-weight:900;color:#fff;z-index:30}.phase4-route-pin.start{background:#111827}.phase4-route-pin.end{background:#ef4444}';document.head.appendChild(style);map.getCanvas().addEventListener('click',captureClick,true)}
const timer=setInterval(()=>{if(window.__streetviewCoverageMap){clearInterval(timer);attach(window.__streetviewCoverageMap)}},60);setTimeout(()=>clearInterval(timer),15000);
})();