(() => {
'use strict';
const TOKEN_KEY='streetview:mapillary-token',DEST_KEY='streetview:phase3-destination',ROUTE_KEY='streetview:journey-route',GRAPH='https://graph.mapillary.com';
const MLY_SOURCE='mapillary-coverage',MLY_LINE='mapillary-sequence-line',MLY_IMAGE='mapillary-image-points';
const ROUTE_SOURCE='selected-journey-route',ROUTE_GLOW='selected-journey-route-glow',ROUTE_LINE='selected-journey-route-line';
const CONNECT_METERS=90,MAX_HOPS=24;
let map=null,busy=false,startMarker=null,endMarker=null,lastPinnedKey='';
const $=id=>document.getElementById(id);
function token(){try{return localStorage.getItem(TOKEN_KEY)||''}catch{return''}}
function destination(){try{const x=JSON.parse(sessionStorage.getItem(DEST_KEY)||'null');return x&&Number.isFinite(+x.lat)&&Number.isFinite(+x.lng)?{...x,lat:+x.lat,lng:+x.lng}:null}catch{return null}}
function dist(a,b){const r=Math.PI/180,p1=a.lat*r,p2=b.lat*r,dp=(b.lat-a.lat)*r,dl=(b.lng-a.lng)*r,s=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 12742000*Math.atan2(Math.sqrt(s),Math.sqrt(Math.max(0,1-s)))}
function fid(f){return String(f?.properties?.id??f?.properties?.sequence_id??f?.properties?.image_id??f?.id??'').trim()}
async function api(path){const t=token();if(!t)throw new Error('Mapillary Access Tokenが未設定です');const r=await fetch(`${GRAPH}${path}`,{headers:{Authorization:`OAuth ${t}`}}),j=await r.json().catch(()=>({}));if(!r.ok||j?.error)throw new Error(j?.error?.message||`Mapillary API ${r.status}`);return j}
async function imageMeta(id){return api(`/${encodeURIComponent(id)}?fields=id,sequence,captured_at,computed_geometry,compass_angle,thumb_2048_url,is_pano`)}
async function pmap(items,limit,fn){const out=new Array(items.length);let n=0;async function worker(){for(;;){const i=n++;if(i>=items.length)return;try{out[i]=await fn(items[i],i)}catch{out[i]=null}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
function frame(m,seq,i){const c=m?.computed_geometry?.coordinates;if(!Array.isArray(c)||c.length<2||!m?.thumb_2048_url)return null;return{id:String(m.id),sequenceId:String(seq),sequenceIndex:i,lat:+c[1],lng:+c[0],heading:Number.isFinite(+m.compass_angle)?+m.compass_angle:null,projection:m.is_pano?'SPHERE':'RECTILINEAR',fieldOfView:m.is_pano?360:100,url:m.thumb_2048_url,provider:'Mapillary',capturedAt:m.captured_at||null}}
async function seqFrames(id){const d=await api(`/image_ids?sequence_id=${encodeURIComponent(id)}`),ids=(d?.data||[]).map(x=>String(x?.id??x)).filter(Boolean);if(ids.length<2)return[];const meta=await pmap(ids,8,imageMeta);return meta.map((m,i)=>frame(m,id,i)).filter(Boolean)}
function coordsOf(g){if(!g)return[];if(g.type==='LineString')return g.coordinates||[];if(g.type==='MultiLineString')return(g.coordinates||[]).flat();return[]}
function cobj(c){return{lng:+c[0],lat:+c[1]}}
function sampleCoords(cs){if(cs.length<=36)return cs;const step=Math.max(1,Math.floor(cs.length/30)),out=[];for(let i=0;i<cs.length;i+=step)out.push(cs[i]);out.push(cs[cs.length-1]);return out}
function buildNodes(features){const nodes=new Map();for(const f of features){const id=fid(f),cs=coordsOf(f.geometry);if(!id||cs.length<2)continue;let n=nodes.get(id);if(!n){n={id,points:[],ends:[]};nodes.set(id,n)}const samp=sampleCoords(cs);n.points.push(...samp);n.ends.push(cs[0],cs[cs.length-1]);}return nodes}
function projected(c,cos){return{x:+c[0]*111320*cos,y:+c[1]*111320}}
function buildAdj(nodes,midLat){const cos=Math.max(.2,Math.cos(midLat*Math.PI/180)),cell=CONNECT_METERS,grid=new Map(),adj=new Map([...nodes.keys()].map(id=>[id,new Set()]));const key=(x,y)=>`${Math.floor(x/cell)}:${Math.floor(y/cell)}`;for(const n of nodes.values())for(const c of n.points){const p=projected(c,cos),k=key(p.x,p.y);if(!grid.has(k))grid.set(k,[]);grid.get(k).push({id:n.id,p});}for(const items of grid.values())for(const a of items){const cx=Math.floor(a.p.x/cell),cy=Math.floor(a.p.y/cell);for(let dx=-1;dx<=1;dx++)for(let dy=-1;dy<=1;dy++){const near=grid.get(`${cx+dx}:${cy+dy}`)||[];for(const b of near){if(a.id===b.id)continue;const dd=Math.hypot(a.p.x-b.p.x,a.p.y-b.p.y);if(dd<=CONNECT_METERS){adj.get(a.id)?.add(b.id);adj.get(b.id)?.add(a.id);}}}}return adj}
function nodeDest(n,d){let best=Infinity;for(const c of n.points)best=Math.min(best,dist(cobj(c),d));return best}
function buildPath(nodes,adj,startId,dest){if(!nodes.has(startId))return[startId];const q=[startId],prev=new Map([[startId,null]]),depth=new Map([[startId,0]]);let best=startId,bestD=nodeDest(nodes.get(startId),dest);while(q.length){const id=q.shift(),dep=depth.get(id)||0,dd=nodeDest(nodes.get(id),dest);if(dd<bestD){best=id;bestD=dd}if(dep>=MAX_HOPS)continue;const next=[...(adj.get(id)||[])].sort((a,b)=>nodeDest(nodes.get(a),dest)-nodeDest(nodes.get(b),dest));for(const to of next){if(prev.has(to))continue;prev.set(to,id);depth.set(to,dep+1);q.push(to)}}const path=[];for(let x=best;x;x=prev.get(x))path.push(x);return path.reverse()}
function nearestIndex(frames,p){let bi=0,bd=Infinity;for(let i=0;i<frames.length;i++){const dd=dist(frames[i],p);if(dd<bd){bd=dd;bi=i}}return{index:bi,distance:bd}}
function nearestNodeIndex(frames,node){let bi=frames.length-1,bd=Infinity;for(let i=0;i<frames.length;i++)for(const c of node.points){const dd=dist(frames[i],cobj(c));if(dd<bd){bd=dd;bi=i}}return{index:bi,distance:bd}}
async function stitch(path,startPoint,dest,anchorImageId,nodes){const all=[];let prev=startPoint;for(let s=0;s<path.length;s++){const id=path[s],fs=await seqFrames(id);if(fs.length<2)continue;let from=s===0&&anchorImageId?fs.findIndex(f=>f.id===String(anchorImageId)):-1;if(from<0)from=nearestIndex(fs,prev).index;const to=s===path.length-1?nearestIndex(fs,dest).index:nearestNodeIndex(fs,nodes.get(path[s+1])).index;let part=to>=from?fs.slice(from,to+1):fs.slice(to,from+1).reverse();if(part.length<2)part=fs;if(all.length&&part.length&&all[all.length-1].id===part[0].id)part.shift();all.push(...part);prev=all[all.length-1]||prev;}return all}
function removeMarker(m){try{m?.remove()}catch{}return null}
function pin(label,kind,lnglat){const el=document.createElement('div');el.className=`phase4-route-pin ${kind}`;el.textContent=label;return new maplibregl.Marker({element:el,anchor:'center'}).setLngLat(lnglat).addTo(map)}
function setPins(start,dest){if(!map||!start||!dest)return;const key=`${(+start.lng).toFixed(6)},${(+start.lat).toFixed(6)}:${(+dest.lng).toFixed(6)},${(+dest.lat).toFixed(6)}`;if(key===lastPinnedKey)return;lastPinnedKey=key;startMarker=removeMarker(startMarker);endMarker=removeMarker(endMarker);startMarker=pin('出','start',[+start.lng,+start.lat]);endMarker=pin('着','end',[+dest.lng,+dest.lat])}
function routeGeo(frames){return{type:'Feature',properties:{provider:'Mapillary'},geometry:{type:'LineString',coordinates:frames.map(f=>[+f.lng,+f.lat]).filter(c=>Number.isFinite(c[0])&&Number.isFinite(c[1]))}}}
function hideCoverage(){for(const id of ['kartaview-coverage-layer','mapillary-sequence-glow','mapillary-sequence-line','mapillary-image-points'])try{if(map.getLayer(id))map.setLayoutProperty(id,'visibility','none')}catch{}}
function showRoute(frames,dest){if(!map||frames.length<2)return;const data=routeGeo(frames),src=map.getSource(ROUTE_SOURCE);if(src?.setData)src.setData(data);else{try{if(map.getLayer(ROUTE_LINE))map.removeLayer(ROUTE_LINE);if(map.getLayer(ROUTE_GLOW))map.removeLayer(ROUTE_GLOW);if(map.getSource(ROUTE_SOURCE))map.removeSource(ROUTE_SOURCE)}catch{}map.addSource(ROUTE_SOURCE,{type:'geojson',data});map.addLayer({id:ROUTE_GLOW,type:'line',source:ROUTE_SOURCE,paint:{'line-color':'#58ff93','line-width':12,'line-opacity':.28,'line-blur':4}});map.addLayer({id:ROUTE_LINE,type:'line',source:ROUTE_SOURCE,paint:{'line-color':'#58ff93','line-width':4.5,'line-opacity':1}})}hideCoverage();setPins(frames[0],dest);const b=new maplibregl.LngLatBounds();for(const f of frames)b.extend([f.lng,f.lat]);b.extend([dest.lng,dest.lat]);try{map.fitBounds(b,{padding:{top:120,right:55,bottom:350,left:55},maxZoom:16,duration:500})}catch{}}
function ensureCandidate(){return $('journeyCandidate')&&$('candidateTitle')&&$('candidateText')}
function openLoading(){if(!ensureCandidate())return;const c=$('journeyCandidate');c.classList.add('is-open','is-loading');document.querySelector('.provider-panel')?.classList.add('has-candidate');$('candidateKicker').textContent='MAPILLARY JOURNEY ROUTE';$('candidateKicker').classList.add('mapillary');$('candidateTitle').textContent='到着地まで撮影ルートを接続中';$('candidateText').classList.remove('jc-error');$('candidateText').textContent='短いsequenceを接続して、到着地に最も近い撮影地点を探している。';$('candidateStats').hidden=true;$('candidateActions').hidden=true}
function render(payload,path,destDist){if(!ensureCandidate())return;const c=$('journeyCandidate');c.classList.remove('is-loading');$('candidateTitle').textContent=path.length>1?`${path.length} sequencesを接続`:`Sequence ${path[0]}`;$('candidateText').textContent=`出発地点から到達可能なMapillary撮影区間を接続。到着地まで残り ${destDist<1000?Math.round(destDist)+'m':(destDist/1000).toFixed(1)+'km'}。`;$('candidateStats').hidden=false;$('candidateStats').innerHTML=`<div class="jc-stat"><small>Provider</small><b>Mapillary</b></div><div class="jc-stat"><small>区間内画像</small><b>${payload.frames.length}枚</b></div><div class="jc-stat"><small>接続sequence</small><b>${path.length}本</b></div>`;$('candidateActions').hidden=false;const old=$('candidateStart'),btn=old.cloneNode(true);old.replaceWith(btn);btn.addEventListener('click',()=>{try{sessionStorage.setItem(ROUTE_KEY,JSON.stringify(payload));location.href='/journey-map.html?autostart=1'}catch{}});showRoute(payload.frames,payload.destination)}
function renderError(msg){if(!ensureCandidate())return;$('journeyCandidate').classList.remove('is-loading');$('candidateTitle').textContent='撮影ルートを接続できなかった';$('candidateText').classList.add('jc-error');$('candidateText').textContent=msg;$('candidateStats').hidden=true;$('candidateActions').hidden=true}
async function handle(feature,ll){if(busy)return;const dest=destination();if(!dest||!token())return;busy=true;openLoading();try{let id=fid(feature),anchorImageId=null,startSeq=id;if(feature?.layer?.id===MLY_IMAGE){anchorImageId=id;const m=await imageMeta(id);startSeq=String(m?.sequence?.id??m?.sequence??'')}if(!startSeq)throw new Error('開始sequenceを特定できませんでした');const bounds=new maplibregl.LngLatBounds([ll.lng,ll.lat],[ll.lng,ll.lat]);bounds.extend([dest.lng,dest.lat]);map.fitBounds(bounds,{padding:80,maxZoom:13,duration:300});await Promise.race([new Promise(r=>map.once('idle',r)),new Promise(r=>setTimeout(r,1600))]);let features=[];try{features=map.querySourceFeatures(MLY_SOURCE,{sourceLayer:'sequence'})||[]}catch{}const nodes=buildNodes(features);if(!nodes.has(startSeq)){const cs=coordsOf(feature.geometry);nodes.set(startSeq,{id:startSeq,points:cs.length?sampleCoords(cs):[[ll.lng,ll.lat]],ends:cs.length?[cs[0],cs[cs.length-1]]:[[ll.lng,ll.lat],[ll.lng,ll.lat]]})}const adj=buildAdj(nodes,(ll.lat+dest.lat)/2),path=buildPath(nodes,adj,startSeq,dest).slice(0,MAX_HOPS+1),frames=await stitch(path,{lat:ll.lat,lng:ll.lng},dest,anchorImageId,nodes);if(frames.length<2)throw new Error('接続できるMapillary画像が不足しています');const dd=dist(frames[frames.length-1],dest),payload={version:'0.4.1-connected',source:'Mapillary',provider:'Mapillary',sequenceId:path.join('→'),sequenceIds:path,frames,destination:dest,selection:{strategy:'mapillary-multi-sequence-connect',destinationDistanceMeters:dd,candidateCount:path.length}};render(payload,path,dd)}catch(e){renderError(e?.message||'Mapillaryルート接続に失敗しました')}finally{busy=false}}
function pointFromDom(e){const r=map.getCanvas().getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function captureClick(e){const dest=destination();if(!dest||!token()||busy)return;let fs=[];try{fs=map.queryRenderedFeatures(pointFromDom(e),{layers:[MLY_IMAGE,MLY_LINE]})||[]}catch{}if(!fs[0])return;e.preventDefault();e.stopImmediatePropagation();const ll=map.unproject(pointFromDom(e));handle(fs[0],ll)}
function syncPinsFromGeoJson(){const dest=destination();if(!dest||!map)return;let features=[];try{features=map.querySourceFeatures(ROUTE_SOURCE)||[]}catch{}const cs=features[0]?.geometry?.coordinates;if(Array.isArray(cs)&&cs.length>1&&Array.isArray(cs[0]))setPins({lng:+cs[0][0],lat:+cs[0][1]},dest);else{const src=map.getSource(ROUTE_SOURCE),data=src?._data||src?._options?.data,raw=data?.geometry?.coordinates;if(Array.isArray(raw)&&raw.length>1)setPins({lng:+raw[0][0],lat:+raw[0][1]},dest)}}
function attach(m){if(map===m)return;map=m;const style=document.createElement('style');style.textContent='.phase4-route-pin{width:38px;height:38px;border-radius:999px;display:grid;place-items:center;border:3px solid #fff;box-shadow:0 5px 20px rgba(0,0,0,.38);font-size:12px;font-weight:900;color:#fff;z-index:30}.phase4-route-pin.start{background:#111827}.phase4-route-pin.end{background:#ef4444}';document.head.appendChild(style);map.getCanvas().addEventListener('click',captureClick,true);const card=$('journeyCandidate');if(card)new MutationObserver(()=>setTimeout(syncPinsFromGeoJson,100)).observe(card,{attributes:true,attributeFilter:['class']});map.on('render',()=>{if($('journeyCandidate')?.classList.contains('is-open'))syncPinsFromGeoJson()})}
const timer=setInterval(()=>{const m=window.__streetviewCoverageMap;if(m){clearInterval(timer);attach(m)}},60);setTimeout(()=>clearInterval(timer),15000);
})();