(() => {
  'use strict';
  const DEST_KEY='streetview:phase3-destination';
  const OVERPASS='https://overpass-api.de/api/interpreter';
  const WIKI='https://ja.wikipedia.org/w/api.php';
  const PAGEVIEWS='https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/ja.wikipedia.org/all-access/all-agents';
  const ROUTE_LAYERS=['kartaview-coverage-layer','mapillary-sequence-glow','mapillary-sequence-line','mapillary-image-points'];
  const markers=[];
  let map=null, mode='browse', selected=null, destination=null, loadAbort=null;
  const $=id=>document.getElementById(id);
  const rad=d=>d*Math.PI/180;
  function distance(a,b){const R=6371000,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng),s=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(s),Math.sqrt(1-s));}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function catLabel(c){return c==='peak'?'山':c==='viewpoint'?'展望地':c==='attraction'?'観光地':'名所';}
  function catIcon(c){return c==='peak'?'▲':c==='viewpoint'?'◎':c==='attraction'?'★':'◆';}
  function setRoutes(on){if(!map)return;for(const id of ROUTE_LAYERS){try{if(map.getLayer(id))map.setLayoutProperty(id,'visibility',on?'visible':'none');}catch{}}}
  function clearMarkers(){while(markers.length){try{markers.pop().remove();}catch{}}}
  function setStatus(text){const el=$('phase3Status');if(el)el.textContent=text;}
  function todayKey(d){return `${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}`;}
  function viewRange(){const end=new Date(Date.now()-2*864e5),start=new Date(end.getTime()-29*864e5);return [todayKey(start),todayKey(end)];}
  async function fetchJson(url,opts={}){const r=await fetch(url,opts);if(!r.ok)throw new Error(`${r.status}`);return r.json();}
  async function overpass(center,radius,signal){const q=`[out:json][timeout:20];(nwr(around:${Math.round(radius)},${center.lat},${center.lng})[name][tourism=attraction];nwr(around:${Math.round(radius)},${center.lat},${center.lng})[name][tourism=viewpoint];nwr(around:${Math.round(radius)},${center.lat},${center.lng})[name][natural=peak];nwr(around:${Math.round(radius)},${center.lat},${center.lng})[name][historic];);out center tags 60;`;const body='data='+encodeURIComponent(q);const j=await fetchJson(OVERPASS,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body,signal});return (j.elements||[]).map(e=>{const t=e.tags||{},lat=Number(e.lat??e.center?.lat),lng=Number(e.lon??e.center?.lon);if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;let category='landmark';if(t.natural==='peak')category='peak';else if(t.tourism==='viewpoint')category='viewpoint';else if(t.tourism==='attraction')category='attraction';return{id:`osm:${e.type}:${e.id}`,title:t['name:ja']||t.name,lat,lng,category,source:'OpenStreetMap',wikiTitle:t.wikipedia?.startsWith('ja:')?t.wikipedia.slice(3):null,views:0};}).filter(Boolean);}
  async function wikiGeo(center,radius,signal){const p=new URLSearchParams({origin:'*',action:'query',format:'json',generator:'geosearch',ggscoord:`${center.lat}|${center.lng}`,ggsradius:String(Math.min(10000,Math.round(radius))),ggslimit:'20',prop:'coordinates|pageimages',piprop:'thumbnail',pithumbsize:'320'});const j=await fetchJson(`${WIKI}?${p}`,{signal});return Object.values(j?.query?.pages||{}).map(x=>{const c=x.coordinates?.[0];if(!c)return null;return{id:`wiki:${x.pageid}`,pageid:x.pageid,title:x.title,lat:Number(c.lat),lng:Number(c.lon),category:'landmark',source:'Wikipedia',wikiTitle:x.title,thumbnail:x.thumbnail?.source||null,views:0};}).filter(Boolean);}
  async function pageViews(title,signal){const [start,end]=viewRange(),article=encodeURIComponent(String(title).replace(/ /g,'_'));try{const j=await fetchJson(`${PAGEVIEWS}/${article}/daily/${start}/${end}`,{signal});return (j.items||[]).reduce((s,x)=>s+(Number(x.views)||0),0);}catch{return 0;}}
  async function enrichViews(items,signal){let i=0;async function worker(){while(i<items.length){const at=i++,x=items[at];if(x.wikiTitle)x.views=await pageViews(x.wikiTitle,signal);}}await Promise.all(Array.from({length:4},worker));return items;}
  function mergePois(osm,wiki,center){const all=[...osm];for(const w of wiki){let best=null,bd=180;for(const o of all){const d=distance(w,o);if(d<bd){bd=d;best=o;}}if(best){best.wikiTitle=best.wikiTitle||w.wikiTitle;best.thumbnail=best.thumbnail||w.thumbnail;best.views=Math.max(best.views||0,w.views||0);}else all.push(w);}for(const x of all)x.distance=distance(center,x);return all.sort((a,b)=>{const va=Math.log10(1+(a.views||0)),vb=Math.log10(1+(b.views||0));const ca=a.category==='peak'?0.35:a.category==='viewpoint'?0.3:a.category==='attraction'?0.25:0.15,cb=b.category==='peak'?0.35:b.category==='viewpoint'?0.3:b.category==='attraction'?0.25:0.15;return (vb+cb-b.distance/25000)-(va+ca-a.distance/25000);}).slice(0,24);}
  function mapRadius(){const b=map.getBounds(),c=map.getCenter(),corners=[b.getNorthEast(),b.getSouthWest()];return Math.max(1500,Math.min(10000,Math.max(...corners.map(x=>distance({lat:c.lat,lng:c.lng},{lat:x.lat,lng:x.lng})))));}
  async function loadPois(){if(!map||mode!=='destination')return;loadAbort?.abort();loadAbort=new AbortController();const signal=loadAbort.signal,cc=map.getCenter(),center={lat:cc.lat,lng:cc.lng},radius=mapRadius();setStatus('名所を探しています…');clearMarkers();let osm=[],wiki=[];const settled=await Promise.allSettled([overpass(center,radius,signal),wikiGeo(center,radius,signal)]);if(settled[0].status==='fulfilled')osm=settled[0].value;if(settled[1].status==='fulfilled')wiki=settled[1].value;try{await enrichViews(wiki.slice(0,12),signal);}catch{}if(signal.aborted)return;const pois=mergePois(osm,wiki,center);renderPois(pois);setStatus(pois.length?`${pois.length}件の候補`:'この範囲に候補がありません');}
  function renderPois(pois){clearMarkers();for(const p of pois){const el=document.createElement('button');el.className=`phase3-poi ${p.category}`;el.type='button';el.innerHTML=`<span>${catIcon(p.category)}</span>`;el.setAttribute('aria-label',p.title);el.addEventListener('click',e=>{e.stopPropagation();selectPoi(p);});const m=new maplibregl.Marker({element:el,anchor:'center'}).setLngLat([p.lng,p.lat]).addTo(map);markers.push(m);}}
  function selectPoi(p){selected=p;const s=$('destinationSheet');s.classList.add('open');$('destinationCategory').textContent=catLabel(p.category);$('destinationTitle').textContent=p.title;$('destinationMeta').textContent=[p.source,p.views?`Wikipedia 30日 ${p.views.toLocaleString()}閲覧`:null].filter(Boolean).join(' · ');const img=$('destinationImage');if(p.thumbnail){img.src=p.thumbnail;img.hidden=false;}else{img.hidden=true;img.removeAttribute('src');}}
  function closeDestinationSheet(){selected=null;$('destinationSheet')?.classList.remove('open');}
  function registerDestination(){if(!selected)return;destination={...selected,registeredAt:new Date().toISOString()};try{sessionStorage.setItem(DEST_KEY,JSON.stringify(destination));}catch{}mode='browse';clearMarkers();closeDestinationSheet();setRoutes(true);document.body.classList.remove('phase3-destination-mode');$('phase3Start').innerHTML=`<small>到着地</small><b>${esc(destination.title)}</b>`;$('phase3Start').classList.add('has-destination');setStatus('撮影済みルートから出発地を選択');}
  function beginDestinationMode(){mode='destination';selected=null;setRoutes(false);document.body.classList.add('phase3-destination-mode');$('phase3Start').classList.remove('has-destination');$('phase3Start').innerHTML='<b>到着地を選んでください</b><small>観光地・山・展望地・名所</small>';loadPois();}
  function installUI(){if($('phase3Start'))return;const btn=document.createElement('button');btn.id='phase3Start';btn.className='phase3-start';btn.type='button';btn.innerHTML='<b>旅をはじめる</b><small>まず到着地を選ぶ</small>';btn.addEventListener('click',()=>{if(mode==='browse')beginDestinationMode();});document.body.appendChild(btn);const status=document.createElement('div');status.id='phase3Status';status.className='phase3-status';status.textContent='';document.body.appendChild(status);const sheet=document.createElement('section');sheet.id='destinationSheet';sheet.className='destination-sheet';sheet.innerHTML=`<button id="destinationBackdrop" class="destination-backdrop" type="button" aria-label="閉じる"></button><div class="destination-card"><div class="destination-handle"></div><div class="destination-body"><img id="destinationImage" hidden alt=""><div><span id="destinationCategory">名所</span><h2 id="destinationTitle">目的地</h2><p id="destinationMeta"></p></div></div><button id="registerDestination" class="destination-primary" type="button">到着地登録</button><button id="cancelDestination" class="destination-secondary" type="button">戻る</button></div>`;document.body.appendChild(sheet);$('destinationBackdrop').addEventListener('click',closeDestinationSheet);$('cancelDestination').addEventListener('click',closeDestinationSheet);$('registerDestination').addEventListener('click',registerDestination);}
  function attach(m){map=m;window.__streetviewCoverageMap=m;installUI();map.on('moveend',()=>{if(mode==='destination')loadPois();});map.on('load',()=>{if(mode==='destination')loadPois();});}
  function hookMapLibre(){if(!window.maplibregl?.Map)return false;const Original=window.maplibregl.Map;if(Original.__phase3Wrapped)return true;class WrappedMap extends Original{constructor(opts){super(opts);setTimeout(()=>attach(this),0);}}WrappedMap.__phase3Wrapped=true;window.maplibregl.Map=WrappedMap;return true;}
  if(!hookMapLibre()){window.addEventListener('load',()=>{hookMapLibre();if(window.__streetviewCoverageMap)attach(window.__streetviewCoverageMap);},{once:true});}
})();