(() => {
'use strict';
const TOKEN_KEY='streetview:mapillary-token',DEST_KEY='streetview:phase3-destination',ROUTE_KEY='streetview:journey-route',GRAPH='https://graph.mapillary.com';
const MLY_SOURCE='mapillary-coverage',MLY_LINE='mapillary-sequence-line',MLY_IMAGE='mapillary-image-points';
const ROUTE_SOURCE='selected-journey-route',ROUTE_GLOW='selected-journey-route-glow',ROUTE_LINE='selected-journey-route-line';
const CONNECT_METERS=120,START_METERS=150,MAX_HOPS=20,MIN_READY=12,INITIAL_SCAN=64,MAX_HEADING=78,FALLBACK_HEADING=105,META_BATCH=48;
let map=null,busy=false,startMarker=null,endMarker=null,lastPinnedKey='';
const $=id=>document.getElementById(id),rad=d=>d*Math.PI/180;
function token(){try{return localStorage.getItem(TOKEN_KEY)||''}catch{return''}}
function destination(){try{const x=JSON.parse(sessionStorage.getItem(DEST_KEY)||'null');return x&&Number.isFinite(+x.lat)&&Number.isFinite(+x.lng)?{...x,lat:+x.lat,lng:+x.lng}:null}catch{return null}}
function dist(a,b){const p1=rad(+a.lat),p2=rad(+b.lat),dp=rad(+b.lat-+a.lat),dl=rad(+b.lng-+a.lng),s=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 12742000*Math.atan2(Math.sqrt(s),Math.sqrt(Math.max(0,1-s)))}
function bearing(a,b){const p1=rad(+a.lat),p2=rad(+b.lat),dl=rad(+b.lng-+a.lng),y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function adiff(a,b){return Math.abs(((b-a+540)%360)-180)}
function fid(f){return String(f?.properties?.id??f?.properties?.sequence_id??f?.properties?.image_id??f?.id??'').trim()}
async function api(path){const t=token();if(!t)throw new Error('Mapillary Access Tokenが未設定です');const r=await fetch(`${GRAPH}${path}`,{headers:{Authorization:`OAuth ${t}`}}),j=await r.json().catch(()=>({}));if(!r.ok||j?.error)throw new Error(j?.error?.message||`Mapillary API ${r.status}`);return j}
async function imageIds(seq){const j=await api(`/image_ids?sequence_id=${encodeURIComponent(seq)}`);return(j?.data||[]).map(x=>String(x?.id??x)).filter(Boolean)}
async function imageMetas(refs){const out=new Array(refs.length).fill(null);for(let s=0;s<refs.length;s+=META_BATCH){const part=refs.slice(s,s+META_BATCH),ids=part.map(r=>r.id).join(','),fields='id,sequence,captured_at,computed_geometry,compass_angle,thumb_2048_url,is_pano';try{const j=await api(`/images?image_ids=${encodeURIComponent(ids)}&fields=${encodeURIComponent(fields)}`),by=new Map((j?.data||[]).map(x=>[String(x.id),x]));part.forEach((r,i)=>{out[s+i]=by.get(String(r.id))||null})}catch{}}
return out}
async function pmap(items,limit,fn){const out=new Array(items.length);let n=0;async function w(){for(;;){const i=n++;if(i>=items.length)return;try{out[i]=await fn(items[i],i)}catch{out[i]=null}}}await Promise.all(Array.from({length:Math.min(limit,items.length||1)},w));return out}
function frame(m,seq,i){const c=m?.computed_geometry?.coordinates;if(!Array.isArray(c)||c.length<2||!m?.thumb_2048_url)return null;return{id:String(m.id),sequenceId:String(seq),sequenceIndex:i,lat:+c[1],lng:+c[0],heading:Number.isFinite(+m.compass_angle)?+m.compass_angle:null,projection:m.is_pano?'SPHERE':'RECTILINEAR',fieldOfView:m.is_pano?360:100,url:m.thumb_2048_url,provider:'Mapillary',capturedAt:m.captured_at||null}}
function coordsOf(g){if(!g)return[];if(g.type==='LineString')return g.coordinates||[];if(g.type==='MultiLineString')return(g.coordinates||[]).flat();return[]}
function point(c){return{lng:+c[0],lat:+c[1]}}
function sample(cs,max=56){if(cs.length<=max)return cs;const step=Math.max(1,Math.ceil(cs.length/max)),out=[];for(let i=0;i<cs.length;i+=step)out.push(cs[i]);if(out[out.length-1]!==cs[cs.length-1])out.push(cs[cs.length-1]);return out}
function featureMap(features){const m=new Map();for(const f of features){const id=fid(f),cs=coordsOf(f.geometry);if(!id||cs.length<2)continue;if(!m.has(id))m.set(id,{id,parts:[]});m.get(id).parts.push(cs)}for(const n of m.values()){n.parts=n.parts.map(p=>sample(p));n.coords=n.parts.reduce((best,p)=>p.length>best.length?p:best,[])}return m}
function nearestCoord(cs,p){let index=0,distance=Infinity;for(let i=0;i<cs.length;i++){const d=dist(point(cs[i]),p);if(d<distance){distance=d;index=i}}return{index,distance}}
function forwardNode(node,current,dest){let best=null;for(const cs of node.parts||[node.coords]){const near=nearestCoord(cs,current),i=near.index;if(i>=cs.length-1)continue;const part=cs.slice(i),entry=point(part[0]),exit=point(part[part.length-1]);let probe=1;while(probe<part.length-1&&dist(entry,point(part[probe]))<18)probe++;const next=point(part[Math.min(probe,part.length-1)]),goal=bearing(current,dest),head=bearing(entry,next),headingError=adiff(goal,head),entryDest=dist(entry,dest),destDistance=dist(exit,dest),o={id:node.id,coords:part,entry,exit,connector:near.distance,destDistance,entryDest,headingError,heading:head,improvement:entryDest-destDistance};if(!best||o.connector<best.connector)best=o}return best}
function scoreOption(o,currentDest){const progress=currentDest-o.destDistance;return o.headingError*28+o.connector*3.4+o.destDistance-Math.max(0,progress)*.75-Math.max(0,o.improvement)*.35}
function candidates(nodes,visited,current,dest,maxConnector,maxHeading){const currentDest=dist(current,dest),arr=[];for(const n of nodes.values()){if(visited?.has(n.id))continue;const o=forwardNode(n,current,dest);if(!o||o.connector>maxConnector||o.headingError>maxHeading)continue;const progress=currentDest-o.destDistance;if(progress<-35||o.improvement<-55)continue;arr.push({...o,progress,score:scoreOption(o,currentDest)})}return arr.sort((a,b)=>a.score-b.score)}
function pickStart(nodes,current,dest){let a=candidates(nodes,null,current,dest,START_METERS,MAX_HEADING);if(!a.length)a=candidates(nodes,null,current,dest,START_METERS,FALLBACK_HEADING);return a[0]||null}
function pickNext(nodes,visited,current,dest){let a=candidates(nodes,visited,current,dest,CONNECT_METERS,MAX_HEADING);if(!a.length)a=candidates(nodes,visited,current,dest,CONNECT_METERS,FALLBACK_HEADING);return a[0]||null}
function greedyRoute(nodes,startPoint,dest){const visited=new Set(),plans=[],routeLines=[],connectors=[];let current=startPoint;for(let hop=0;hop<MAX_HOPS;hop++){const o=hop===0?pickStart(nodes,current,dest):pickNext(nodes,visited,current,dest);if(!o)break;visited.add(o.id);if(plans.length){const prev=plans[plans.length-1].exit;if(dist(prev,o.entry)>2)connectors.push([[prev.lng,prev.lat],[o.entry.lng,o.entry.lat]])}plans.push({sequenceId:o.id,entry:o.entry,exit:o.exit,headingError:o.headingError,connector:o.connector,coords:o.coords});routeLines.push(o.coords);current=o.exit;if(dist(current,dest)<=140)break}return{plans,routeLines,connectors,destinationDistance:dist(current,dest)}}
function removeMarker(m){try{m?.remove()}catch{}return null}
function pin(label,kind,lnglat){const el=document.createElement('div');el.className=`phase4-route-pin ${kind}`;el.textContent=label;return new maplibregl.Marker({element:el,anchor:'center'}).setLngLat(lnglat).addTo(map)}
function setPins(start,dest){const key=`${(+start.lng).toFixed(5)},${(+start.lat).toFixed(5)}:${(+dest.lng).toFixed(5)},${(+dest.lat).toFixed(5)}`;if(key===lastPinnedKey)return;lastPinnedKey=key;startMarker=removeMarker(startMarker);endMarker=removeMarker(endMarker);startMarker=pin('出','start',[+start.lng,+start.lat]);endMarker=pin('着','end',[+dest.lng,+dest.lat])}
function hideCoverage(){for(const id of ['kartaview-coverage-layer','mapillary-sequence-glow','mapillary-sequence-line','mapillary-image-points'])try{if(map.getLayer(id))map.setLayoutProperty(id,'visibility','none')}catch{}}
function showRoute(lines,connectors,start,dest){const good=lines.filter(x=>Array.isArray(x)&&x.length>=2);if(!good.length)throw new Error('表示できる経路形状を作れませんでした');const features=[];good.forEach((c,i)=>features.push({type:'Feature',properties:{provider:'Mapillary',kind:'route',order:i},geometry:{type:'LineString',coordinates:c}}));connectors.forEach((c,i)=>features.push({type:'Feature',properties:{provider:'Mapillary',kind:'connector',order:i},geometry:{type:'LineString',coordinates:c}}));const data={type:'FeatureCollection',features},src=map.getSource(ROUTE_SOURCE);if(src?.setData)src.setData(data);else{try{if(map.getLayer(ROUTE_LINE))map.removeLayer(ROUTE_LINE);if(map.getLayer(ROUTE_GLOW))map.removeLayer(ROUTE_GLOW);if(map.getSource(ROUTE_SOURCE))map.removeSource(ROUTE_SOURCE)}catch{}map.addSource(ROUTE_SOURCE,{type:'geojson',data});map.addLayer({id:ROUTE_GLOW,type:'line',source:ROUTE_SOURCE,paint:{'line-color':['case',['==',['get','kind'],'connector'],'#9affbd','#58ff93'],'line-width':['case',['==',['get','kind'],'connector'],9,14],'line-opacity':['case',['==',['get','kind'],'connector'],.22,.34],'line-blur':4}});map.addLayer({id:ROUTE_LINE,type:'line',source:ROUTE_SOURCE,paint:{'line-color':['case',['==',['get','kind'],'connector'],'#b8ffd0','#18d96f'],'line-width':['case',['==',['get','kind'],'connector'],3,5.5],'line-opacity':1,'line-dasharray':['case',['==',['get','kind'],'connector'],['literal',[2,2]],['literal',[1,0]]]}})}hideCoverage();setPins(start,dest);try{const b=new maplibregl.LngLatBounds();good.flat().forEach(c=>b.extend(c));connectors.flat().forEach(c=>b.extend(c));b.extend([dest.lng,dest.lat]);map.fitBounds(b,{padding:{top:125,right:55,bottom:350,left:55},maxZoom:15,duration:350})}catch{}}
function ensureCandidate(){return $('journeyCandidate')&&$('candidateTitle')&&$('candidateText')}
function openLoading(){if(!ensureCandidate())return;const c=$('journeyCandidate');c.classList.add('is-open','is-loading');document.querySelector('.provider-panel')?.classList.add('has-candidate');$('candidateKicker').textContent='MAPILLARY JOURNEY ROUTE';$('candidateKicker').classList.add('mapillary');$('candidateTitle').textContent='撮影ルートを検索中';$('candidateText').classList.remove('jc-error');$('candidateText').textContent='近くの全sequenceを比較し、到着地方向へ進むルートを選んでいる。';$('candidateStats').hidden=true;$('candidateActions').hidden=true}
function setupCard(payload){const path=payload.sequenceIds,dd=payload.selection.destinationDistanceMeters,c=$('journeyCandidate');c.classList.remove('is-loading');$('candidateTitle').textContent=path.length>1?`${path.length} sequencesを接続`:`Sequence ${path[0]}`;$('candidateText').textContent=`到着地方向を優先して接続。到着地まで残り ${dd<1000?Math.round(dd)+'m':(dd/1000).toFixed(1)+'km'}。`;$('candidateStats').hidden=false;$('candidateStats').innerHTML=`<div class="jc-stat"><small>Provider</small><b>Mapillary</b></div><div class="jc-stat"><small>準備済み</small><b id="streamReadyCount">0枚</b></div><div class="jc-stat"><small>接続sequence</small><b>${path.length}本</b></div>`;$('candidateActions').hidden=false;const old=$('candidateStart'),btn=old.cloneNode(true);old.replaceWith(btn);btn.disabled=true;btn.textContent='先頭画像を準備中…';btn.addEventListener('click',()=>{if(btn.disabled)return;try{payload.streamOpen=payload.streamPending.length>0;sessionStorage.setItem(ROUTE_KEY,JSON.stringify(payload));location.href='/journey-map.html?autostart=1'}catch{}});payload._button=btn}
function updateReady(payload){const n=payload.frames.length,total=payload.selection.totalImageIds||n,el=$('streamReadyCount');if(el)el.textContent=`${n} / ${total}枚`;if(payload._button&&n>=Math.min(MIN_READY,total)){payload._button.disabled=false;payload._button.textContent='このルートでJourney開始'}}
function renderError(msg){if(!ensureCandidate())return;$('journeyCandidate').classList.remove('is-loading');$('candidateTitle').textContent='撮影ルートを接続できなかった';$('candidateText').classList.add('jc-error');$('candidateText').textContent=msg;$('candidateStats').hidden=true;$('candidateActions').hidden=true}
async function buildRefs(plans,anchorImageId){const lists=await pmap(plans,8,async plan=>{let ids=await imageIds(plan.sequenceId);if(!ids.length)return[];if(plan===plans[0]&&anchorImageId){const i=ids.indexOf(String(anchorImageId));if(i>=0)ids=ids.slice(i)}return ids.map((id,i)=>({id,sequenceId:plan.sequenceId,sequenceIndex:i}))});return lists.filter(Boolean).flat()}
async function refsToFrames(refs){const meta=await imageMetas(refs),frames=[],failed=[];for(let i=0;i<refs.length;i++){const f=meta[i]?frame(meta[i],refs[i].sequenceId,refs[i].sequenceIndex):null;if(f)frames.push(f);else failed.push(refs[i])}return{frames,failed}}
async function prepareInitial(payload,refs){let cursor=0,failed=[];while(cursor<refs.length&&payload.frames.length<Math.min(MIN_READY,refs.length)&&cursor<INITIAL_SCAN){const batch=refs.slice(cursor,Math.min(cursor+META_BATCH,INITIAL_SCAN,refs.length)),res=await refsToFrames(batch);payload.frames.push(...res.frames);failed.push(...res.failed);cursor+=batch.length;updateReady(payload);await new Promise(r=>setTimeout(r,0))}payload.streamPending=[...failed,...refs.slice(cursor)];if(payload.frames.length<2)throw new Error('先頭の再生画像を準備できませんでした')}
async function waitTiles(){for(let i=0;i<8;i++){let fs=[];try{fs=map.querySourceFeatures(MLY_SOURCE,{sourceLayer:'sequence'})||[]}catch{}if(fs.length>12)return fs;await new Promise(r=>setTimeout(r,80))}try{return map.querySourceFeatures(MLY_SOURCE,{sourceLayer:'sequence'})||[]}catch{return[]}}
async function handle(feature,ll,anchorImageId=null){if(busy)return;const dest=destination();if(!dest||!token())return;busy=true;openLoading();try{const b=new maplibregl.LngLatBounds([ll.lng,ll.lat],[ll.lng,ll.lat]);b.extend([dest.lng,dest.lat]);map.fitBounds(b,{padding:70,maxZoom:13,duration:0});const features=await waitTiles(),nodes=featureMap(features);const clickedId=fid(feature),clickedCoords=coordsOf(feature.geometry);if(clickedId&&clickedCoords.length>=2&&!nodes.has(clickedId))nodes.set(clickedId,{id:clickedId,parts:[sample(clickedCoords)],coords:sample(clickedCoords)});if(!nodes.size)throw new Error('周辺のMapillary sequenceを取得できませんでした');const route=greedyRoute(nodes,{lat:ll.lat,lng:ll.lng},dest);if(!route.plans.length)throw new Error('到着地方向へ進むsequenceが見つかりません');const routeStart=route.plans[0].entry||{lat:ll.lat,lng:ll.lng};showRoute(route.routeLines,route.connectors,routeStart,dest);const payload={version:'0.4.6-multiline-batch',source:'Mapillary',provider:'Mapillary',sequenceId:route.plans.map(x=>x.sequenceId).join('→'),sequenceIds:route.plans.map(x=>x.sequenceId),frames:[],destination:dest,streamOpen:true,streamPending:[],selection:{strategy:'mapillary-heading-first-greedy',destinationDistanceMeters:route.destinationDistance,candidateCount:route.plans.length,totalImageIds:0,maxHeadingErrorDeg:Math.max(...route.plans.map(x=>x.headingError||0)),routeReady:true}};setupCard(payload);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const refs=await buildRefs(route.plans,anchorImageId);if(refs.length<2)throw new Error('再生できるMapillary画像が不足しています');payload.selection.totalImageIds=refs.length;await prepareInitial(payload,refs);updateReady(payload)}catch(e){renderError(e?.message||'Mapillaryルート接続に失敗しました')}finally{busy=false}}
function domPoint(e){const r=map.getCanvas().getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function captureClick(e){const dest=destination();if(!dest||!token()||busy)return;const p=domPoint(e);let fs=[];try{fs=map.queryRenderedFeatures(p,{layers:[MLY_IMAGE,MLY_LINE]})||[]}catch{}if(!fs[0])return;e.preventDefault();e.stopImmediatePropagation();let feature=fs[0],anchor=null;if(feature.layer?.id===MLY_IMAGE)anchor=fid(feature);else{try{const ims=map.queryRenderedFeatures([[p.x-22,p.y-22],[p.x+22,p.y+22]],{layers:[MLY_IMAGE]})||[];if(ims[0])anchor=fid(ims[0])}catch{}}const ll=map.unproject(p);handle(feature,ll,anchor)}
function attach(m){if(map===m)return;map=m;const style=document.createElement('style');style.textContent='.phase4-route-pin{width:38px;height:38px;border-radius:999px;display:grid;place-items:center;border:3px solid #fff;box-shadow:0 5px 20px rgba(0,0,0,.38);font-size:12px;font-weight:900;color:#fff;z-index:30}.phase4-route-pin.start{background:#111827}.phase4-route-pin.end{background:#ef4444}';document.head.appendChild(style);map.getCanvas().addEventListener('click',captureClick,true)}
const timer=setInterval(()=>{if(window.__streetviewCoverageMap){clearInterval(timer);attach(window.__streetviewCoverageMap)}},60);setTimeout(()=>clearInterval(timer),15000);
})();