/* Journey playback-only diagnostics. Observes playback; does not alter playback, URL refresh, or streaming. */
(()=>{
  if(window.__journeyPlaybackLoggerInstalled)return;
  window.__journeyPlaybackLoggerInstalled=true;
  const VERSION='0.1.37-playback-log',MAX_EVENTS=500,POLL_MS=120,STALL_MS=650,RAF_GAP_MS=220;
  const trace={schema:'streetview-journey-playback-diagnostic-v1',version:VERSION,startedAt:null,events:[]};
  let active=false,t0=0,lastIndex=null,lastAdvance=0,lastHeartbeat=0,lastStall=0,lastRaf=performance.now();
  function safeUrl(u){try{const x=new URL(String(u||''),location.href);return{present:!!u,protocol:x.protocol,host:x.host,path:x.pathname.slice(-100),queryKeys:[...x.searchParams.keys()].slice(0,8),length:String(u||'').length}}catch{return{present:!!u,invalid:true,length:String(u||'').length}}}
  function imageState(id){const im=document.getElementById(id),src=im?.currentSrc||im?.src||'';return{complete:!!im?.complete,naturalWidth:im?.naturalWidth||0,naturalHeight:im?.naturalHeight||0,visible:!!im?.classList?.contains('is-visible'),src:safeUrl(src)}}
  function snapshot(){
    const p=window.__journeyPlaybackState||{},s=window.__journeyStreamState||{},e=window.JourneyEngine?.getState?.()||{},d=window.__journeyDiagnostics||{},sel=window.__journeySelectedRoute||{};
    const index=Number.isFinite(p.index)?p.index:(Number.isFinite(e.index)?e.index:null);
    const available=Number.isFinite(p.available)?p.available:(Number.isFinite(e.available)?e.available:(Array.isArray(sel.frames)?sel.frames.length:0));
    const total=Number.isFinite(p.total)?p.total:(Number.isFinite(e.total)?e.total:(sel.selection?.totalImageIds||available));
    const frame=Number.isFinite(index)?sel.frames?.[index]:null;
    return{index,available,total,streaming:!!(p.streaming??e.streaming),stream:{active:!!s.active,complete:!!s.complete,failed:!!s.failed,frameCount:Array.isArray(s.frames)?s.frames.length:0,pending:Array.isArray(sel.streamPending)?sel.streamPending.length:0},engine:{routeLength:e.routeLength??null,frameCache:e.frameCache??null,tileLayerCache:e.tileLayerCache??null,pairCache:e.pairCache??null,version:e.version||null},diagnostics:{worker:d.worker||null,workerReady:!!d.workerReady,lastPairMs:Number.isFinite(d.lastPairMs)?d.lastPairMs:null,frameCacheHits:d.frameCacheHits??null,tileCacheHits:d.tileCacheHits??null,pairCacheHits:d.pairCacheHits??null,lastWorkerPair:d.lastWorkerPair??null},currentFrame:frame?{id:String(frame.id||''),sequenceId:String(frame.sequenceId||''),sequenceIndex:frame.sequenceIndex??null,url:safeUrl(frame.url)}:null,dom:{frameLabel:document.getElementById('frameLabel')?.textContent||null,networkLabel:document.getElementById('networkLabel')?.textContent||null,errorVisible:!document.getElementById('errorPanel')?.hidden,errorMessage:document.getElementById('errorMessage')?.textContent||null,layerA:imageState('layerA'),layerB:imageState('layerB')}};
  }
  function log(name,data={}){if(!active&&name!=='playback-trace-start')return;const row={tMs:Math.round(performance.now()-t0),name,...data};trace.events.push(row);if(trace.events.length>MAX_EVENTS)trace.events.shift();console.info('[JourneyPlayback]',row)}
  function start(detail={}){if(active)return;active=true;t0=performance.now();trace.startedAt=new Date().toISOString();lastIndex=null;lastAdvance=t0;lastHeartbeat=0;lastStall=0;log('playback-trace-start',{detail,initial:snapshot()})}
  async function copy(){const payload={...trace,exportedAt:new Date().toISOString(),page:{visibility:document.visibilityState,online:navigator.onLine,userAgent:navigator.userAgent},current:snapshot(),startupTail:(window.__journeyStartupTrace?.events||[]).slice(-12)};const text=JSON.stringify(payload,null,2);try{await navigator.clipboard.writeText(text);return true}catch{}try{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();return true}catch{return false}}
  function installButton(){let btn=document.getElementById('playbackLogCopy');if(!btn){btn=document.createElement('button');btn.id='playbackLogCopy';btn.type='button';document.body.appendChild(btn)}btn.textContent='再生ログコピー';btn.style.cssText='position:fixed;z-index:31;right:10px;top:calc(env(safe-area-inset-top) + 98px);width:auto;height:30px;padding:0 9px;border:1px solid rgba(255,255,255,.22);border-radius:999px;background:rgba(5,8,12,.58);color:#fff;font:700 9px/1 -apple-system,BlinkMacSystemFont,"SF Pro Text",sans-serif;backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);pointer-events:auto';btn.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();const ok=await copy();btn.textContent=ok?'コピー完了':'コピー失敗';setTimeout(()=>btn.textContent='再生ログコピー',1200)})}
  window.__copyJourneyPlaybackLog=copy;
  window.addEventListener('journey-playback-started',e=>start(e.detail||{}));
  window.addEventListener('journey-playback-stalled',e=>{if(active)log('engine-stall-event',{detail:e.detail||null,snapshot:snapshot()})});
  window.addEventListener('journey-playback-ended',e=>{if(active)log('playback-ended',{detail:e.detail||null,snapshot:snapshot()})});
  document.addEventListener('visibilitychange',()=>{if(active)log('visibility-change',{visibility:document.visibilityState})});
  function hookLayer(id){const im=document.getElementById(id);if(!im)return;im.addEventListener('load',()=>{if(active)log('layer-load',{layer:id,state:imageState(id)})});im.addEventListener('error',()=>{if(active)log('layer-error',{layer:id,state:imageState(id)})})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{installButton();hookLayer('layerA');hookLayer('layerB')},{once:true});else{installButton();hookLayer('layerA');hookLayer('layerB')}
  setInterval(()=>{if(!active)return;const now=performance.now(),snap=snapshot(),idx=snap.index,changed=idx!==lastIndex;if(changed){lastIndex=idx;lastAdvance=now;log('frame-advance',snap)}if(now-lastHeartbeat>=1000){lastHeartbeat=now;log('heartbeat',snap)}const canAdvance=Number.isFinite(idx)&&Number.isFinite(snap.available)&&snap.available>idx+1&&!snap.dom.errorVisible;if(canAdvance&&now-lastAdvance>=STALL_MS&&now-lastStall>=1000){lastStall=now;log('stall-suspected',{stalledMs:Math.round(now-lastAdvance),...snap})}},POLL_MS);
  function rafWatch(now){const gap=now-lastRaf;lastRaf=now;if(active&&gap>RAF_GAP_MS)log('main-thread-gap',{gapMs:Math.round(gap),snapshot:snapshot()});requestAnimationFrame(rafWatch)}requestAnimationFrame(rafWatch);
})();
