function createMemoizedProvider(){
  const M=window.mapillary;if(!M?.GraphDataProvider)throw new Error('Mapillary GraphDataProviderを読み込めませんでした');
  const base=new M.GraphDataProvider({accessToken:token()});const stats={imagesHit:0,imagesMiss:0,bufferHit:0,bufferMiss:0,meshHit:0,meshMiss:0,clusterHit:0,clusterMiss:0};
  const images=new Map(),spatial=new Map(),buffers=new Map(),meshes=new Map(),clusters=new Map(),tiles=new Map(),sequences=new Map();
  const original={getImages:base.getImages.bind(base),getSpatialImages:base.getSpatialImages.bind(base),getImageBuffer:base.getImageBuffer.bind(base),getMesh:base.getMesh.bind(base),getCluster:base.getCluster.bind(base),getImageTiles:base.getImageTiles.bind(base),getSequence:base.getSequence.bind(base)};
  base.getImages=async ids=>{const keys=ids.map(String),miss=keys.filter(id=>!images.has(id));if(miss.length){stats.imagesMiss+=miss.length;const rows=await original.getImages(miss);for(const row of rows||[]){const id=String(row?.node_id??row?.node?.id??'');if(id){images.set(id,row);spatial.set(id,row)}}}else stats.imagesHit+=keys.length;return keys.map(id=>images.get(id)).filter(Boolean)};
  base.getSpatialImages=async ids=>{const keys=ids.map(String),miss=keys.filter(id=>!spatial.has(id));if(miss.length){const rows=await original.getSpatialImages(miss);for(const row of rows||[]){const id=String(row?.node_id??row?.node?.id??'');if(id)spatial.set(id,row)}}return keys.map(id=>spatial.get(id)).filter(Boolean)};
  function memoUrl(map,hitKey,missKey,fn){return async(url,abort)=>{if(map.has(url)){stats[hitKey]++;return map.get(url)}stats[missKey]++;const p=fn(url,abort).catch(e=>{map.delete(url);throw e});map.set(url,p);return p}}
  base.getImageBuffer=memoUrl(buffers,'bufferHit','bufferMiss',original.getImageBuffer);base.getMesh=memoUrl(meshes,'meshHit','meshMiss',original.getMesh);base.getCluster=memoUrl(clusters,'clusterHit','clusterMiss',original.getCluster);
  base.getImageTiles=async req=>{const key=`${req.imageId}:${req.z}`;if(!tiles.has(key))tiles.set(key,original.getImageTiles(req).catch(e=>{tiles.delete(key);throw e}));return tiles.get(key)};
  base.getSequence=async id=>{const key=String(id);if(!sequences.has(key))sequences.set(key,original.getSequence(key).catch(e=>{sequences.delete(key);throw e}));return sequences.get(key)};
  return{provider:base,stats};
}
function contractNode(rows,id){const row=(rows||[]).find(x=>String(x?.node_id??x?.node?.id??'')===String(id))||(rows||[])[0];return row?.node||null}
async function prefetchFrame(index,generation=state.preloadGeneration){
  if(generation!==state.preloadGeneration||!state.route||state.preloaded.has(index))return false;const frame=state.route.frames[index];if(!frame)return false;const t0=performance.now();
  try{const rows=await state.provider.getImages([frame.id]);if(generation!==state.preloadGeneration)return false;const node=contractNode(rows,frame.id);if(!node)throw new Error('image-contract-missing');const jobs=[];if(node.thumb?.url)jobs.push(state.provider.getImageBuffer(node.thumb.url));if(node.mesh?.url)jobs.push(state.provider.getMesh(node.mesh.url));if(node.cluster?.url)jobs.push(state.provider.getCluster(node.cluster.url));const settled=await Promise.allSettled(jobs);if(!jobs.length||settled.every(x=>x.status==='rejected'))throw new Error('asset-prefetch-failed');state.preloaded.add(index);state.preloadTimes.push(performance.now()-t0);return true}catch{state.preloadFailures++;return false}
}
async function prefetchIndexes(indexes,concurrency=PRELOAD_CONCURRENCY,generation=state.preloadGeneration){let cursor=0;const workers=Array.from({length:Math.min(concurrency,indexes.length||1)},async()=>{while(cursor<indexes.length&&generation===state.preloadGeneration)await prefetchFrame(indexes[cursor++],generation)});await Promise.all(workers)}
function contiguousAhead(){let n=0;for(let i=state.cursor+1;i<state.route?.frames.length;i++){if(!state.preloaded.has(i))break;n++}return n}
function updatePreloadUI(){const total=Math.max(1,state.preloadTarget||PRELOAD_MIN),ready=Math.min(total,state.preloaded.size),pct=clamp(ready/total*100,0,100);if($('preloadBar'))$('preloadBar').style.width=`${pct}%`;if($('preloadText'))$('preloadText').textContent=`先読み ${state.preloaded.size}/${state.route?.frames.length||0}`;if($('prepBar'))$('prepBar').style.width=`${pct}%`;if($('prepText'))$('prepText').textContent=`Mapillary先読み ${state.preloaded.size}/${state.preloadTarget||'…'} ・ ${fmt(state.preloadRateFps,2,'fps')}`;updateTripReadyState()}
async function adaptivePreload(){
  const gen=++state.preloadGeneration;state.preloaded.clear();state.preloadTimes=[];state.preloadFailures=0;state.preloadTarget=PRELOAD_MIN;const wallStart=performance.now();updatePreloadUI();
  const sample=[...Array(Math.min(PRELOAD_SAMPLE,state.route.frames.length)).keys()],sampleStart=performance.now();await prefetchIndexes(sample,PRELOAD_CONCURRENCY,gen);const sampleWall=performance.now()-sampleStart,sampleReady=sample.filter(i=>state.preloaded.has(i)).length;state.preloadRateFps=sampleReady?sampleReady/(sampleWall/1000):0;
  const consumeRate=1000/DEFAULT_CADENCE,playSeconds=Math.max(1,(state.route.frames.length-1)*DEFAULT_CADENCE/1000),deficit=Math.max(0,(consumeRate-state.preloadRateFps)*playSeconds);state.preloadTarget=clamp(Math.ceil(deficit)+PRELOAD_MIN,PRELOAD_MIN,Math.min(PRELOAD_MAX,state.route.frames.length));updatePreloadUI();let next=sample.length;
  while(gen===state.preloadGeneration&&state.preloaded.size<state.preloadTarget&&next<state.route.frames.length&&performance.now()-wallStart<PRELOAD_WAIT_MAX_MS){const batch=[];while(batch.length<PRELOAD_CONCURRENCY&&next<state.route.frames.length)batch.push(next++);await prefetchIndexes(batch,PRELOAD_CONCURRENCY,gen);updatePreloadUI()}
  state.preloadWallMs=performance.now()-wallStart;state.preloadReadyAtOpen=state.preloaded.size;updatePreloadUI();return state.preloaded.size;
}
async function backgroundWarm(){if(state.backgroundWarming||!state.route||!state.provider)return;state.backgroundWarming=true;const gen=state.preloadGeneration;try{while(gen===state.preloadGeneration&&state.route){const end=Math.min(state.route.frames.length,state.cursor+1+BACKGROUND_AHEAD),needed=[];for(let i=state.cursor+1;i<end;i++)if(!state.preloaded.has(i))needed.push(i);if(!needed.length)break;await prefetchIndexes(needed.slice(0,3),3,gen);updatePreloadUI()}}finally{state.backgroundWarming=false}}
function clearPoiMarkers(){for(const m of state.poiMarkers)m.remove();state.poiMarkers=[]}
function poiIcon(type){return type==='peak'?'▲':type==='viewpoint'?'◉':'●'}
function addPoiMarker(p){const el=document.createElement('button');el.className=`poi-marker ${p.type}`;el.type='button';el.innerHTML=`<span>${poiIcon(p.type)}</span>`;el.setAttribute('aria-label',p.name);el.addEventListener('click',e=>{e.stopPropagation();chooseDestination(p)});const marker=new maplibregl.Marker({element:el,anchor:'center'}).setLngLat([p.lng,p.lat]).addTo(state.map);state.poiMarkers.push(marker)}
async function refreshPOIs(){if(!state.map||state.stage!=='goal'||state.map.getZoom()<10.5)return;const req=++state.poiRequestId,bounds=state.map.getBounds(),dynamic=await fetchPOIs(bounds);if(req!==state.poiRequestId||state.stage!=='goal')return;clearPoiMarkers();const seen=new Set();for(const p of [...FALLBACK_POIS,...dynamic]){const k=`${p.name}:${p.lat.toFixed(3)}`;if(seen.has(k))continue;seen.add(k);if(bounds.contains([p.lng,p.lat]))addPoiMarker(p)}}
function plannerStatus(title,hint){if($('plannerTitle'))$('plannerTitle').textContent=title;if($('plannerHint'))$('plannerHint').textContent=hint}
function syncPlannerUI(){if($('plannerStatus'))$('plannerStatus').hidden=state.stage!=='goal'||!$('poiCard')?.hidden;if($('centerAim'))$('centerAim').hidden=state.stage!=='start';if($('startPicker'))$('startPicker').hidden=state.stage!=='start';if($('routeSearchCard'))$('routeSearchCard').hidden=state.stage!=='search';if($('planner'))$('planner').dataset.stage=state.stage}
function chooseDestination(p){closeSearch();state.pendingGoal={lat:p.lat,lng:p.lng};state.selectedPlace=p;$('poiName').textContent=p.name;$('poiType').textContent=p.type==='peak'?'山・ピーク':p.type==='viewpoint'?'展望地':'観光地';$('poiCard').hidden=false;plannerStatus('到着地点候補',`${p.name} を到着地点に登録できます`);state.map.easeTo({center:[p.lng,p.lat],zoom:Math.max(state.map.getZoom(),14),duration:420});syncPlannerUI()}
function registerDestination(){if(!state.pendingGoal)return;state.goal={...state.pendingGoal};state.goalMarker?.remove();state.goalMarker=new maplibregl.Marker({color:'#ffffff'}).setLngLat([state.goal.lng,state.goal.lat]).addTo(state.map);state.stage='start';clearPoiMarkers();$('poiCard').hidden=true;$('startGoalName').textContent=state.selectedPlace?.name||'到着地';plannerStatus('出発地点を選ぶ','地図を動かし、中央の照準を出発地点に合わせます');syncPlannerUI();updateStartPickerCoord()}
function updateStartPickerCoord(){if(state.stage!=='start'||!state.map)return;const c=state.map.getCenter();if($('startCenterCoord'))$('startCenterCoord').textContent=`${c.lat.toFixed(5)}, ${c.lng.toFixed(5)}`}
function resolvedRouteGeoJSON(route){return{type:'FeatureCollection',features:route?.frames?.length>1?[{type:'Feature',properties:{direction:route.direction},geometry:{type:'LineString',coordinates:route.frames.map(f=>[f.lng,f.lat])}}]:[]}}
function showResolvedRoute(route){const map=state.map,geo=resolvedRouteGeoJSON(route);if(map.getSource('resolved-route'))map.getSource('resolved-route').setData(geo);else{map.addSource('resolved-route',{type:'geojson',data:geo});map.addLayer({id:'resolved-route-glow',type:'line',source:'resolved-route',paint:{'line-color':'rgba(124,242,200,.38)','line-width':13,'line-blur':5}});map.addLayer({id:'resolved-route-line',type:'line',source:'resolved-route',paint:{'line-color':'#ffffff','line-width':6,'line-opacity':.98}});map.addLayer({id:'resolved-route-arrows',type:'symbol',source:'resolved-route',layout:{'symbol-placement':'line','symbol-spacing':70,'text-field':'▶','text-size':12,'text-rotation-alignment':'map','text-keep-upright':false,'text-allow-overlap':true},paint:{'text-color':'#07110f','text-halo-color':'#ffffff','text-halo-width':2}})}const b=new maplibregl.LngLatBounds();for(const f of route.frames)b.extend([f.lng,f.lat]);if(state.start)b.extend([state.start.lng,state.start.lat]);if(state.goal)b.extend([state.goal.lng,state.goal.lat]);map.fitBounds(b,{padding:{top:90,bottom:330,left:28,right:28},duration:450,maxZoom:16})}
function clearResolvedRoute(){const map=state.map;if(!map)return;try{for(const id of['resolved-route-arrows','resolved-route-line','resolved-route-glow'])if(map.getLayer(id))map.removeLayer(id);if(map.getSource('resolved-route'))map.removeSource('resolved-route')}catch{}}
function updateRouteSearchCard(text,pct=0){if($('routeSearchTitle'))$('routeSearchTitle').textContent='ルートを検索しています…';if($('routeSearchHint'))$('routeSearchHint').textContent=text;if($('routeSearchBar'))$('routeSearchBar').style.width=`${clamp(pct,0,100)}%`}
async function registerStartPoint(){if(state.stage!=='start'||!state.goal)return;if(!token()){openTokenSheet();return}const c=state.map.getCenter();state.start={lat:c.lat,lng:c.lng};state.startMarker?.remove();state.startMarker=new maplibregl.Marker({color:'#7cf2c8'}).setLngLat([state.start.lng,state.start.lat]).addTo(state.map);state.stage='search';syncPlannerUI();updateRouteSearchCard('出発地と到着地の両方に近い同一sequenceを探しています…',6);await prepareRouteFromEndpoints()}
function updateRouteSummary(){const name=state.selectedPlace?.name||'到着地';$('tripRouteName').textContent=`${distanceLabel(state.totalDistanceM)} ・ ${name}`;$('tripStartLabel').textContent=coordLabel(state.start);$('tripGoalLabel').textContent=name}
async function prepareRouteFromEndpoints(){const setupStart=performance.now();$('tripSheet').hidden=true;$('tripStart').disabled=true;$('prepArea').hidden=false;try{state.route=await resolveRouteBetweenPoints();state.totalDistanceM=state.route.totalDistanceM;showResolvedRoute(state.route);updateRouteSearchCard(`${state.route.direction}方向でルート確定`,86);const memo=createMemoizedProvider();state.provider=memo.provider;state.providerStats=memo.stats;state.stage='trip';syncPlannerUI();$('routeSearchCard').hidden=true;$('tripSheet').hidden=false;resetTripTiming();updateRouteSummary();renderTripTimes();renderElevationChart();const summary=state.routeCacheHit?'保存済みルートを使用':`${(state.routeResolveMs/1000).toFixed(1)}秒 / ${state.routeSearchApiRequests} API / ${state.route.direction}`;$('prepText').textContent=`${summary} ・ 先読み開始`;$('prepBar').style.width='4%';const preloadPromise=adaptivePreload();const elevationPromise=loadElevationProfile(state.route).then(()=>{resetTripTiming();renderTripTimes();renderElevationChart();updateTripReadyState()});Promise.allSettled([preloadPromise,elevationPromise]).then(()=>{state.setupMs=performance.now()-setupStart;updateRouteSummary();updateTripReadyState()});plannerStatus('ルート確定','標高と画像を準備しています')}catch(error){state.stage='search';syncPlannerUI();$('routeSearchTitle').textContent='ルートが見つかりませんでした';$('routeSearchHint').textContent=String(error?.message||error);$('routeSearchBar').style.width='0';$('routeSearchRetry').hidden=false;plannerStatus('出発地点を調整','少し場所を変えて再検索できます')}}
function renderTripTimes(){if(!state.departureTime)resetTripTiming();$('tripDepart').textContent=timeLabel(state.departureTime);$('tripArrive').textContent=timeLabel(state.arrivalTime);$('tripDuration').textContent=`約${Math.max(1,Math.round((state.durationSec||60)/60))}分`;$('tripAscent').textContent=`+${Math.round(state.totalAscentM||0)}m`}
function renderElevationChart(){const svg=$('elevationChart'),frames=state.route?.frames||[];if(!svg)return;if(!frames.length||!frames.some(f=>Number.isFinite(f.elevation))){svg.innerHTML='<text x="18" y="70" fill="rgba(255,255,255,.45)" font-size="10">標高を取得中…</text>';return}const w=360,h=130,pad=18,vals=frames.map(f=>Number.isFinite(f.elevation)?f.elevation:0),min=Math.min(...vals),max=Math.max(...vals),span=Math.max(1,max-min),total=Math.max(1,state.route.totalDistanceM),pts=frames.map(f=>{const x=pad+(w-pad*2)*(f.distanceFromStartM/total),y=h-pad-(h-pad*2)*((f.elevation-min)/span);return[x,y]}),line=pts.map((p,i)=>`${i?'L':'M'}${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(' '),area=`${line} L${pts.at(-1)[0]},${h-pad} L${pts[0][0]},${h-pad} Z`;svg.innerHTML=`<defs><linearGradient id="eg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="rgba(124,242,200,.32)"/><stop offset="1" stop-color="rgba(124,242,200,0)"/></linearGradient></defs><path d="${area}" fill="url(#eg)"/><path d="${line}" fill="none" stroke="rgba(255,255,255,.9)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><line x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}" stroke="rgba(255,255,255,.12)"/><text x="${pad}" y="${h-2}" fill="rgba(255,255,255,.45)" font-size="9">0</text><text x="${w-pad}" y="${h-2}" text-anchor="end" fill="rgba(255,255,255,.45)" font-size="9">${distanceLabel(total)}</text><text x="${pad}" y="12" fill="rgba(255,255,255,.45)" font-size="9">${Math.round(max)}m</text><text x="${pad}" y="${h-pad-4}" fill="rgba(255,255,255,.45)" font-size="9">${Math.round(min)}m</text>`}
function updateTripReadyState(){if(!$('tripStart'))return;const ready=!!state.route&&!!state.provider&&state.preloaded.size>=Math.min(PRELOAD_MIN,state.route.frames.length);$('tripStart').disabled=!ready;if(ready){const routeInfo=state.routeCacheHit?'ルート即時復元':`ルート ${(state.routeResolveMs/1000).toFixed(1)}秒`;$('prepText').textContent=`出発準備OK ・ ${routeInfo} ・ ${state.preloaded.size}枚先読み済み`;$('prepBar').style.width='100%'}}
function resetPlanner(){stopPlayback('route-reset',true);destroyViewer();state.preloadGeneration++;state.route=null;state.provider=null;state.providerStats=null;state.start=null;state.goal=null;state.pendingGoal=null;state.selectedPlace=null;state.stage='goal';state.routeCacheHit=false;state.routeResolveMs=null;state.routeSearchMs=null;state.routeSearchApiRequests=0;state.routeSearchRadiusM=0;state.routeSearchCandidates=0;state.preloaded.clear();state.completed=false;state.goalMarker?.remove();state.startMarker?.remove();state.goalMarker=state.startMarker=null;clearResolvedRoute();$('poiCard').hidden=true;$('tripSheet').hidden=true;$('routeSearchCard').hidden=true;$('routeSearchRetry').hidden=true;$('prepArea').hidden=true;plannerStatus('行き先を選ぶ','観光地や山のアイコンをタップ');state.poiCacheKey='';syncPlannerUI();refreshPOIs()}
async function handleMapBackgroundClick(){if(state.stage==='goal')closeSearch()}
function initMap(){state.map=new maplibregl.Map({container:'routeMap',style:'https://tiles.openfreemap.org/styles/liberty',center:[135.7594,35.0068],zoom:12.5,attributionControl:false});state.map.addControl(new maplibregl.NavigationControl({showCompass:true}),'top-right');state.map.addControl(new maplibregl.GeolocateControl({positionOptions:{enableHighAccuracy:true},trackUserLocation:false,showUserHeading:true}),'top-right');state.map.on('load',refreshPOIs);state.map.on('move',updateStartPickerCoord);state.map.on('moveend',()=>{updateStartPickerCoord();setTimeout(refreshPOIs,150)});state.map.on('click',handleMapBackgroundClick)}
