/* Streetview Journey v0.1.50 CENTER LOCK + guarded Motion FOE / Static VP */
(()=>{
'use strict';
if(window.__journeyCenterDecisionInstalled)return;window.__journeyCenterDecisionInstalled=true;
const VERSION='0.1.50',MG={confidence:.55,inlierRatio:.50,coverage:.40,medErr:3,vectors:10,maxModelAgreement:.22,maxTranslationDominance:3.6},SG={confidence:.55,lineCount:8,inlierRatio:.45,maxSpread:.12},TR=3,TMIN=3,TSPREAD=.08,AGREE=.10,MINOFF=.025,MAXOFF=.08,MAGAGREE=.05,SIDE=45,SIDE_CLEAR=70,SIDE_RATIO=.70,AHEAD=5;
const NativeWorker=window.Worker,NativePost=NativeWorker?.prototype?.postMessage,nativeDraw=CanvasRenderingContext2D.prototype.drawImage,nativeSetTimeout=window.setTimeout.bind(window);
const motion=new Map(),statics=new Map(),urls=new Map(),images=new Map(),accepted=new Map(),motionPending=new Set(),staticPending=new Set();
let frames=[],selection=null,generation=0,worker=null,errors=0,lastMotion=null,lastStatic=null,diagValue=null,debug=false,bridgeWrapped=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rad=v=>v*Math.PI/180,deg=v=>v*180/Math.PI;
const median=a=>{const s=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!s.length)return null;const m=s.length>>1;return s.length&1?s[m]:(s[m-1]+s[m])*.5},mad=(a,m=median(a))=>Number.isFinite(m)?median(a.filter(Number.isFinite).map(v=>Math.abs(v-m))):null,angle=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)?((b-a+540)%360)-180:null;
const norm=v=>{try{const u=new URL(String(v||''),location.href);u.searchParams.delete('analysis');u.searchParams.delete('axisv');return u.href}catch{return String(v||'').replace(/([?&])(analysis|axisv)=[^&]+(&|$)/g,'$1').replace(/[?&]$/,'')}};
function xy(f){if(Number.isFinite(Number(f?.lat))&&Number.isFinite(Number(f?.lng)))return{lat:Number(f.lat),lng:Number(f.lng)};const c=f?.computed_geometry?.coordinates;return Array.isArray(c)&&c.length>1?{lat:Number(c[1]),lng:Number(c[0])}:null}
function dist(a,b){const A=xy(a),B=xy(b);if(!A||!B)return Infinity;const p1=rad(A.lat),p2=rad(B.lat),dp=p2-p1,dl=rad(B.lng-A.lng),s=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 12742000*Math.atan2(Math.sqrt(s),Math.sqrt(Math.max(0,1-s)))}
function bear(a,b){const A=xy(a),B=xy(b);if(!A||!B)return null;const p1=rad(A.lat),p2=rad(B.lat),dl=rad(B.lng-A.lng),y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(deg(Math.atan2(y,x))+360)%360}
function sphere(f){const p=String(f?.projection||f?.camera_type||'').toUpperCase();return p==='SPHERE'||p.includes('EQUIRECT')||f?.is_pano===true||Number(f?.fieldOfView)>=180}
function projection(f){if(sphere(f))return'SPHERE';const p=String(f?.projection||f?.camera_type||'').toUpperCase();return p.includes('RECTILINEAR')?'RECTILINEAR':p.includes('PERSPECTIVE')?'PERSPECTIVE':p||'PERSPECTIVE'}
function heading(f){for(const v of [f?.computed_compass_angle,f?.computedHeading,f?.compass_angle,f?.heading,f?.projectionYaw]){const n=Number(v);if(Number.isFinite(n))return((n%360)+360)%360}return null}
function travelIn(list,i){const c=list[i];if(!c)return null;const seq=String(c?.sequenceId||c?.sequence?.id||'');let sx=0,sy=0,sw=0;for(let s=1;s<=10&&i+s<list.length;s++){const n=list[i+s],ns=String(n?.sequenceId||n?.sequence?.id||'');if(seq&&ns&&ns!==seq)break;const d=dist(c,n),br=bear(c,n);if(!Number.isFinite(d)||d<.7||!Number.isFinite(br))continue;const w=Math.min(d,18)/Math.sqrt(s);sx+=Math.cos(rad(br))*w;sy+=Math.sin(rad(br))*w;sw+=w;if(d>=22)break}for(let s=1;s<=5&&i-s>=0;s++){const p=list[i-s],ps=String(p?.sequenceId||p?.sequence?.id||'');if(seq&&ps&&ps!==seq)break;const d=dist(p,c),br=bear(p,c);if(!Number.isFinite(d)||d<.7||!Number.isFinite(br))continue;const w=.55*Math.min(d,14)/(1+.35*(s-1));sx+=Math.cos(rad(br))*w;sy+=Math.sin(rad(br))*w;sw+=w}return sw?(deg(Math.atan2(sy,sx))+360)%360:null}
const travel=i=>travelIn(frames,i);
function sphereAnchor(i){const tr=travel(i),hd=heading(frames[i]);if(!Number.isFinite(tr)||!Number.isFinite(hd))return 50;return((50+angle(hd,tr)/3.6)%100+100)%100}
function sideAssessment(list=frames){const ds=[];for(let i=0;i<list.length;i++){const tr=travelIn(list,i),hd=heading(list[i]);if(Number.isFinite(tr)&&Number.isFinite(hd))ds.push(Math.abs(angle(hd,tr)))}const med=median(ds),r45=ds.filter(v=>v>=SIDE).length/Math.max(1,ds.length),r70=ds.filter(v=>v>=SIDE_CLEAR).length/Math.max(1,ds.length),confidence=clamp(Math.max((r45-.45)/.40,(r70-.20)/.45),0,1);return{samples:ds.length,medianDifference:med,over45Ratio:r45,over70Ratio:r70,confidence,side:ds.length>=4&&r45>=SIDE_RATIO}}
function mGate(r){const q=[],k=String(r?.kind||'');if(!r)q.push('missing');else{if(['low-texture','safe-error','invalid','size','none'].includes(k))q.push(k);if(k.startsWith('side-flow'))q.push('side-flow');if(k.includes('disagree'))q.push('full-residual-disagree');if((+r.confidence||0)<MG.confidence)q.push('confidence');if((+r.inlierRatio||0)<MG.inlierRatio)q.push('inlierRatio');if((+r.coverage||0)<MG.coverage)q.push('coverage');if(!Number.isFinite(+r.medErr)||+r.medErr>MG.medErr)q.push('medErr');if((+r.vectors||0)<MG.vectors)q.push('vectors');if(Number.isFinite(+r.modelAgreement)&&+r.modelAgreement>MG.maxModelAgreement)q.push('modelAgreement');if(Number.isFinite(+r.translationDominance)&&+r.translationDominance>MG.maxTranslationDominance)q.push('translationDominance');if(!Number.isFinite(+r.centerX))q.push('centerX')}return{high:!q.length,reasons:q}}
function sGate(r){const q=[],k=String(r?.kind||'');if(!r)q.push('missing');else{if(['safe-error','invalid','size','low-lines','no-consensus'].includes(k))q.push(k);if((+r.confidence||0)<SG.confidence)q.push('confidence');if((+r.lineCount||0)<SG.lineCount)q.push('lineCount');if((+r.inlierRatio||0)<SG.inlierRatio)q.push('inlierRatio');if(!Number.isFinite(+r.spread)||+r.spread>SG.maxSpread)q.push('spread');if(!Number.isFinite(+r.staticVpX))q.push('staticVpX')}return{high:!q.length,reasons:q}}
function temporal(i){const a=[];for(let k=Math.max(0,i-TR);k<=Math.min(frames.length-2,i+TR);k++){const r=motion.get(k);if(mGate(r).high)a.push(r)}if(a.length<TMIN)return{stable:false,x:null,confidence:0,spread:null,samples:a.length,reason:'TEMPORAL_TOO_FEW'};const xs=a.map(r=>+r.centerX),m=median(xs),sigma=1.4826*(mad(xs,m)||0),gate=Math.max(.025,sigma*2.8),ins=a.filter(r=>Math.abs(+r.centerX-m)<=gate),ix=ins.map(r=>+r.centerX),x=median(ix),spread=1.4826*(mad(ix,x)||0),stable=ins.length>=TMIN&&spread<=TSPREAD;return{stable,x,confidence:median(ins.map(r=>+r.confidence))||0,spread,samples:ins.length,total:a.length,reason:stable?null:'TEMPORAL_SPREAD'}}
function cropMargin(i){const f=frames[i],iw=+f?.width,ih=+f?.height,vw=Math.max(1,innerWidth||390),vh=Math.max(1,innerHeight||844);if(!(iw>0&&ih>0))return .18;const ratio=iw/ih>vw/vh?(iw/ih)/(vw/vh):1;return clamp(.5-1/(2*ratio),0,.49)}
function smoothOffset(i,o){const p=accepted.get(i-1);if(Number.isFinite(p))o=p+clamp(o-p,-.015,.015);accepted.set(i,o);return o}
function decide(i){const f=frames[i];if(!f)return{frame:i,projection:'UNKNOWN',anchor:.5,centerMode:'UNKNOWN',centerFallbackReason:'FRAME_MISSING'};if(sphere(f))return{frame:i,projection:'SPHERE',anchor:sphereAnchor(i)/100,centerMode:'SPHERE_METADATA_YAW',centerFallbackReason:null,centerOffsetApplied:0};const mr=motion.get(i),mg=mGate(mr),tm=temporal(i),sr=statics.get(i),sg=sGate(sr),mx=tm.stable?tm.x:(mg.high?+mr.centerX:null),sx=sg.high?+sr.staticVpX:null,agree=Number.isFinite(mx)&&Number.isFinite(sx)&&Math.abs(mx-sx)<=AGREE,tr=travel(i),hd=heading(f),hdiff=Number.isFinite(tr)&&Number.isFinite(hd)?Math.abs(angle(hd,tr)):null,side=sideAssessment(),front=Number.isFinite(hdiff)&&hdiff<=30,unavailable=!mg.high&&!sg.high,base={frame:i,projection:projection(f),anchor:.5,centerMode:'CENTER_LOCK',originalCenterX:50,motionFoeX:Number.isFinite(mx)?mx*100:null,motionFoeStable:tm.stable,motionTemporalSpread:tm.spread,motionTemporalSamples:tm.samples,staticVpX:Number.isFinite(sx)?sx*100:null,foeStaticAgreement:agree,travelBearing:tr,cameraHeading:hd,headingDifference:hdiff,sideCameraConfidence:side.confidence,vanishingPointUnavailable:unavailable,centerOffsetApplied:0};if(side.side)return{...base,centerMode:'SIDE_CAMERA',centerFallbackReason:'SIDE_CAMERA_SEQUENCE'};if(agree&&tm.stable&&mg.high&&sg.high){const dm=mx-.5,ds=sx-.5,w=(mx*(tm.confidence||.55)+sx*(+sr.confidence||.55))/Math.max(.001,(tm.confidence||.55)+(+sr.confidence||.55)),off=w-.5,same=dm*ds>0,mag=Math.abs(Math.abs(dm)-Math.abs(ds))<=MAGAGREE;if(Math.abs(dm)<=.06&&Math.abs(ds)<=.06)return{...base,centerMode:'CENTER_CONFIRMED',centerFallbackReason:null};if(same&&mag&&Math.abs(off)>=MINOFF&&Math.abs(off)<=MAXOFF){if(cropMargin(i)>=Math.abs(off)+.01){const a=clamp(.5+smoothOffset(i,off),.42,.58);return{...base,anchor:a,centerMode:'SMALL_OFFSET_CONFIRMED',centerOffsetApplied:(a-.5)*100,centerFallbackReason:null}}return{...base,centerFallbackReason:'INSUFFICIENT_CROP_MARGIN'}}return{...base,centerFallbackReason:'OFFSET_NOT_SMALL_OR_NOT_COHERENT'}}if(Number.isFinite(mx)&&mg.high&&tm.stable&&Math.abs(mx-.5)<=.05&&front)return{...base,centerMode:'CENTER_CONFIRMED',centerFallbackReason:null};if(Number.isFinite(sx)&&sg.high&&Math.abs(sx-.5)<=.05&&front)return{...base,centerMode:'CENTER_CONFIRMED',centerFallbackReason:null};let reason='CENTER_EVIDENCE_INSUFFICIENT';if(Number.isFinite(mx)&&Number.isFinite(sx)&&!agree)reason='MOTION_STATIC_DISAGREE';else if(!tm.stable&&mg.high)reason=tm.reason||'MOTION_TEMPORAL_UNSTABLE';else if(unavailable)reason='VANISHING_POINT_UNAVAILABLE';else if(!mg.high&&sg.high)reason='MOTION_INVALID';else if(mg.high&&!sg.high)reason='STATIC_INVALID';return{...base,centerFallbackReason:reason}}
function invCenter(ctx){const cx=ctx.canvas.width*.5,cy=ctx.canvas.height*.5,m=ctx.getTransform?.();if(!m)return{x:cx,y:cy};const det=m.a*m.d-m.b*m.c;if(!Number.isFinite(det)||Math.abs(det)<1e-8)return{x:cx,y:cy};const X=cx-m.e,Y=cy-m.f;return{x:(m.d*X-m.c*Y)/det,y:(-m.b*X+m.a*Y)/det}}
function frameFor(im){if(!(im instanceof HTMLImageElement))return null;const i=urls.get(norm(im.currentSrc||im.src));return Number.isFinite(i)?i:null}
CanvasRenderingContext2D.prototype.drawImage=function(im,...a){try{if(a.length===4&&this.canvas?.width>40&&this.canvas?.height>40){const i=frameFor(im);if(Number.isFinite(i)&&!sphere(frames[i])){let[x,y,w,h]=a;if([x,y,w,h].every(Number.isFinite)&&w>0&&h>0){const d=decide(i),p=invCenter(this);a=[p.x-w*(Number.isFinite(d.anchor)?d.anchor:.5),p.y-h*.5,w,h];publish(i,d)}}}}catch{}return nativeDraw.call(this,im,...a)};
function gray(im,w=160){const ratio=im.naturalWidth/Math.max(1,im.naturalHeight),h=clamp(Math.round(w/Math.max(.65,ratio)),72,128),c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d',{willReadFrequently:true});nativeDraw.call(g,im,0,0,w,h);const d=g.getImageData(0,0,w,h).data,o=new Uint8Array(w*h);for(let k=0,j=0;k<o.length;k++,j+=4)o[k]=Math.round(d[j]*.299+d[j+1]*.587+d[j+2]*.114);return{w,h,o}}
function load(u){const k=norm(u);if(images.has(k))return images.get(k);let p;p=new Promise((res,rej)=>{const im=new Image();im.crossOrigin='anonymous';im.referrerPolicy='no-referrer';im.decoding='async';im.onload=()=>res(im);im.onerror=()=>{images.delete(k);rej(new Error('axis image load'))};im.src=`${k}${k.includes('?')?'&':'?'}axisv=${VERSION}`});images.set(k,p);return p}
async function submitMotion(i,g=generation){if(g!==generation||!worker||i<0||i>=frames.length-1||motionPending.has(i))return;motionPending.add(i);try{const[A,B]=await Promise.all([load(frames[i].url),load(frames[i+1].url)]);if(g!==generation)return;const a=gray(A),b=gray(B,a.w),h=Math.min(a.h,b.h),len=a.w*h,aa=a.o.slice(0,len),bb=b.o.slice(0,len);NativePost.call(worker,{type:'axis',space:'full-image',frame:i,generation:g,width:a.w,height:h,grayA:aa.buffer,grayB:bb.buffer,seed:i*173+len},[aa.buffer,bb.buffer])}catch{}finally{motionPending.delete(i)}}
async function submitStatic(i,g=generation){if(g!==generation||!worker||i<0||i>=frames.length||staticPending.has(i)||sphere(frames[i]))return;staticPending.add(i);try{const im=await load(frames[i].url);if(g!==generation)return;const a=gray(im),buf=a.o;NativePost.call(worker,{type:'static',frame:i,generation:g,width:a.w,height:a.h,gray:buf.buffer,seed:i*257+a.w*a.h},[buf.buffer])}catch{}finally{staticPending.delete(i)}}
function warm(i){const g=generation;for(let k=Math.max(0,i-3);k<=Math.min(frames.length-2,i+AHEAD);k++)if(!motion.has(k))submitMotion(k,g);for(let k=Math.max(0,i-2);k<=Math.min(frames.length-1,i+AHEAD);k++)if(!statics.has(k))submitStatic(k,g)}
function reset(fs,sel=null){generation++;frames=Array.isArray(fs)?fs:[];selection=sel||null;motion.clear();statics.clear();accepted.clear();urls.clear();images.clear();motionPending.clear();staticPending.clear();lastMotion=lastStatic=null;for(let i=0;i<frames.length;i++)for(const u of [frames[i]?.url,frames[i]?.sourceUrl,frames[i]?.raw256Url])if(u)urls.set(norm(u),i);Object.assign(state,{generation,routeFrames:frames.length,routeSelection:selection,latestFull:null,latestStatic:null,appliedFrame:null,metadataAnchor:50,effectiveAnchor:50,anchorSource:'CENTER_LOCK'});try{NativePost?.call(worker,{type:'reset',generation})}catch{}for(const i of [...new Set([0,1,2,Math.round((frames.length-1)*.25),Math.round((frames.length-1)*.5),Math.round((frames.length-1)*.75),frames.length-1].filter(i=>i>=0&&i<frames.length))]){submitStatic(i,generation);if(i<frames.length-1)submitMotion(i,generation)}}
if(Response?.prototype?.json){const raw=Response.prototype.json;Response.prototype.json=async function(...a){const data=await raw.apply(this,a),isImagery=String(this.url||'').includes('/api/imagery');if(isImagery&&Array.isArray(data?.frames)){const side=sideAssessment(data.frames);data.selection={...(data.selection||{}),centerPolicy:'source-center-50-default',centerAnalysisNonBlocking:true,sideCameraAssessment:side,journeySuitability:side.side?'low-side-camera':'normal'};reset(data.frames,data.selection)}return data}}
if(NativeWorker&&NativePost){try{worker=new NativeWorker(`/travel-axis-worker.js?v=${VERSION}`);worker.addEventListener('message',e=>{const m=e.data||{},r=m.result;if(m.type==='axis-ready'){state.worker=m.engine||'tile-flow+static-vp';state.workerReady=true;return}if(!r||r.generation!==generation||!Number.isFinite(r.frame))return;if(m.type==='axis-result'&&r.space==='full-image'){motion.set(r.frame,r);lastMotion={...r};state.latestFull=lastMotion;for(let k=r.frame-4;k<=r.frame+4;k++)accepted.delete(k);publish(r.frame)}if(m.type==='static-result'){statics.set(r.frame,r);lastStatic={...r};state.latestStatic=lastStatic;for(let k=r.frame-2;k<=r.frame+2;k++)accepted.delete(k);publish(r.frame)}});worker.addEventListener('error',()=>{errors++;state.worker='fallback';state.workerReady=false;state.errors=errors})}catch{errors++;}};
function normalizeVectors(vs,cols=4,rows=5){if(!Array.isArray(vs)||!vs.length)return{vectors:vs||[],x:0,y:0};const r=Math.floor(rows/2),c0=Math.floor((cols-1)/2),c1=Math.ceil((cols-1)/2),base=vs.filter(v=>v&&v.row===r&&(v.col===c0||v.col===c1)),src=base.length?base:vs.filter(v=>+v?.confidence>=.018),x=median(src.map(v=>+v.vx))||0,y=median(src.map(v=>+v.vy))||0;return{vectors:vs.map(v=>({...v,vx:(+v.vx||0)-x,vy:(+v.vy||0)-y})),x,y}}
function bridgeNormalize(){if(bridgeWrapped)return;const b=window.__journeyOpticalBridge;if(!b||typeof b.getPreparedPair!=='function')return;const fn=b.getPreparedPair.bind(b);b.getPreparedPair=i=>{const p=fn(i);if(!p||sphere(frames[+i]))return p;const cfg=b.getTileConfig?.()||{cols:4,rows:5},n=normalizeVectors(p.vs,+cfg.cols||4,+cfg.rows||5);if(diagValue)Object.assign(diagValue,{opticalCenterFlowX:n.x,opticalCenterFlowY:n.y,opticalCenterNormalized:true});return{...p,vs:n.vectors,centerFlowRemoved:{x:n.x,y:n.y}}};bridgeWrapped=true}
function publish(i,d=decide(i)){if(!Number.isFinite(i)||!frames[i])return null;const mr=motion.get(i),sr=statics.get(i),tm=temporal(i),mg=mGate(mr),sg=sGate(sr),p={frameIndex:i,projection:d.projection||projection(frames[i]),originalCenterX:50,finalAnchorX:(Number.isFinite(d.anchor)?d.anchor:.5)*100,centerMode:d.centerMode||'CENTER_LOCK',motionFoeX:Number.isFinite(d.motionFoeX)?d.motionFoeX:(Number.isFinite(+mr?.centerX)?+mr.centerX*100:null),motionFoeConfidence:+mr?.confidence||0,motionFoeVectors:+mr?.vectors||0,motionFoeInlierRatio:+mr?.inlierRatio||0,motionFoeCoverage:+mr?.coverage||0,motionFoeMedErr:Number.isFinite(+mr?.medErr)?+mr.medErr:null,motionFoeStable:tm.stable,motionFoeTemporalSpread:tm.spread,motionFoeGate:mg.high,motionFoeGateReasons:mg.reasons,staticVpX:Number.isFinite(+sr?.staticVpX)?+sr.staticVpX*100:null,staticVpY:Number.isFinite(+sr?.staticVpY)?+sr.staticVpY*100:null,staticVpConfidence:+sr?.confidence||0,staticVpLineCount:+sr?.lineCount||0,staticVpInlierRatio:+sr?.inlierRatio||0,staticVpSpread:Number.isFinite(+sr?.spread)?+sr.spread:null,staticVpGate:sg.high,staticVpGateReasons:sg.reasons,foeStaticAgreement:!!d.foeStaticAgreement,travelBearing:Number.isFinite(d.travelBearing)?d.travelBearing:travel(i),cameraHeading:Number.isFinite(d.cameraHeading)?d.cameraHeading:heading(frames[i]),headingDifference:Number.isFinite(d.headingDifference)?d.headingDifference:null,sideCameraConfidence:+d.sideCameraConfidence||sideAssessment().confidence,centerOffsetApplied:+d.centerOffsetApplied||0,centerFallbackReason:d.centerFallbackReason||null,vanishingPointUnavailable:!!d.vanishingPointUnavailable};Object.assign(state,{appliedFrame:i,metadataAnchor:sphere(frames[i])?sphereAnchor(i):50,effectiveAnchor:p.finalAnchorX,anchorSource:p.centerMode,currentDecision:p});if(diagValue)Object.assign(diagValue,p,{version:VERSION,travelAxis:'center-lock-v1',travelAxisState:state});return p}
function overlay(){let c=document.getElementById('journeyCenterDebugOverlay');if(c)return c;const v=document.getElementById('viewer');if(!v)return null;c=document.createElement('canvas');c.id='journeyCenterDebugOverlay';Object.assign(c.style,{position:'absolute',inset:'0',width:'100%',height:'100%',zIndex:'7',pointerEvents:'none',display:'none'});v.appendChild(c);return c}
function drawDebug(){const c=overlay();if(!c)return;c.style.display=debug?'block':'none';if(!debug)return;const r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,Math.round(r.width*dpr));c.height=Math.max(1,Math.round(r.height*dpr));const g=c.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,r.width,r.height);const i=clamp(+window.__journeyPlaybackState?.index||0,0,Math.max(0,frames.length-1)),d=decide(i),mr=motion.get(i),sr=statics.get(i),line=(x,color,w=1)=>{g.strokeStyle=color;g.lineWidth=w;g.beginPath();g.moveTo(x*r.width,0);g.lineTo(x*r.width,r.height);g.stroke()};line(.5,'rgba(255,255,255,.92)',1.5);if(Number.isFinite(+mr?.centerX)){g.fillStyle='rgba(80,160,255,.98)';g.beginPath();g.arc(clamp(+mr.centerX,0,1)*r.width,r.height*.34,6,0,Math.PI*2);g.fill()}if(Number.isFinite(+sr?.staticVpX)){g.fillStyle='rgba(255,220,70,.98)';g.beginPath();g.arc(clamp(+sr.staticVpX,0,1)*r.width,r.height*.42,6,0,Math.PI*2);g.fill()}line(clamp(d.anchor,0,1),'rgba(255,75,75,.96)',2);g.fillStyle='rgba(0,0,0,.68)';g.fillRect(8,8,Math.min(r.width-16,330),48);g.fillStyle='#fff';g.font='11px -apple-system,sans-serif';g.fillText(`${d.centerMode} anchor ${(d.anchor*100).toFixed(1)}%`,14,26);g.fillText(`FOE ${Number.isFinite(+mr?.centerX)?(+mr.centerX*100).toFixed(1):'—'} / VP ${Number.isFinite(+sr?.staticVpX)?(+sr.staticVpX*100).toFixed(1):'—'} / ${d.centerFallbackReason||'confirmed'}`,14,43)}
function debugButton(){const log=document.getElementById('journeyDiag')?.querySelector('.jd-log');if(!log||document.getElementById('jdCenterDebug'))return;const b=document.createElement('button');b.id='jdCenterDebug';b.type='button';b.style.pointerEvents='auto';const label=()=>b.textContent=`Center Debug ${debug?'ON':'OFF'}`;label();b.onclick=e=>{e.preventDefault();debug=!debug;try{localStorage.setItem('streetview:center-debug',debug?'1':'0')}catch{}label();drawDebug()};log.appendChild(b)}
try{debug=localStorage.getItem('streetview:center-debug')==='1'}catch{}
const state=window.__journeyTravelAxis={version:VERSION,mode:'RECTILINEAR source-center lock + guarded multi-signal confirmation',worker:'starting',workerReady:false,generation:0,routeFrames:0,routeSelection:null,latestFull:null,latestStatic:null,appliedFrame:null,metadataAnchor:50,effectiveAnchor:50,anchorSource:'CENTER_LOCK',errors:0,motionGate:MG,staticGate:SG,temporalPolicy:{radius:TR,minPairs:TMIN,maxSpread:TSPREAD},offsetPolicy:{agreement:AGREE,min:42,max:58},anchorForFrame(i,fallback=50){return Number.isFinite(i)&&frames[i]?decide(i).anchor*100:fallback},decisionForFrame:i=>decide(+i),setDebug(v){debug=!!v;drawDebug();return debug},snapshot(){const side=sideAssessment();return{version:VERSION,mode:this.mode,worker:this.worker,workerReady:this.workerReady,generation,routeFrames:frames.length,routeSelection:selection,motionResults:motion.size,staticResults:statics.size,latestFull:lastMotion,latestStatic:lastStatic,appliedFrame:this.appliedFrame,metadataAnchor:this.metadataAnchor,effectiveAnchor:this.effectiveAnchor,anchorSource:this.anchorSource,currentDecision:this.currentDecision||null,sideCamera:side.side,sideCameraConfidence:side.confidence,headingDifferenceMedian:side.medianDifference,headingOver45Ratio:side.over45Ratio,errors,debugEnabled:debug}}};
try{Object.defineProperty(window,'__journeyDiagnostics',{configurable:true,get(){return diagValue},set(v){diagValue=v;if(v&&typeof v==='object'){v.version=VERSION;v.travelAxis='center-lock-v1';v.travelAxisState=state}}})}catch{}
function onFrame(i){if(!Number.isFinite(i))return;warm(i);publish(i);bridgeNormalize();drawDebug()}
addEventListener('journey-playback-started',e=>onFrame(+e.detail?.index||0));addEventListener('journey-frame-presented',e=>onFrame(+e.detail?.index));addEventListener('resize',drawDebug);nativeSetTimeout(()=>{debugButton();bridgeNormalize()},120);setInterval(()=>{debugButton();bridgeNormalize();const i=+window.__journeyPlaybackState?.index;if(Number.isFinite(i)&&frames.length)publish(clamp(i,0,frames.length-1));drawDebug()},250);
})();
