/* Streetview Journey v0.2.2 strict CENTER LOCK + profile router */
(()=>{
'use strict';
if(window.__journeyCenterDecisionInstalled)return;window.__journeyCenterDecisionInstalled=true;
const VERSION='0.2.2',nativeDraw=CanvasRenderingContext2D.prototype.drawImage;
const norm=v=>{try{const u=new URL(String(v||''),location.href);u.searchParams.delete('analysis');u.searchParams.delete('axisv');return u.href}catch{return String(v||'')}};
let frames=[],sig='',profileName='UNKNOWN',appliedFrame=null;
const urls=new Map();
function route(){if(window.__journeySelectedRoute)return window.__journeySelectedRoute;try{return JSON.parse(sessionStorage.getItem('streetview:journey-route')||'null')}catch{return null}}
function profile(){const r=route();let p=String(r?.journeyProfile||r?.routeProfile||r?.profile||'').trim().toUpperCase();if(!p){const id=String(r?.fixedTestRoute?.routeId||r?.destination?.testRouteType||'').toLowerCase();p=id==='road'?'ROAD':id==='sidewalk'?'SIDEWALK':id==='mountain'?'MOUNTAIN':id==='rail'?'RAIL':''}if(!p)p=String((window.__journeyStreamState?.frames||r?.frames||[])[0]?.journeyProfile||'').toUpperCase();return p||'UNKNOWN'}
function routeFrames(){const s=window.__journeyStreamState?.frames,r=route()?.frames;return Array.isArray(s)&&s.length?s:(Array.isArray(r)?r:[])}
function sphere(f){const p=String(f?.projection||f?.camera_type||'').toUpperCase();return p==='SPHERE'||p.includes('EQUIRECT')||f?.is_pano===true||Number(f?.fieldOfView)>=180}
function projection(f){if(sphere(f))return'SPHERE';const p=String(f?.projection||f?.camera_type||'').toUpperCase();return p.includes('RECTILINEAR')?'RECTILINEAR':p.includes('PERSPECTIVE')?'PERSPECTIVE':p||'PERSPECTIVE'}
function sync(force=false){const list=routeFrames(),p=profile(),s=`${p}:${list.length}:${list[0]?.id||''}:${list[list.length-1]?.id||''}`;if(!force&&s===sig)return;frames=list;profileName=p;sig=s;urls.clear();for(let i=0;i<frames.length;i++)for(const u of [frames[i]?.url,frames[i]?.sourceUrl,frames[i]?.raw2048Url,frames[i]?.raw1024Url,frames[i]?.raw256Url])if(u)urls.set(norm(u),i);for(const f of frames){if(!f||sphere(f))continue;f.photoCenterX=50;f.photoCenterY=50;f.presentationCenterLocked=true;f.directionPresentationSeparated=true}const r=route();if(r)r.presentationProfile={...(r.presentationProfile||{}),photoCenterX:50,photoCenterY:50,strictPhotoCenter:true,centerTranslation:false,directionPresentationSeparated:true};loadModule()}
function loadModule(){const p=profileName||profile();let id=null,src=null;if(p==='ROAD'||p==='UNKNOWN'||p==='AUTO'){id='journeyRoadDirectionModule';src=`/road-direction.js?v=${VERSION}`}else if(p==='SIDEWALK'){id='journeySidewalkDirectionModule';src=`/pedestrian-axis-fix.js?v=${VERSION}`}else if(p==='MOUNTAIN'){id='journeyMountainDirectionModule';src=`/mountain-axis-fix.js?v=${VERSION}`}if(!id||!src||document.getElementById(id))return;const s=document.createElement('script');s.id=id;s.src=src;s.async=false;document.head.appendChild(s)}
function invCenter(ctx){const cx=ctx.canvas.width*.5,cy=ctx.canvas.height*.5,m=ctx.getTransform?.();if(!m)return{x:cx,y:cy};const det=m.a*m.d-m.b*m.c;if(!Number.isFinite(det)||Math.abs(det)<1e-8)return{x:cx,y:cy};const X=cx-m.e,Y=cy-m.f;return{x:(m.d*X-m.c*Y)/det,y:(-m.b*X+m.a*Y)/det}}
function frameFor(im){if(!(im instanceof HTMLImageElement))return null;const i=urls.get(norm(im.currentSrc||im.src));return Number.isFinite(i)?i:null}
function publish(i){if(!frames[i])return null;appliedFrame=i;const p={frameIndex:i,profile:profileName,projection:projection(frames[i]),originalCenterX:50,originalCenterY:50,finalAnchorX:50,finalAnchorY:50,centerMode:sphere(frames[i])?'SPHERE_UNCHANGED':'CENTER_LOCK',centerOffsetApplied:0};Object.assign(state,{profile:profileName,routeFrames:frames.length,appliedFrame:i,effectiveAnchor:50,currentDecision:p});const d=window.__journeyDiagnostics;if(d&&typeof d==='object')Object.assign(d,p,{travelAxis:'strict-center-lock-profile-router',travelAxisState:state});return p}
CanvasRenderingContext2D.prototype.drawImage=function(im,...a){try{if(a.length===4&&this.canvas?.width>40&&this.canvas?.height>40){sync();const i=frameFor(im);if(Number.isFinite(i)&&!sphere(frames[i])){const[x,y,w,h]=a;if([x,y,w,h].every(Number.isFinite)&&w>0&&h>0){const p=invCenter(this);a=[p.x-w*.5,p.y-h*.5,w,h];publish(i)}}}}catch{}return nativeDraw.call(this,im,...a)};
const state=window.__journeyTravelAxis={version:VERSION,mode:'strict RECTILINEAR/PERSPECTIVE CENTER LOCK + isolated profile router',profile:profile(),routeFrames:0,appliedFrame:null,metadataAnchor:50,effectiveAnchor:50,anchorSource:'CENTER_LOCK',centerPolicy:{x:50,y:50,translationAllowed:false},anchorForFrame(i,fallback=50){sync();return Number.isFinite(i)&&frames[i]&&!sphere(frames[i])?50:fallback},decisionForFrame(i){sync();const f=frames[+i];return f?{frame:+i,profile:profileName,projection:projection(f),anchor:.5,centerX:50,centerY:50,centerMode:sphere(f)?'SPHERE_UNCHANGED':'CENTER_LOCK',centerOffsetApplied:0}:null},snapshot(){sync();return{version:VERSION,mode:this.mode,profile:profileName,routeFrames:frames.length,appliedFrame,effectiveAnchor:50,anchorSource:'CENTER_LOCK',centerPolicy:this.centerPolicy,currentDecision:this.currentDecision||null}}};
function tick(i){sync();loadModule();if(Number.isFinite(i)&&frames[i])publish(i)}
addEventListener('journey-engine-ready',()=>sync(true));addEventListener('journey-playback-started',e=>tick(Number(e.detail?.index??0)));addEventListener('journey-frame-presented',e=>tick(Number(e.detail?.index)));addEventListener('journey-profile-changed',()=>sync(true));
setTimeout(()=>sync(true),20);setInterval(()=>{sync();const i=Number(window.__journeyPlaybackState?.index);if(Number.isFinite(i))tick(i)},300);
})();
