function currentFrame(){return state.route?.frames[state.cursor]||null}
function nextFrame(){return state.route?.frames[state.cursor+1]||null}
function updateTravelHeading(){const a=currentFrame(),b=nextFrame()||state.route?.frames[state.cursor-1];state.currentTravelHeading=a&&b?bearing(a,b):null}
async function readBearing(){if(!state.viewer)return null;try{const b=await state.viewer.getBearing();if(Number.isFinite(b)){state.currentViewHeading=norm360(b);return state.currentViewHeading}}catch{}return null}
function setFrameMetrics(){const f=currentFrame();if(!f)return;state.currentProgress=f.routeProgress;state.currentRouteDistance=f.routeDistance;state.maxProgressSeen=Number.isFinite(state.maxProgressSeen)?Math.max(state.maxProgressSeen,f.routeProgress):f.routeProgress;updateTravelHeading();if(Number.isFinite(state.currentViewHeading)&&Number.isFinite(state.currentTravelHeading)){state.userViewOffset=angleDiff(state.currentViewHeading,state.currentTravelHeading);state.heldOffset=state.userViewOffset}renderDiagnostics()}
async function gentlyPreservePano(offset){if(!state.viewer||state.pointerActive||state.currentProjection!=='360'||!Number.isFinite(state.currentTravelHeading))return;const before=await readBearing();if(!Number.isFinite(before))return;const desired=norm360(state.currentTravelHeading+offset),delta=angleDiff(desired,before);if(Math.abs(delta)<3)return;if(Math.abs(delta)>45)state.viewJumps++;if(Math.abs(delta)>75)return;let center;try{center=await state.viewer.getCenter()}catch{return}if(!Array.isArray(center)||center.length<2)return;state.correcting=true;const startX=Number(center[0]),y=clamp(Number(center[1]),.08,.92),steps=6;for(let i=1;i<=steps;i++){if(state.pointerActive)break;const eased=1-Math.pow(1-i/steps,2),x=((startX+(delta/360)*eased)%1+1)%1;state.viewer.setCenter([x,y]);await sleep(26)}state.correcting=false}
function installViewerEvents(){
  const el=state.viewer.getCanvasContainer?.()||$('mly');el.addEventListener('touchstart',()=>{state.pointerActive=true},{passive:true});el.addEventListener('touchend',()=>{state.pointerActive=false},{passive:true});el.addEventListener('touchcancel',()=>{state.pointerActive=false},{passive:true});
  state.viewer.on('pov',async e=>{const b=await e.target.getBearing().catch(()=>null);if(!Number.isFinite(b))return;state.currentViewHeading=norm360(b);if(Number.isFinite(state.currentTravelHeading)&&(!state.correcting||state.pointerActive)){const off=angleDiff(state.currentViewHeading,state.currentTravelHeading);state.userViewOffset=off;if(state.pointerActive||!state.playing)state.heldOffset=off}renderDiagnostics()});
  state.viewer.on('image',e=>{const image=e?.image;if(image){state.currentProjection=String(image.cameraType||'').toLowerCase()==='spherical'?'360':'Rectilinear';renderDiagnostics()}})
}
async function initializeViewer(){
  if(state.viewer||!state.route||!state.provider)return;const M=window.mapillary;if(!M?.Viewer)throw new Error('MapillaryJS 4.1.2を読み込めませんでした');
  state.cursor=0;state.successfulFrames=0;state.transitionTimes=[];state.cadenceTimes=[];state.logs=[];state.stopReason='initializing';state.maxProgressSeen=null;state.regressionStreak=0;state.reverseEvents=0;state.viewJumps=0;state.deadlineMisses=0;
  state.viewer=new M.Viewer({container:'mly',dataProvider:state.provider,imageTiling:true,transitionMode:M.TransitionMode.Default,component:{cover:false,cache:{depth:CACHE_DEPTH}}});
  try{state.viewer.getComponent('pointer').configure({dragPan:true,scrollZoom:false,touchZoom:true})}catch{}
  installViewerEvents();try{await state.viewer.setFilter(['==','sequenceId',state.route.sequenceId])}catch{}
  setStatus('最初の画像を表示中…');const t0=performance.now(),image=await moveToWithRetry(state.route.frames[0].id,2);state.initialDisplayMs=performance.now()-t0;state.successfulFrames=1;state.currentProjection=String(image?.cameraType||'').toLowerCase()==='spherical'||state.route.frames[0].isPano?'360':'Rectilinear';await readBearing();setFrameMetrics();logFrame();state.stopReason='ready';$('start').disabled=false;$('stop').disabled=true;setStatus(`${state.route.direction} / ${state.route.frames.length}枚。Default transition / 0.8秒基準`);updatePreloadUI();backgroundWarm();renderDiagnostics()
}
async function moveToWithRetry(id,maxAttempts=2){let last;for(let i=0;i<maxAttempts;i++){try{return await state.viewer.moveTo(id)}catch(error){last=error;if(/CancelMapillaryError/i.test(String(error?.name||error)))throw error;if(i+1<maxAttempts)await sleep(180*(i+1))}}throw last}
function reverseGuard(target){if(target.routeDistance>MAX_ROUTE_DISTANCE)return`off-route-${Math.round(target.routeDistance)}m`;const maxSeen=Number.isFinite(state.maxProgressSeen)?state.maxProgressSeen:currentFrame()?.routeProgress,behind=Number.isFinite(maxSeen)?maxSeen-target.routeProgress:0;if(behind>REGRESSION_HARD){state.reverseEvents++;return'route-progress-hard-regression'}if(behind>REGRESSION_SOFT)state.regressionStreak++;else state.regressionStreak=Math.max(0,state.regressionStreak-1);if(state.regressionStreak>=REGRESSION_STREAK_LIMIT){state.reverseEvents++;return'route-progress-sustained-regression'}return null}
async function moveOne(){
  const target=nextFrame();if(!target)return false;const guard=reverseGuard(target);if(guard){stopPlayback(guard);return false}
  const held=Number.isFinite(state.userViewOffset)?state.userViewOffset:0,t0=performance.now();
  try{const image=await moveToWithRetry(target.id,2);const dt=performance.now()-t0;state.lastTransitionMs=dt;state.transitionTimes.push(dt);if(dt>Number($('speed').value))state.deadlineMisses++;state.cursor++;state.successfulFrames++;state.currentProjection=String(image?.cameraType||'').toLowerCase()==='spherical'||target.isPano?'360':'Rectilinear';const now=performance.now();if(Number.isFinite(state.lastDisplayAt)){state.lastCadenceMs=now-state.lastDisplayAt;state.cadenceTimes.push(state.lastCadenceMs)}state.lastDisplayAt=now;setFrameMetrics();await readBearing();await gentlyPreservePano(held);setFrameMetrics();logFrame();backgroundWarm();return true}catch(error){stopPlayback(`moveTo-error: ${error?.message||error}`);return false}
}
async function playback(){
  if(state.playing||!state.viewer)return;const run=++state.moveToken;state.playing=true;state.stopReason='playing';state.lastDisplayAt=performance.now();$('start').disabled=true;$('stop').disabled=false;setStatus(`${Number($('speed').value)/1000}s周期で自動再生中`);
  while(state.playing&&run===state.moveToken&&state.cursor<state.route.frames.length-1){const cycle=performance.now(),ok=await moveOne();if(!ok||!state.playing)break;const interval=Number($('speed').value)||DEFAULT_CADENCE,elapsed=performance.now()-cycle,remain=interval-elapsed;if(remain>0)await sleep(remain)}
  if(state.playing&&state.cursor>=state.route.frames.length-1)stopPlayback('completed-50')
}
function stopPlayback(reason='user-stop',silent=false){state.playing=false;state.moveToken++;state.stopReason=reason;if($('start'))$('start').disabled=!state.viewer;if($('stop'))$('stop').disabled=true;if(!silent&&$('status'))setStatus(reason==='completed-50'?`完了: ${state.successfulFrames}/${state.route?.frames.length||0}枚`:`停止: ${reason}`);renderDiagnostics()}
function destroyViewer(){if(state.viewer){try{state.viewer.remove()}catch{}state.viewer=null}$('mly').innerHTML='';$('start').disabled=true;$('stop').disabled=true}
function logFrame(){const f=currentFrame();state.logs.push({step:state.cursor+1,id:f?.id||null,routeProgress:state.currentProgress,routeDistance:state.currentRouteDistance,travelHeading:state.currentTravelHeading,userViewOffset:state.userViewOffset,currentViewHeading:state.currentViewHeading,imageTransitionMs:state.lastTransitionMs,actualCadenceMs:state.lastCadenceMs,projection:state.currentProjection,preloadAhead:contiguousAhead(),stopReason:state.stopReason})}
function renderDiagnostics(){if(!$('diagGrid'))return;const ps=state.providerStats||{},rows=[['version',VERSION],['frame / step',`${Math.min(state.cursor+1,state.route?.frames.length||0)} / ${state.route?.frames.length||0} (success ${state.successfulFrames})`],['sequenceId',state.route?.sequenceId||'—'],['Next / Prev',state.route?.direction||'—'],['requested cadence',fmt(Number($('speed')?.value)||DEFAULT_CADENCE,0,'ms')],['actual cadence',fmt(state.lastCadenceMs,0,'ms')],['avg cadence',fmt(average(state.cadenceTimes),0,'ms')],['imageTransitionMs',fmt(state.lastTransitionMs,0,'ms')],['avgTransitionMs',fmt(average(state.transitionTimes),0,'ms')],['deadline misses',String(state.deadlineMisses)],['preload ready / target',`${state.preloaded.size} / ${state.preloadTarget||0}`],['preload ready at open',String(state.preloadReadyAtOpen)],['preload rate',fmt(state.preloadRateFps,2,'fps')],['preload wall',fmt(state.preloadWallMs,0,'ms')],['preload avg asset',fmt(average(state.preloadTimes),0,'ms')],['preload failures',String(state.preloadFailures)],['preload ahead',String(contiguousAhead())],['provider buffer hit/miss',`${ps.bufferHit||0} / ${ps.bufferMiss||0}`],['provider mesh hit/miss',`${ps.meshHit||0} / ${ps.meshMiss||0}`],['provider cluster hit/miss',`${ps.clusterHit||0} / ${ps.clusterMiss||0}`],['route cache',state.routeCacheHit?'HIT':'MISS'],['route resolve',fmt(state.routeResolveMs,0,'ms')],['initialDisplayMs',fmt(state.initialDisplayMs,0,'ms')],['routeProgress',Number.isFinite(state.currentProgress)?`${(state.currentProgress*100).toFixed(1)}%`:'—'],['routeDistance',fmt(state.currentRouteDistance,1,'m')],['travelHeading',fmt(state.currentTravelHeading,1,'°')],['userViewOffset',fmt(state.userViewOffset,1,'°')],['currentViewHeading',fmt(state.currentViewHeading,1,'°')],['360 / Rectilinear',state.currentProjection],['360 in route',`${state.route?.pano||0}/${state.route?.frames.length||0}`],['reverse events',String(state.reverseEvents)],['regression streak',String(state.regressionStreak)],['view jumps',String(state.viewJumps)],['stopReason',state.stopReason],['frameId',currentFrame()?.id||'—']];$('diagGrid').innerHTML=rows.map(([k,v])=>`<span>${k}</span><b>${String(v)}</b>`).join('')}
function diagnosticsText(){return JSON.stringify({test:'MapillaryJS',version:VERSION,start:state.start,goal:state.goal,sequenceId:state.route?.sequenceId||null,direction:state.route?.direction||null,targetFrames:state.route?.frames.length||0,requestedCadenceMs:Number($('speed').value)||DEFAULT_CADENCE,preloadTargetFrames:state.preloadTarget,preloadReadyAtOpen:state.preloadReadyAtOpen,preloadReadyFrames:state.preloaded.size,preloadRateFps:state.preloadRateFps,preloadAverageAssetMs:average(state.preloadTimes),preloadWallMs:state.preloadWallMs,preloadFailures:state.preloadFailures,successfulFrames:state.successfulFrames,initialDisplayMs:state.initialDisplayMs,averageImageTransitionMs:average(state.transitionTimes),averageCadenceMs:average(state.cadenceTimes),deadlineMisses:state.deadlineMisses,transitionMode:'Default',cacheDepth:CACHE_DEPTH,routeCacheHit:state.routeCacheHit,providerCache:state.providerStats,reverseEvents:state.reverseEvents,regressionStreak:state.regressionStreak,viewJumps:state.viewJumps,panoFrames:state.route?.pano||0,totalPreparedFrames:state.route?.frames.length||0,stopReason:state.stopReason,setupMs:state.setupMs,frames:state.logs},null,2)}
async function copyDiagnostics(){const text=diagnosticsText();try{await navigator.clipboard.writeText(text);setStatus('Diagnosticsをコピーしました')}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();setStatus('Diagnosticsをコピーしました')}}
async function openViewer(){
  if(!state.route||!state.provider)return;$('planner').hidden=true;$('viewerScreen').hidden=false;$('viewerRouteLabel').textContent=`${coordLabel(state.start)} → ${coordLabel(state.goal)} / 公式Viewer`;await initializeViewer()
}
function backToPlanner(){stopPlayback('planner',true);destroyViewer();$('viewerScreen').hidden=true;$('planner').hidden=false;state.map?.resize()}
function openTokenSheet(){$('tokenInput').value=token();$('tokenSheet').hidden=false}
function saveToken(){const v=$('tokenInput').value.trim();if(!v)return;try{localStorage.setItem(TOKEN_KEY,v)}catch{}$('tokenSheet').hidden=true;resetPlanner()}
