const HUD_AUTO_HIDE_MS=3500;
let hudHideTimer=null;
function journeyHudEl(){return document.querySelector('#viewerScreen .journey-hud')}
function clearHudHideTimer(){if(hudHideTimer){clearTimeout(hudHideTimer);hudHideTimer=null}}
function hideJourneyHud(){const hud=journeyHudEl();if(!hud)return;clearHudHideTimer();hud.style.transform='translateY(calc(100% + 36px))';hud.style.opacity='0';hud.style.pointerEvents='none'}
function showJourneyHud(autoHide=true){const hud=journeyHudEl();if(!hud)return;clearHudHideTimer();hud.style.transform='translateY(0)';hud.style.opacity='1';hud.style.pointerEvents='auto';if(autoHide&&!state.completed)hudHideTimer=setTimeout(hideJourneyHud,HUD_AUTO_HIDE_MS)}
function installHudBehavior(){const hud=journeyHudEl();if(!hud||hud.dataset.autoHideInstalled==='1')return;hud.dataset.autoHideInstalled='1';hud.style.transition='transform .28s cubic-bezier(.2,.8,.2,1),opacity .2s ease';hud.style.willChange='transform,opacity';const hold=()=>showJourneyHud(false),release=()=>showJourneyHud(true);hud.addEventListener('pointerdown',hold,{passive:true});hud.addEventListener('pointerup',release,{passive:true});hud.addEventListener('pointercancel',release,{passive:true});hud.addEventListener('input',release,{passive:true})}
function currentFrame(){return state.route?.frames[state.cursor]||null}
function nextFrame(){return state.route?.frames[state.cursor+1]||null}
function updateTravelHeading(){const a=currentFrame(),b=nextFrame()||state.route?.frames[state.cursor-1];state.currentTravelHeading=a&&b?bearing(a,b):null}
async function readBearing(){if(!state.viewer)return null;try{const b=await state.viewer.getBearing();if(Number.isFinite(b)){state.currentViewHeading=norm360(b);return state.currentViewHeading}}catch{}return null}
function setFrameMetrics(){const f=currentFrame();if(!f)return;state.currentProgress=f.routeProgress;state.currentRouteDistance=f.routeDistance;state.maxProgressSeen=Number.isFinite(state.maxProgressSeen)?Math.max(state.maxProgressSeen,f.routeProgress):f.routeProgress;updateTravelHeading();if(Number.isFinite(state.currentViewHeading)&&Number.isFinite(state.currentTravelHeading)){state.userViewOffset=angleDiff(state.currentViewHeading,state.currentTravelHeading);state.heldOffset=state.userViewOffset}renderJourneyHud();renderDiagnostics()}
async function gentlyPreservePano(offset){if(!state.viewer||state.pointerActive||state.currentProjection!=='360'||!Number.isFinite(state.currentTravelHeading))return;const before=await readBearing();if(!Number.isFinite(before))return;const desired=norm360(state.currentTravelHeading+offset),delta=angleDiff(desired,before);if(Math.abs(delta)<3)return;if(Math.abs(delta)>45)state.viewJumps++;if(Math.abs(delta)>75)return;let center;try{center=await state.viewer.getCenter()}catch{return}if(!Array.isArray(center)||center.length<2)return;state.correcting=true;const startX=Number(center[0]),y=clamp(Number(center[1]),.08,.92),steps=6;for(let i=1;i<=steps;i++){if(state.pointerActive)break;const eased=1-Math.pow(1-i/steps,2),x=((startX+(delta/360)*eased)%1+1)%1;state.viewer.setCenter([x,y]);await sleep(26)}state.correcting=false}
function installViewerEvents(){const el=state.viewer.getCanvasContainer?.()||$('mly');el.addEventListener('touchstart',()=>{state.pointerActive=true},{passive:true});el.addEventListener('touchend',()=>{state.pointerActive=false},{passive:true});el.addEventListener('touchcancel',()=>{state.pointerActive=false},{passive:true});el.addEventListener('click',()=>showJourneyHud(true),{passive:true});state.viewer.on('pov',async e=>{const b=await e.target.getBearing().catch(()=>null);if(!Number.isFinite(b))return;state.currentViewHeading=norm360(b);if(Number.isFinite(state.currentTravelHeading)&&(!state.correcting||state.pointerActive)){const off=angleDiff(state.currentViewHeading,state.currentTravelHeading);state.userViewOffset=off;if(state.pointerActive||!state.playing)state.heldOffset=off}renderDiagnostics()});state.viewer.on('image',e=>{const image=e?.image;if(image){state.currentProjection=String(image.cameraType||'').toLowerCase()==='spherical'?'360':'Rectilinear';renderDiagnostics()}})}
async function initializeViewer(){
  if(state.viewer||!state.route||!state.provider)return;const M=window.mapillary;if(!M?.Viewer)throw new Error('MapillaryJS 4.1.2を読み込めませんでした');state.cursor=0;state.successfulFrames=0;state.skippedFrames=0;state.consecutiveMoveErrors=0;state.transitionTimes=[];state.cadenceTimes=[];state.logs=[];state.stopReason='initializing';state.maxProgressSeen=null;state.regressionStreak=0;state.reverseEvents=0;state.viewJumps=0;state.deadlineMisses=0;state.completed=false;
  state.viewer=new M.Viewer({container:'mly',dataProvider:state.provider,imageTiling:true,transitionMode:M.TransitionMode.Default,component:{cover:false,cache:{depth:CACHE_DEPTH}}});try{state.viewer.getComponent('pointer').configure({dragPan:true,scrollZoom:false,touchZoom:true})}catch{}installViewerEvents();installHudBehavior();try{await state.viewer.setFilter(['==','sequenceId',state.route.sequenceId])}catch{}
  setStatus('最初の景色を表示中…');const t0=performance.now(),image=await moveToWithRetry(state.route.frames[0].id,3);state.initialDisplayMs=performance.now()-t0;state.successfulFrames=1;state.currentProjection=String(image?.cameraType||'').toLowerCase()==='spherical'||state.route.frames[0].isPano?'360':'Rectilinear';await readBearing();setFrameMetrics();logFrame();state.stopReason='ready';updatePlayButton();updatePreloadUI();backgroundWarm();renderDiagnostics();showJourneyHud(true)
}
async function moveToWithRetry(id,maxAttempts=3){let last;for(let i=0;i<maxAttempts;i++){try{return await state.viewer.moveTo(id)}catch(error){last=error;if(i+1<maxAttempts)await sleep(180*(i+1))}}throw last}
function reverseGuard(target){const maxSeen=Number.isFinite(state.maxProgressSeen)?state.maxProgressSeen:currentFrame()?.routeProgress,behind=Number.isFinite(maxSeen)?maxSeen-target.routeProgress:0;if(behind>REGRESSION_HARD){state.reverseEvents++;return'route-progress-hard-regression'}if(behind>REGRESSION_SOFT)state.regressionStreak++;else state.regressionStreak=Math.max(0,state.regressionStreak-1);return null}
async function moveOne(){
  const target=nextFrame();if(!target)return false;const guard=reverseGuard(target);if(guard){state.cursor++;state.skippedFrames++;state.stopReason=`skip:${guard}`;logFrame();renderJourneyHud();return true}
  const held=Number.isFinite(state.userViewOffset)?state.userViewOffset:0;state.heldOffset=held;const t0=performance.now();try{const image=await moveToWithRetry(target.id,3);const dt=performance.now()-t0;state.lastTransitionMs=dt;state.transitionTimes.push(dt);if(dt>Number($('speed').value))state.deadlineMisses++;state.cursor++;state.successfulFrames++;state.consecutiveMoveErrors=0;state.currentProjection=String(image?.cameraType||'').toLowerCase()==='spherical'||target.isPano?'360':'Rectilinear';const now=performance.now();if(Number.isFinite(state.lastDisplayAt)){state.lastCadenceMs=now-state.lastDisplayAt;state.cadenceTimes.push(state.lastCadenceMs)}state.lastDisplayAt=now;setFrameMetrics();await readBearing();await gentlyPreservePano(state.pointerActive?state.heldOffset:held);setFrameMetrics();state.stopReason='playing';logFrame();backgroundWarm();return true}catch(error){state.cursor++;state.skippedFrames++;state.consecutiveMoveErrors++;state.stopReason=`skip-load:${error?.message||error}`;state.lastTransitionMs=performance.now()-t0;logFrame();renderJourneyHud();backgroundWarm();await sleep(Math.min(600,140+state.consecutiveMoveErrors*80));return true}
}
async function playback(){
  if(state.playing||!state.viewer||state.completed)return;const run=++state.moveToken;state.playing=true;state.stopReason='playing';state.lastDisplayAt=performance.now();updatePlayButton();setStatus('自動再生中');showJourneyHud(true);try{state.viewer.setTransitionMode?.(window.mapillary.TransitionMode.Default)}catch{}while(state.playing&&run===state.moveToken&&state.cursor<state.route.frames.length-1){const ok=await moveOne();if(!ok||!state.playing)break;const hold=Number($('speed').value)||DEFAULT_CADENCE;if(hold>0)await sleep(hold)}if(state.playing&&state.cursor>=state.route.frames.length-1)completeJourney()
}
function pausePlayback(reason='user-pause',silent=false){state.playing=false;state.moveToken++;state.stopReason=reason;updatePlayButton();showJourneyHud(true);if(!silent)setStatus('一時停止');renderDiagnostics()}
function stopPlayback(reason='user-stop',silent=false){pausePlayback(reason,true);if(!silent)setStatus(`停止: ${reason}`)}
function completeJourney(){state.playing=false;state.moveToken++;state.completed=true;state.stopReason='arrived';updatePlayButton();renderJourneyHud();hideJourneyHud();$('arrivalText').textContent=`${state.selectedPlace?.name||'到着地'}まで ${distanceLabel(state.route?.totalDistanceM||0)} の旅を完了しました。`;$('arrivalOverlay').hidden=false;setStatus('到着しました')}
function destroyViewer(){clearHudHideTimer();if(state.viewer){try{state.viewer.remove()}catch{}state.viewer=null}if($('mly'))$('mly').innerHTML='';state.playing=false;state.moveToken++;updatePlayButton()}
function logFrame(){const f=currentFrame();state.logs.push({step:state.cursor+1,id:f?.id||null,distanceFromStartM:f?.distanceFromStartM??null,remainingDistanceM:f?.remainingDistanceM??null,stepDistanceM:f?.stepDistanceM??null,routeProgress:state.currentProgress,travelHeading:state.currentTravelHeading,userViewOffset:state.userViewOffset,currentViewHeading:state.currentViewHeading,imageTransitionMs:state.lastTransitionMs,actualCadenceMs:state.lastCadenceMs,projection:state.currentProjection,preloadAhead:contiguousAhead(),stopReason:state.stopReason})}
function renderJourneyHud(){const f=currentFrame(),total=state.route?.totalDistanceM||0,done=f?.distanceFromStartM||0,remain=Math.max(0,total-done),pct=total?clamp(done/total*100,0,100):0;if($('journeyProgress'))$('journeyProgress').value=Math.round(pct*10);if($('journeyProgressFill'))$('journeyProgressFill').style.width=`${pct}%`;if($('journeyDistance'))$('journeyDistance').textContent=`${distanceLabel(done)} / ${distanceLabel(total)}`;if($('journeyRemaining'))$('journeyRemaining').textContent=`残り ${distanceLabel(remain)}`;if($('journeyStep'))$('journeyStep').textContent=`+${distanceLabel(f?.stepDistanceM||0)}`;if($('journeyDepart'))$('journeyDepart').textContent=timeLabel(state.departureTime);if($('journeyArrive'))$('journeyArrive').textContent=timeLabel(state.arrivalTime);if($('journeyPercent'))$('journeyPercent').textContent=`${Math.round(pct)}%`;if($('journeyPlace'))$('journeyPlace').textContent=state.selectedPlace?.name||'到着地';updatePlayButton()}
function updatePlayButton(){if(!$('playToggle'))return;$('playToggle').textContent=state.playing?'Ⅱ  一時停止':'▶  再生';$('playToggle').disabled=!state.viewer||state.completed}
async function seekToRatio(ratio){if(!state.viewer||!state.route)return;showJourneyHud(false);const was=state.seekWasPlaying||state.playing;state.seekWasPlaying=false;pausePlayback('seeking',true);const idx=clamp(Math.round(ratio*(state.route.frames.length-1)),0,state.route.frames.length-1),target=state.route.frames[idx];setStatus(`${distanceLabel(target.distanceFromStartM)}へ移動中…`);try{const image=await moveToWithRetry(target.id,3);state.cursor=idx;state.currentProjection=String(image?.cameraType||'').toLowerCase()==='spherical'||target.isPano?'360':'Rectilinear';state.maxProgressSeen=target.routeProgress;await readBearing();setFrameMetrics();state.stopReason='seeked';logFrame();backgroundWarm()}catch(e){setStatus(`移動失敗: ${e?.message||e}`)}renderJourneyHud();showJourneyHud(true);if(was&&!state.completed)playback()}
function renderDiagnostics(){if(!$('diagGrid'))return;const ps=state.providerStats||{},f=currentFrame(),rows=[['version',VERSION],['frame / step',`${Math.min(state.cursor+1,state.route?.frames.length||0)} / ${state.route?.frames.length||0} (success ${state.successfulFrames}, skip ${state.skippedFrames})`],['sequenceId',state.route?.sequenceId||'—'],['Next / Prev',state.route?.direction||'—'],['distance',`${distanceLabel(f?.distanceFromStartM)} / ${distanceLabel(state.route?.totalDistanceM)}`],['remaining',distanceLabel(f?.remainingDistanceM)],['transition style','61c4 Default + hold'],['hold after transition',fmt(Number($('speed')?.value)||DEFAULT_CADENCE,0,'ms')],['actual cadence',fmt(state.lastCadenceMs,0,'ms')],['avg cadence',fmt(average(state.cadenceTimes),0,'ms')],['imageTransitionMs',fmt(state.lastTransitionMs,0,'ms')],['avgTransitionMs',fmt(average(state.transitionTimes),0,'ms')],['deadline misses',String(state.deadlineMisses)],['preload ready / target',`${state.preloaded.size} / ${state.preloadTarget||0}`],['preload ready at open',String(state.preloadReadyAtOpen)],['preload rate',fmt(state.preloadRateFps,2,'fps')],['preload wall',fmt(state.preloadWallMs,0,'ms')],['preload failures',String(state.preloadFailures)],['preload ahead',String(contiguousAhead())],['provider buffer hit/miss',`${ps.bufferHit||0} / ${ps.bufferMiss||0}`],['provider mesh hit/miss',`${ps.meshHit||0} / ${ps.meshMiss||0}`],['route cache',state.routeCacheHit?'HIT':'MISS'],['initialDisplayMs',fmt(state.initialDisplayMs,0,'ms')],['travelHeading',fmt(state.currentTravelHeading,1,'°')],['userViewOffset',fmt(state.userViewOffset,1,'°')],['currentViewHeading',fmt(state.currentViewHeading,1,'°')],['360 / Rectilinear',state.currentProjection],['reverse events',String(state.reverseEvents)],['view jumps',String(state.viewJumps)],['stopReason',state.stopReason],['frameId',f?.id||'—']];$('diagGrid').innerHTML=rows.map(([k,v])=>`<span>${k}</span><b>${String(v)}</b>`).join('')}
function diagnosticsText(){const f=currentFrame();return JSON.stringify({test:'MapillaryJS Journey',version:VERSION,start:state.start,goal:state.goal,place:state.selectedPlace?.name||null,sequenceId:state.route?.sequenceId||null,direction:state.route?.direction||null,totalDistanceM:state.route?.totalDistanceM||null,currentDistanceM:f?.distanceFromStartM||0,remainingDistanceM:f?.remainingDistanceM||null,departure:state.departureTime?.toISOString?.()||null,arrival:state.arrivalTime?.toISOString?.()||null,targetFrames:state.route?.frames.length||0,requestedCadenceMs:Number($('speed').value)||DEFAULT_CADENCE,playbackTiming:'61c4-default-transition-plus-hold',hudAutoHideMs:HUD_AUTO_HIDE_MS,preloadTargetFrames:state.preloadTarget,preloadReadyAtOpen:state.preloadReadyAtOpen,preloadReadyFrames:state.preloaded.size,preloadRateFps:state.preloadRateFps,preloadAverageAssetMs:average(state.preloadTimes),preloadWallMs:state.preloadWallMs,preloadFailures:state.preloadFailures,successfulFrames:state.successfulFrames,skippedFrames:state.skippedFrames,initialDisplayMs:state.initialDisplayMs,averageImageTransitionMs:average(state.transitionTimes),averageCadenceMs:average(state.cadenceTimes),deadlineMisses:state.deadlineMisses,transitionMode:'Default',cacheDepth:CACHE_DEPTH,routeCacheHit:state.routeCacheHit,providerCache:state.providerStats,reverseEvents:state.reverseEvents,viewJumps:state.viewJumps,panoFrames:state.route?.pano||0,totalPreparedFrames:state.route?.frames.length||0,stopReason:state.stopReason,setupMs:state.setupMs,frames:state.logs},null,2)}
async function copyDiagnostics(){const text=diagnosticsText();try{await navigator.clipboard.writeText(text);setStatus('Diagnosticsをコピーしました')}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();setStatus('Diagnosticsをコピーしました')}}
async function startJourney(){if(!state.route||!state.provider||state.preloaded.size<Math.min(PRELOAD_MIN,state.route.frames.length))return;state.departureTime=new Date();state.durationSec=estimateDurationSec(state.route.totalDistanceM,state.totalAscentM);state.arrivalTime=new Date(state.departureTime.getTime()+state.durationSec*1000);$('tripSheet').hidden=true;$('planner').hidden=true;$('viewerScreen').hidden=false;$('arrivalOverlay').hidden=true;$('viewerRouteLabel').textContent=`${state.selectedPlace?.name||'到着地'} ・ ${distanceLabel(state.route.totalDistanceM)}`;await initializeViewer();renderJourneyHud();showJourneyHud(true);playback()}
function backToPlanner(){pausePlayback('planner',true);destroyViewer();$('viewerScreen').hidden=true;$('planner').hidden=false;$('arrivalOverlay').hidden=true;state.map?.resize()}
function finishJourney(){const goal=state.goal?{...state.goal}:null;backToPlanner();resetPlanner();if(goal)state.map?.easeTo({center:[goal.lng,goal.lat],zoom:12.5,duration:400})}
function openTokenSheet(){$('tokenInput').value=token();$('tokenSheet').hidden=false}
function saveToken(){const v=$('tokenInput').value.trim();if(!v)return;try{localStorage.setItem(TOKEN_KEY,v)}catch{}$('tokenSheet').hidden=true;resetPlanner()}
