/* Streetview Journey Phase 4 Journey Graph + KartaView + Mapillary analysis proxy + OSM transport */
const KARTA_API='https://api.openstreetcam.org/2.0';
const OVERPASS_API='https://overpass-api.de/api/interpreter';
const PAGE_SIZE=150,MAX_PAGES=120,DIRECT_TAP_LIMIT=220,MAPILLARY_IMAGE_TIMEOUT_MS=12000,GRAPH_SEQUENCE_LIMIT=18,GRAPH_POINT_LIMIT=9;
const OSM_POINT_LIMIT=8,OSM_RADIUS_M=55,OSM_TIMEOUT_MS=6500,OSM_CACHE_TTL_MS=5*60*1000;
const osmCache=new Map();
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function extract(j){const d=j?.result?.data;if(Array.isArray(d))return d;if(d&&Array.isArray(d.photos))return d.photos;return[]}
function sid(p){return String(p?.sequenceId??p?.sequence?.id??'').trim()}
function imageUrl(p){return p?.fileurlLTh||p?.fileurlTh||p?.fileurlProc||p?.fileurl||null}
function norm(p){const url=imageUrl(p);if(!url)return null;return{id:String(p.id??p.photoId??''),sequenceId:sid(p),sequenceIndex:num(p.sequenceIndex),lat:num(p.lat??p.matchLat),lng:num(p.lng??p.matchLng),heading:num(p.heading),projectionYaw:num(p.projectionYaw),projection:p.projection||null,fieldOfView:num(p.fieldOfView),width:num(p.width),height:num(p.height),url,provider:'KartaView'}}
function coords(p){return Number.isFinite(p?.lat)&&Number.isFinite(p?.lng)}
function dist(a,b){if(!coords(a)||!coords(b))return Infinity;const r=Math.PI/180,p1=a.lat*r,p2=b.lat*r,dp=(b.lat-a.lat)*r,dl=(b.lng-a.lng)*r,s=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 12742000*Math.atan2(Math.sqrt(s),Math.sqrt(Math.max(0,1-s)))}
function dedupe(list){const seen=new Set(),out=[];for(const raw of list){const p=norm(raw)||raw;if(!p?.url)continue;const k=p.id||`${p.sequenceId}:${p.sequenceIndex}`||p.url;if(seen.has(k))continue;seen.add(k);out.push(p)}out.sort((a,b)=>(a.sequenceIndex??0)-(b.sequenceIndex??0));return out}
async function json(url){const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`KartaView upstream ${r.status}`);const j=await r.json();if(Number(j?.status?.httpCode)>=400)throw new Error(`KartaView API ${j?.status?.apiCode||j?.status?.httpCode}`);return j}
async function nearby(lat,lng,z){const q=new URLSearchParams({lat:String(lat),lng:String(lng),zoomLevel:String(z),join:'sequence',orderBy:'id',orderDirection:'desc'});try{return extract(await json(`${KARTA_API}/photo/?${q}`))}catch{return[]}}
async function page(sequenceId,pageNo){const q=new URLSearchParams({sequenceId,page:String(pageNo),itemsPerPage:String(PAGE_SIZE)});return extract(await json(`${KARTA_API}/photo/?${q}`))}
async function allSequence(sequenceId){const first=await page(sequenceId,1);let all=[...first];if(first.length<PAGE_SIZE)return dedupe(all);for(let start=2;start<=MAX_PAGES;start+=4){const nums=[start,start+1,start+2,start+3].filter(x=>x<=MAX_PAGES),chunks=await Promise.all(nums.map(p=>page(sequenceId,p).catch(()=>[])));chunks.forEach(c=>all.push(...c));if(chunks.some(c=>c.length<PAGE_SIZE))break}return dedupe(all)}
function nearestIndex(frames,target){let best=-1,bd=Infinity;for(let i=0;i<frames.length;i++){const d=dist(frames[i],target);if(d<bd){bd=d;best=i}}return{index:best,distance:bd}}
function routeSegment(frames,startIndex,dest){if(!frames.length)return{frames:[],destinationDistanceMeters:null,startIndex:0,endIndex:0};const start=Math.max(0,Math.min(frames.length-1,startIndex));if(!dest)return{frames:frames.slice(start),destinationDistanceMeters:null,startIndex:start,endIndex:frames.length-1};const hit=nearestIndex(frames,dest);if(hit.index<0)return{frames:frames.slice(start),destinationDistanceMeters:null,startIndex:start,endIndex:frames.length-1};const section=hit.index>=start?frames.slice(start,hit.index+1):frames.slice(hit.index,start+1).reverse();return{frames:section.length>=2?section:frames.slice(start),destinationDistanceMeters:hit.distance,startIndex:start,endIndex:hit.index}}
async function directTap(lat,lng,dest){const target={lat,lng},raw=(await Promise.all([18,17,16,15].map(z=>nearby(lat,lng,z)))).flat(),seen=new Set(),hits=[];for(const x of raw){const p=norm(x),sequenceId=sid(x);if(!p||!sequenceId||!coords(p))continue;const k=p.id||`${sequenceId}:${p.sequenceIndex}`;if(seen.has(k))continue;seen.add(k);hits.push({p,sequenceId,distance:dist(target,p)})}hits.sort((a,b)=>a.distance-b.distance);const hit=hits[0];if(!hit||!Number.isFinite(hit.distance)||hit.distance>DIRECT_TAP_LIMIT)return null;const frames=await allSequence(hit.sequenceId);if(frames.length<2)return null;let anchor=frames.findIndex(f=>f.id===hit.p.id);if(anchor<0&&Number.isFinite(hit.p.sequenceIndex)){let bd=Infinity;for(let i=0;i<frames.length;i++){if(!Number.isFinite(frames[i].sequenceIndex))continue;const d=Math.abs(frames[i].sequenceIndex-hit.p.sequenceIndex);if(d<bd){bd=d;anchor=i}}}if(anchor<0)anchor=0;const seg=routeSegment(frames,anchor,dest);if(seg.frames.length<2)return null;return{version:'0.5.0',source:'KartaView',provider:'KartaView',sequenceId:hit.sequenceId,anchorIndex:anchor,destination:dest||null,selection:{strategy:dest?'destination-sequence-segment':'direct-nearest-photo-full',direction:seg.endIndex>=seg.startIndex?'forward':'reverse',proximityMeters:hit.distance,destinationDistanceMeters:seg.destinationDistanceMeters,searchMode:'tap-direct-full',candidateCount:1,visualOverride:false,totalSequenceFrames:frames.length,segmentStartIndex:seg.startIndex,segmentEndIndex:seg.endIndex},frames:seg.frames,candidateRoutes:[]}}
function parseGraphPoints(value){return String(value||'').split(';').slice(0,GRAPH_POINT_LIMIT).map(s=>{const [lat,lng]=s.split(',').map(Number);return Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null}).filter(Boolean)}
async function graphNearby(points,limit){const zooms=[18,17,16],requests=[];for(const p of points)for(const z of zooms)requests.push(nearby(p.lat,p.lng,z));const raw=(await Promise.all(requests)).flat(),groups=new Map();for(const x of raw){const p=norm(x),sequenceId=sid(x);if(!p||!sequenceId||!coords(p))continue;if(!groups.has(sequenceId))groups.set(sequenceId,{sequenceId,photos:new Map(),minDistance:Infinity});const g=groups.get(sequenceId),k=p.id||String(p.sequenceIndex??`${p.lat},${p.lng}`);g.photos.set(k,p);for(const q of points)g.minDistance=Math.min(g.minDistance,dist(p,q))}const seqs=[...groups.values()].sort((a,b)=>a.minDistance-b.minDistance).slice(0,Math.max(1,Math.min(GRAPH_SEQUENCE_LIMIT,limit||GRAPH_SEQUENCE_LIMIT))).map(g=>{const photos=[...g.photos.values()].sort((a,b)=>(a.sequenceIndex??0)-(b.sequenceIndex??0)),coords=[];for(const p of photos){const c=[p.lng,p.lat],last=coords[coords.length-1];if(!last||Math.abs(last[0]-c[0])>1e-7||Math.abs(last[1]-c[1])>1e-7)coords.push(c)}return{sequenceId:g.sequenceId,minDistanceMeters:g.minDistance,coords,photoCount:photos.length}}).filter(x=>x.coords.length>1);return{version:'0.5.0-journey-graph',provider:'KartaView',points,sequences:seqs}}

function parseTransportPoints(value){return String(value||'').split(';').slice(0,OSM_POINT_LIMIT).map(s=>{const [lat,lng]=s.split(',').map(Number);return Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180?{lat,lng}:null}).filter(Boolean)}
function transportCacheKey(points){return points.map(p=>`${p.lat.toFixed(4)},${p.lng.toFixed(4)}`).join(';')}
function overpassTransportQuery(points){const parts=[];for(const p of points){const at=`around:${OSM_RADIUS_M},${p.lat},${p.lng}`;parts.push(`nwr(${at})["highway"]`);parts.push(`nwr(${at})["railway"~"^(rail|tram|subway|light_rail)$"]`)}return`[out:json][timeout:10];(${parts.join(';')};);out tags center;`}
function summarizeOsm(elements){const highway={},railway={},surface={},features=[];for(const e of Array.isArray(elements)?elements:[]){const t=e?.tags||{},h=String(t.highway||''),r=String(t.railway||''),s=String(t.surface||'');if(h)highway[h]=(highway[h]||0)+1;if(r)railway[r]=(railway[r]||0)+1;if(s)surface[s]=(surface[s]||0)+1;if((h||r)&&features.length<80)features.push({type:e.type||null,id:e.id||null,highway:h||null,railway:r||null,surface:s||null,access:t.access||null,bicycle:t.bicycle||null,foot:t.foot||null})}return{highway,railway,surface,featureCount:features.length,features}}
async function osmTransport(points){const key=transportCacheKey(points),cached=osmCache.get(key);if(cached&&Date.now()-cached.at<OSM_CACHE_TTL_MS)return{...cached.data,cache:'memory'};const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),OSM_TIMEOUT_MS);try{const query=overpassTransportQuery(points),r=await fetch(OVERPASS_API,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8','User-Agent':'StreetviewJourney/1.0'},body:`data=${encodeURIComponent(query)}`,signal:controller.signal}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Overpass ${r.status}`);const summary=summarizeOsm(j?.elements);const data={version:'0.1.0-osm-transport',points,radiusMeters:OSM_RADIUS_M,...summary,cache:'miss'};osmCache.set(key,{at:Date.now(),data});if(osmCache.size>80){const first=osmCache.keys().next().value;osmCache.delete(first)}return data}catch(e){return{version:'0.1.0-osm-transport',points,radiusMeters:OSM_RADIUS_M,highway:{},railway:{},surface:{},featureCount:0,features:[],cache:'error',error:e?.name==='AbortError'?'Overpass timeout':String(e?.message||e)}}finally{clearTimeout(timer)}}

function analysisImageUrl(raw){if(typeof raw!=='string'||!raw||raw.length>5000)return null;try{const u=new URL(raw),h=u.hostname.toLowerCase();if(u.protocol!=='https:')return null;const ok=h==='fbcdn.net'||h.endsWith('.fbcdn.net')||h==='openstreetcam.org'||h.endsWith('.openstreetcam.org')||h==='kartaview.org'||h.endsWith('.kartaview.org');return ok?u:null}catch{return null}}
async function proxyAnalysisImage(req,res){const target=analysisImageUrl(String(req.query.url||''));if(!target)return res.status(400).json({error:'無効な解析画像URLです'});const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),MAPILLARY_IMAGE_TIMEOUT_MS);try{const upstream=await fetch(target,{signal:controller.signal,redirect:'follow',headers:{Accept:'image/avif,image/webp,image/apng,image/*,*/*;q=0.8','User-Agent':'Mozilla/5.0 StreetviewJourney/1.0'}}),finalUrl=analysisImageUrl(upstream.url||target.href);if(!finalUrl||!upstream.ok)return res.status(502).json({error:`解析画像取得失敗 ${upstream.status}`});const type=upstream.headers.get('content-type')||'';if(!type.toLowerCase().startsWith('image/'))return res.status(502).json({error:'解析画像レスポンスが画像ではありません'});const data=Buffer.from(await upstream.arrayBuffer());res.statusCode=200;res.setHeader('Content-Type',type);res.setHeader('Content-Length',String(data.length));res.setHeader('Cache-Control','public, max-age=300, s-maxage=300, stale-while-revalidate=600');res.setHeader('Cross-Origin-Resource-Policy','same-origin');return res.end(data)}catch(e){if(e?.name==='AbortError')return res.status(504).json({error:'解析画像取得がタイムアウトしました'});console.error('analysis image proxy error',e);return res.status(502).json({error:'解析画像を取得できませんでした'})}finally{clearTimeout(timer)}}

async function handler(req,res){try{
  if(req.query.mode==='mapillary-image')return proxyAnalysisImage(req,res);
  if(req.query.mode==='osm-transport'){const points=parseTransportPoints(req.query.points);if(!points.length)return res.status(400).json({error:'OSM道路分類用の有効なpointsが必要です'});res.setHeader('Cache-Control','public, s-maxage=300, stale-while-revalidate=1800');res.setHeader('Content-Type','application/json; charset=utf-8');return res.status(200).json(await osmTransport(points))}
  res.setHeader('Cache-Control','public, s-maxage=60, stale-while-revalidate=300');res.setHeader('Content-Type','application/json; charset=utf-8');
  if((req.query.source||'karta')!=='karta')return res.status(400).json({error:'KartaViewルートのみこのAPIで扱います'});
  if(req.query.mode==='graph-nearby'){const points=parseGraphPoints(req.query.points),limit=Number(req.query.limit)||GRAPH_SEQUENCE_LIMIT;if(!points.length)return res.status(400).json({error:'Journey Graph用の有効なpointsが必要です'});return res.status(200).json(await graphNearby(points,limit))}
  if(req.query.mode==='nearest'){const lat=Number(req.query.lat),lng=Number(req.query.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return res.status(400).json({error:'有効な緯度・経度が必要です'});const dl=Number(req.query.destLat),dn=Number(req.query.destLng),dest=Number.isFinite(dl)&&Number.isFinite(dn)?{lat:dl,lng:dn}:null,route=await directTap(lat,lng,dest);if(!route)return res.status(404).json({error:`タップ地点から${DIRECT_TAP_LIMIT}m以内に直接選択できるKartaView sequenceが見つかりませんでした`});return res.status(200).json(route)}
  const sequenceId=String(req.query.sequence||'').trim();if(sequenceId){const frames=await allSequence(sequenceId);if(frames.length<2)return res.status(404).json({error:'再生可能な画像が不足しています'});return res.status(200).json({version:'0.5.0',source:'KartaView',provider:'KartaView',sequenceId,selection:{strategy:'full-sequence',totalSequenceFrames:frames.length},frames,candidateRoutes:[]})}
  return res.status(400).json({error:'Journey Graphでは地図上で出発地点を選択してください'});
}catch(e){console.error('imagery route error',e);return res.status(502).json({error:'KartaViewからルートを取得できませんでした'})}}
handler._test={parseTransportPoints,overpassTransportQuery,summarizeOsm,routeSegment,parseGraphPoints};
module.exports=handler;
